/**
 * @file nvm.c
 * @author Joel Santos (jsantosrico@gmail.com)
 * @brief General use of the NVM3 module to store stuff in the internal flash of the chip.
 * @version 0.1
 * @date 2026-03-09
 *
 * @copyright Copyright (c) 2026
 *
 */

#include "nvm_HW.h"

#include <string.h>

// This one has to be higher in the chain
#include "sl_status.h"  // fake version in /support
// Silab's headers
#include "app_log.h"
#include "nvm3.h"
#include "nvm3_default_config.h"  // Config stuff to use the default nvm3 area and not need to mess with the linkerfile
#include "nvm3_hal_flash.h"       // driver for internal flash on nvm3

// our headers
#include "effectControl.h"

/**
 * @brief Use default nvm3 area
 * I explored a bit and there was no simpler way that I found to this without having to modify the linkerscript. Nothing
 * wrong with that, but it's an autogenerated file, so changes are very volatile.
 */
#ifndef TEST
#if (NVM3_DEFAULT_CACHE_SIZE != 0)
static nvm3_CacheEntry_t nvm3_cache[NVM3_DEFAULT_CACHE_SIZE];
#endif
extern const uint32_t linker_nvm_begin[];      // Start of NVM (end boundary of CRC range)
extern const uint32_t linker_vectors_begin[];  // Start of vector table / beginning of CRC range
#define MAIN_FLASH_BASE ((uint32_t)linker_vectors_begin)
#define MAIN_FLASH_END ((uint32_t)linker_nvm_begin)
#define NVM3_BASE MAIN_FLASH_END
nvm3_Init_t nvm3_init_data = {
    (nvm3_HalPtr_t)NVM3_BASE,
    NVM3_DEFAULT_NVM_SIZE,
#if (NVM3_DEFAULT_CACHE_SIZE != 0)
    nvm3_cache,
#else
    NULL,
#endif
    NVM3_DEFAULT_CACHE_SIZE,
    NVM3_DEFAULT_MAX_OBJECT_SIZE,
    NVM3_DEFAULT_REPACK_HEADROOM,
    &nvm3_halFlashHandle,
};
#else   // TEST
// Trickery need to be able to test, otherwise it complains about NVM3_BASE not being constant initializer
nvm3_Init_t nvm3_init_data = {0};
#endif  // TEST

static nvm3_Handle_t handle;

/**
 * @brief Initialises the NVM
 */
void nvm_init(void) {
    sl_status_t status;

    // Initialize the handle to zero
    (void)memset(&handle, 0, sizeof(nvm3_Handle_t));

    // Open NVM3
    status = nvm3_open(&handle, &nvm3_init_data);
    if (status != SL_STATUS_OK) {
        // Handle error
        return;
    }
}

/**
 * @brief reads an LED Channel Context from NVM
 * @param key the NVM key for the channel to recover fron NVM
 * @param ptrContext a pointer to an LEDContext_t struct to store the data read from NVM
 */
void nvm_readLEDContext(const nvmKeys_t key, LEDContext_t* ptrContext) {
    uint32_t objectType = 0;
    size_t dataLen = 0;

    uint32_t numObjs = nvm3_countObjects(&handle);
    if (numObjs == 0UL) {
        app_log_warning("No objects to retrieve on NVM\r\n");
        return;
    }
    // Find size of data for the object
    // TODO: test key
    sl_status_t status = nvm3_getObjectInfo(&handle, key, &objectType, &dataLen);
    if (status == SL_STATUS_NOT_FOUND) {
        app_log_warning("No items on NVM yet!\r\n");
        return;
    } else if (status != SL_STATUS_OK) {
        app_log_error("Error 0x%04" PRIX32 " on getinfo\r\n", (uint32_t)status);
        return;
    }
    if (dataLen != sizeof(LEDContext_t)) {
        app_log_error("Don't know what the NVM had but len is wrong => %" PRIu32 "\r\n", (uint32_t)dataLen);
        app_log_critical("**** ERASING NVM ****");
        nvm3_eraseAll(&handle);
        return;
    }
    // TODO: add test for object size
    if (objectType == NVM3_OBJECTTYPE_DATA) {
        nvm3_readData(&handle, key, ptrContext, dataLen);  //TODO: test for status
        if (status != SL_STATUS_OK) {
            app_log_error("Error on readData\r\n");
            return;
        }
        // app_log_info("Object 0x%04" PRIX32 " has len %" PRIu32 "\r\n", (uint32_t)key, (uint32_t)dataLen);
        // app_log_debug("\tCurr Anim %" PRIu32 "\r\n", (uint32_t)ptrContext->currAnimation);
        // app_log_debug("\tBreathe Period %" PRIu32 "\r\n", ptrContext->currBreathePeriod);
        // app_log_debug("\tBrightness %" PRIu32 "\r\n", ptrContext->currBrightness);
    }
}

/**
 * @brief Writes an LED channel context to the NVM, so it can be recovered later
 * @param key the NVM item key for the channel we want to store
 * @param ptrContext a pointer to an LEDcontext_t object, with the data to store
 */
void nvm_writeLEDContext(const nvmKeys_t key, const LEDContext_t* ptrContext) {
    // app_log_info("Storing\r\n");
    // app_log_debug("\tCurr Anim %" PRIu32 "\r\n", (uint32_t)ptrContext->currAnimtion);
    // app_log_debug("\tBreathe Period %" PRIu32 "\r\n", ptrContext->currBreathePeriod);
    // app_log_debug("\tBrightness %" PRIu32 "\r\n", ptrContext->currBrightness);
    sl_status_t status = nvm3_writeData(&handle, key, ptrContext, sizeof(LEDContext_t));
    if (status != SL_STATUS_OK) {
        app_log_error("Error on writeData\r\n");
        return;
    }
}

/**
 * @brief Checks if an nvm repack is needed, and performs one if that's the case
 */
void nvm_checkForRepack(void) {
    // TODO: check for status
    if (nvm3_repackNeeded(&handle)) {
        nvm3_repack(&handle);
    }
}