#eyJzdGF0ZSI6eyJidWlsZFByZXNldHMiOnsiZGVmYXVsdF9jb25maWciOnsibmFtZSI6ImRlZmF1bHRfY29uZmlnIiwiY29uZmlndXJhdGlvbiI6ImJhc2UiLCJkZWZpbml0aW9ucyI6W10sInJlbW92ZWRGbGFncyI6eyJDIjpbIi1PcyIsIi1nIl0sIkNYWCI6WyItT3MiLCItZyJdLCJBU00iOltdfSwiYWRkaXRpb25hbEZsYWdzIjp7IkMiOlsiLU9nIiwiLWdnZGIzIl0sIkNYWCI6WyItT2ciLCItZ2dkYjMiXSwiQVNNIjpbXX19fSwiY3VycmVudENvbmZJbmRleCI6MH0sImZvbGRlcnMiOltdLCJmaWxlcyI6W119
target_compile_options(slc PRIVATE
	"$<$<AND:$<CONFIG:base>,$<COMPILE_LANGUAGE:C>>:-Og>"
	"$<$<AND:$<CONFIG:base>,$<COMPILE_LANGUAGE:C>>:-ggdb3>"
	"$<$<AND:$<CONFIG:base>,$<COMPILE_LANGUAGE:CXX>>:-Og>"
	"$<$<AND:$<CONFIG:base>,$<COMPILE_LANGUAGE:CXX>>:-ggdb3>"
)
