####################################################################
# Automatically-generated file. Do not edit!                       #
####################################################################

set(SDK_PATH "C:/Users/mundo/.silabs/slt/installs/conan/p/simpleb526998f4a4d/p")
set(COPIED_SDK_PATH "simplicity_sdk_2025.6.2")
set(PKG_PATH "C:/Users/mundo/.silabs/slt/installs")

add_library(slc OBJECT
    "../${COPIED_SDK_PATH}/app/common/util/app_log/app_log.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_assert.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_core_cortexm.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_slist.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_string.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_syscalls.c"
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/BGM22/Source/startup_bgm22.c"
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/BGM22/Source/system_bgm22.c"
    "../${COPIED_SDK_PATH}/platform/driver/gpio/src/sl_gpio.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/dmadrv/src/dmadrv.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/gpiointerrupt/src/gpiointerrupt.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_cache.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_hal_flash.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_object.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_page.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_utils.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_burtc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_cmu.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_emu.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_eusart.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_gpio.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_iadc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_ldma.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_msc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_prs.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_rtcc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_system.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_timer.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_eusart.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_gpio.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_prs.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_system.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/fem_util/sl_fem_util.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/pa_conversions_efr32.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_power_manager_init/sl_rail_util_power_manager_init.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_pti/sl_rail_util_pti.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_attestation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_entropy.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_hash.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_handling.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_signature.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_util.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sli_se_manager_mailbox.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/cryptoacc_aes.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/cryptoacc_gcm.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ccm.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_cmac.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ecdsa_ecdh.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_protocol_crypto/src/sli_protocol_crypto_radioaes.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_protocol_crypto/src/sli_radioaes_management.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/cryptoacc_management.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sl_psa_its_nvm3.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_driver_trng.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_aead.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_hash.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_key_management.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_mac.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_signature.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_trng.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sli_crypto/src/sl_crypto_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager_init.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager_init_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_init/src/sl_device_init_dcdc_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/clocks/sl_device_clock_efr32xg22.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/devices/sl_device_peripheral_hal_efr32xg22.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_clock.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_gpio.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_peripheral.c"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/src/sl_interrupt_manager_cortexm.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream_eusart.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream_retarget_stdio.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream_stdlib_config.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream_uart.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/profiler/src/sli_memory_profiler_stubs.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_dynamic_reservation.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_pool.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_pool_common.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_region.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_retarget.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sli_memory_manager_common.c"
    "../${COPIED_SDK_PATH}/platform/service/mpu/src/sl_mpu_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/common/sl_power_manager_common.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/common/sl_power_manager_em4.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/sleep_loop/sl_power_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/sleep_loop/sl_power_manager_debug.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/sleep_loop/sl_power_manager_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/sl_system_compatibility/src/sl_system_compatibility.c"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/src/sl_main_init.c"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/src/sl_main_init_memory.c"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/src/sl_main_process_action.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c"
    "../${COPIED_SDK_PATH}/platform/service/udelay/src/sl_udelay.c"
    "../${COPIED_SDK_PATH}/platform/service/udelay/src/sl_udelay_armv6m_gcc.S"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgcommon/src/sli_bgcommon_debug_efr32.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgstack/ll/src/sl_btctrl_init.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgstack/ll/src/sl_btctrl_init_tasklets.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sl_bt_stack_init.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_accept_list_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_advertiser_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_connection_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_dynamic_gattdb_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_external_bondingdb_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_host_adaptation.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_l2cap_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_pawr_advertiser_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_periodic_advertiser_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_sync_config.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/ba414ep_config.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/ba431_config.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/cryptodma_internal.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/cryptolib_types.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_aes.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_blk_cipher.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_dh_alg.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_ecc_curves.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_ecc_keygen_alg.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_ecdsa_alg.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_hash.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_math.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_memcmp.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_memcpy.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_primitives.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_rng.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_trng.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/cipher.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/cipher_wrap.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/constant_time.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/platform.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/platform_util.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_aead.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_cipher.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_client.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_driver_wrappers_no_static.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ecp.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ffdh.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_hash.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_mac.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_pake.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_rsa.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_se.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_slot_management.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_storage.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_util.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/threading.c"
    "../app.c"
    "../autogen/gatt_db.c"
    "../autogen/sl_bluetooth.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
    "../autogen/sl_iostream_init_eusart_instances.c"
    "../autogen/sl_power_manager_handler.c"
    "../main.c"
    "../sl_gatt_service_device_information.c"
    "../sl_gatt_service_device_information_warning.c"
)

target_include_directories(slc PUBLIC
   "../autogen"
   "../config"
   "../config/btconf"
   "../."
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/BGM22/Include"
    "../${COPIED_SDK_PATH}/app/common/util/app_assert"
    "../${COPIED_SDK_PATH}/app/common/util/app_log"
    "../${COPIED_SDK_PATH}/platform/common/inc"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/inc"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgcommon/inc"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgstack/ll/inc"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src"
    "../${COPIED_SDK_PATH}/platform/CMSIS/Core/Include"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/device_init/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/dmadrv/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/dmadrv/inc/s2_signals"
    "../${COPIED_SDK_PATH}/platform/emdrv/common/inc"
    "../${COPIED_SDK_PATH}/platform/emlib/inc"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/fem_util"
    "../${COPIED_SDK_PATH}/app/bluetooth/common/gatt_service_device_information_legacy"
    "../${COPIED_SDK_PATH}/platform/driver/gpio/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/gpiointerrupt/inc"
    "../${COPIED_SDK_PATH}/platform/peripheral/inc"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/src"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/inc/arm"
    "../${COPIED_SDK_PATH}/platform/service/iostream/inc"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/include"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/inc"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/include"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/profiler/inc"
    "../${COPIED_SDK_PATH}/platform/service/mpu/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/config"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/inc"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/inc"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/common"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/ble"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/ieee802154"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/wmbus"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/zwave"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/chip/efr32/efr32xg2x"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/sidewalk"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/efr32xg22"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_power_manager_init"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_pti"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/inc"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/src"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/sl_system_compatibility/inc"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/inc"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sli_crypto/inc"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_protocol_crypto/src"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sli_psec_osal/inc"
    "../${COPIED_SDK_PATH}/platform/service/udelay/inc"
)

target_compile_definitions(slc PUBLIC
    "BGM220PC22WGA=1"
    "SL_CODE_COMPONENT_SYSTEM=system"
    "SL_CODE_COMPONENT_CLOCK_MANAGER=clock_manager"
    "SL_COMPONENT_CATALOG_PRESENT=1"
    "SL_CODE_COMPONENT_DEVICE_PERIPHERAL=device_peripheral"
    "SL_CODE_COMPONENT_DMADRV=dmadrv"
    "SL_CODE_COMPONENT_GPIO=gpio"
    "SL_CODE_COMPONENT_HAL_COMMON=hal_common"
    "SL_CODE_COMPONENT_HAL_GPIO=hal_gpio"
    "SL_CODE_COMPONENT_INTERRUPT_MANAGER=interrupt_manager"
    "CMSIS_NVIC_VIRTUAL=1"
    "CMSIS_NVIC_VIRTUAL_HEADER_FILE=\"cmsis_nvic_virtual.h\""
    "MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>"
    "SL_CODE_COMPONENT_POWER_MANAGER=power_manager"
    "MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>"
    "SL_RAIL_LIB_MULTIPROTOCOL_SUPPORT=0"
    "SL_RAIL_UTIL_PA_CONFIG_HEADER=<sl_rail_util_pa_config.h>"
    "SL_CODE_COMPONENT_SE_MANAGER=se_manager"
    "SL_CODE_COMPONENT_CORE=core"
    "SL_RAIL_3_API=1"
    "SL_CODE_COMPONENT_SLEEPTIMER=sleeptimer"
    "SL_CODE_COMPONENT_SLI_CRYPTO=sli_crypto"
    "SLI_RADIOAES_REQUIRES_MASKING=1"
    "SL_CODE_COMPONENT_SLI_PROTOCOL_CRYPTO=sli_protocol_crypto"
    "SL_CODE_COMPONENT_PSEC_OSAL=psec_osal"
)

target_link_libraries(slc PUBLIC
    "-Wl,--start-group"
    "gcc"
    "c"
    "m"
    "nosys"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/bgcommon/lib/build/gcc/cortex-m33/bgcommon/release/libbgcommon.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/bgstack/ll/build/gcc/xg22/release/liblinklayer.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/bgstack/release/libbondingdb.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/ble_bgapi/release/libble_bgapi_gatt_client.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/ble_bgapi/release/libble_bgapi_gatt_server.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/bgapi_protocol/api3/release/libbgapi_core.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/accept_list/release/libble_host_accept_list_stub.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/bgstack/release/libble_host.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/ble_bgapi/release/libble_bgapi.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/ble_system/release/libble_system.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/connection_subrating/release/libble_host_connection_subrating_stub.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/core/release/libble_host_core.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/hal/release/libble_host_hal_series2.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/hci/release/libble_host_hci.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/system/release/libble_host_system.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/platform/radio/rail_lib/autogen/librail_release/librail_config_bgm220pc22wga_gcc.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/platform/radio/rail_lib/autogen/librail_release/librail_module_efr32xg22_gcc_release.a"
    "-Wl,--end-group"
)
target_compile_options(slc PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:C>:-mcmse>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:C>:-fno-lto>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-mcmse>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-lto>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=hard>
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-x assembler-with-cpp>"
)

set(post_build_command )
set_property(TARGET slc PROPERTY C_STANDARD 17)
set_property(TARGET slc PROPERTY CXX_STANDARD 17)
set_property(TARGET slc PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc INTERFACE
    -mcpu=cortex-m33
    -mthumb
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    "SHELL:-Xlinker -Map=$<TARGET_FILE_DIR:Gruffalo_Dimmer>/Gruffalo_Dimmer.map"
    "SHELL:-Wl,--wrap=_free_r -Wl,--wrap=_malloc_r -Wl,--wrap=_calloc_r -Wl,--wrap=_realloc_r"
    -Wl,--wrap=sl_system_init,--wrap=sl_system_process_action
    -fno-lto
    -Wl,--gc-sections
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztvQmT3DaW7/tVHIqJF3dxJVVZktuja3eHW6r21L2SpaeSZ97EaIKBJJGZdHG7XGpxR3/3B4AEV5AEiAOS1dMzbUmZSf7P72Df8dcXtzcfPr2/eXvz5d/t2y+/vrv5aH969+H2xZsXP/zpMfC/fv3mHiepF4U/fn1xuXv59QX5BodO5HrhiXz165e/XHz/9cWf/vj169eE/Bf+ECfRb9jJyGMhCjB5JHd2QeTmPt6lOMvjHYqRc2cfsrdRePROu5+T/HhEfmS/84IAJ7uT4zAjRCfGSfZ065C/iQzXfVGZIg+R//1wjHwXJ7U9lGfRCYe9B/njno/rh08oy2z3sCtsHnLPzzzqapbkmH1FlHCCMuxWX1oquuf5uj9YhWfdr73Q8XMXf0LZmXzME48opFnuetEbqwwkqwqDWvQH/mP1zTemYjh3TMWtw3QHo7bz9CGjzw88PRxthZGcxA4JlB0XEcYZ+dL3wjv2DXE0HU4e4sgUQqA4tlGakgAqUcpUpGO+b8GPTqbkU98++DnOoig7UxshiVsSlEuZM2TD8SNSbgUoRCec2FHqeL6PsihZzGSWYGzQmBelxAIKbJyniKQ9L0yNJUBiLkGeb+cZ+SPOPIN24uiBhB0PQ0N2wvvgynbxEeW+sTCLU2Q7yVOcRQZDy8X3noNJ3Huk+nJcx6CpAAdR8mQ6ZtwAucm9yaLnhGKT6ZfUP1nimzeQOmdM6/DEjhMvSrzsabm4T/BpqfoBuaS1k3mpuRTHgtQ+k9KUGENxhgzXfY2CtFXUsTy8iFlksgqMEpOV3hEHhRPmTKQ+xqSKC4ymuOCA3cxPF7BQ1hD6hnT6N7wf0NOUf9niDfuVukhfcBCT9iNeuQPcLBzBe8EtcY2usFD885dr+20UxFGIwywFl2dlT6luOygjMXQyYQTfUwNnFLqk7jVvwEAUVx2HwoaRqOjZMOkHqzlp9weFjmF3mKlGh6uwaNy5nkV4H71OnWSXxdISprIEhekxSgKDRjutLXP5y7NZz898IFIzpaJpc6xtkNDvdr77X3GItHzgA85IHyFDa4+CkyguLXk4/a8YH1VVf8s+gkeHF5BSQi4ySCntBtj2gtPLXRyehG3pKhTpq2+st2+sX0mPNrWCPHQj62OI3yXePbbe4fQui2Lr/fW70hMrTRz2HwOyerakcm/91uWChJezCPcLEu5nEV4tSHg1i/DVgoSvxIRDJUs3n6Ue6VV5Dh29St07e/9y/3r33W4vO2NEe2S03TAxZ9R56x3rEo++M/DmrUdgo/A9OqQSrw+I/PnnD/shD+VJojyR8kGk1W5KPKUZDuzDKdjvy+bQYLLhlQCJK4uHvVUEp9UIG4u5aBWMVteAODWrMWekOZzHJqG7FtSoR+cPpSP5pqiHIWKZ+fEydvb7hxMq24dAIVZSWj0TABHNNG1U9XhMIHN5MNxDnqDAJHBlABI5cwwjFwbAkJ0gNwlcysPhsqlA5BgN5ZYRMHQ6sWiSmuvDARO74TEyylybgMMOENFNncQjkZgYpe9ZgnMi9n2j6KU+GDA2W45g4HKkGAo0SlxZAIM+kq6D0exYGQBDPsVOYrTUqwwAIntGA5nrgwLbcWQ2ObeMgKGfj4ZTdGUAEPnRMPEjLLC3N5oBS3k4XGS2mcT14YAd5JyxUeTKAhi0T9ouJpG5Pijw4wEZbc81bYCD04WSXmi2Cy6yBecIZst5jPLXJuCwTVcxPngV4xuuYnzoKiZIjRbZpTwYbuwaHVcq5eFwE6OFRikPiWun3ikkiIaxm2bA8JPM7OAS1wcDTs32vFPgnnf6lDrHk1HiygIYtPGaD77ey41XfDl8zWd8VAZ+UObBjYymZq4PAIyDch2zGd6WPMT0ZHPG0whx14LR2UnpxyUelHmkv4s0CKKhpVGjb3qhozBP310xiLIo8OZVqQWyRexbLSHZeBIszPbmFS9tklJlPoYTudh2fJSm3pH07tmWW32sAdXZmJ4ZzkHZ+eGJw3xek74dgFxmPkixgxkisVdCOqmMKoIkLC6kBRN7/sxWVA+nktIBSuZVhF2YRKnCE2yVyhIvnNeGaKPUQhowvpdCpN9KRydcUJbP60N2w4ULTcPI19K9RXiJVi1Z5Pc5i7BKZ9nawqaQXtagf2T4MQBA6sppZxV9pFpIA4b0M5HvpxA4DSndvAtAw3VAssuctipJwnMXl7ZOj5i/vFQlNw9mo9ZBFnQL0qzIKQPDaslVeUtoQ7EjI2j49WTtM5q3ImUMf8yQpg8DynY6b6WrYiQ0TIH6YZjdQNpZItkYSTHLJBb1dKI67KDTm1co2eDimDeshTZgc5NZaABezzCwQB88Hc5vUpenLmyiMucnQNDg0ioU2k7xUqErr5vOSz222MwYLVcHgo1x4sVnnJDS3Bhy28ZzKnNbKUSnHOiET1lydeUhE6Ax2nlrKYcPAJu5VE6KddZCOZm8Yoy4bQMc3M6e4pnroRTxa0tLZXiWjeR3N8rkeRsfk6v942nmVr2BICtAuwVA29ZSgVYQgIVaI/5pK9tI8JXI4lTXs7q9phVtVm+iXVWfvajZ52rodar+rolnWPlXLkCUmiyIOnVUU39DqdULM5wkeZzp9wXmxEb3lJGJrfKS0eoEqZfaIQl4+95LslyzKu+FEYtbREd3hYYW2YrdO5CpC2nA5SEzS+V3gFLRMx5QfCBNK6SkY1lrMmnKiXFzWyrFytPI1q1wOYVeXJQiVRQ0RLVTT/tIbiOcDW0w3ARnKDnhzE4zV3PUZRC7bwMMnyj63oEfcWqEvmcCDD43llByxWSyhdZilRu16gweIrxObYhqj2qbIPQgEXslhYmgnL1JXDobG6HumYDNxkaYc5hw9syxCqQ31HZpn12/bgumzaJV7LeleOHfN6CbwjtH/7tP5CfSHUswBSkWwJp2Y8iodo7oXWnBFouCuzNiCDh2eCPLfJQ0LQHHg1bRJBUBECV/JzziKPKNJaAJYwZcWcYHIzngtEiRVNt5Ts1rcxmtbLUYz2dluJsmb9iBrmVIyYlDfsdMlkR6Y6dCZ+RsLpVw4ySigSLf9BrQUW+ATUUJJyP9gvwwbzX0QDxw5W4F1Le4xrmi6kWJbEhCpuUqDDuJumnr2ex7HIiJIM5X7pHEue68JZGoKslK7VnVivG8cwiaAcBrkVjpzIEFUljr2otl09rcbbwycda9JlK74d0SZOmZby0ZNgaxVbyrjoNXC/lRWlqjAmJ3rNl+FMUmkgNw+NWwvTA0lQhcfMj1ZjKU3KjtmXAGYDuCmjdzd7AMuON15OPEu6cXwelUGRMOjZjcRotnIF9D1MbtDAYXyGUN3ZPX7aCKcpJZ6tqIdt/UbGAL9DfUMqLNNeTJN0jMtL8Jgf4Gy1KoaoY3RbUHYLhY2f8yAtrQ1h9v6YrqJOs2sFgcJIRJr9bBaWojR3tORRTIffln1UOrEjREXPK+WlMUPJeYADWc5qCR+/KLLWRkBxPQE7LoiSso8w6e72VPmxmBFNLB5HmxduO4BqHdZz0Kyb0CKyCGApGfytI2B9NnKkUNZEk5b+Zn1nlZdon2Hb/Ifd0mXs2hmcO5TH3aSVNYt0Zo3HtPO9DstFdTvC0LwOAkIdOrpoyi1zaA4YtrsoyyVyaA0c2m8LYJ7T5CW1izmO1Qi9SfU2O7UawAhUt1slpTGDAOYTm7yhsasshd7CP5ZqyR6qxg0MrohQTP5LWgbolUKNkoCe6/C+wTqV5ugSk72s8pW5fBrJNVyhAps3MtuEYOmXM429sPtze3c45mexslMke6Dbw97xpX4Z5LrbNImfsW9aU6R7qvqpUHC7nysndYxoaoFmL2O1sDhR/ndRUFfG1FgPA7zbzHYTDsTnMubuiisaMwg6srMLSmoBYaXXVCy+XvodBags+lcMOBm9zPKdzcAMm9OfC+dqOiAJjVomBOW4UAq6lrrS3Xzd0Q3PMLYSAGxIog0LrJphWsrLqvCK2+/PL78ctYBnGt1tpQQ19xrRR8gxHTk+41ArhxjnUltaHwpcdvVZvvVyz6WhwaJWBLhxWEPeUtl4cjYTI/CbbDhKbEnvKGUmR4H1ytmN+peXr5Isp9nTCnMiyou3paDTwqBgUFAmOfcIiTmXfDiEKqoacPN/9aVxHazCtcRWBzh1pFWBAnJ3Mh++ij9AyJVivqA84+NlPEBnJIJlOKDr9hB66sqOX00WJ0gkv/XEwfK0vQzBvMRFyVmj5YnnlaHYU2WKX2bI6talZW5fJ+m4XDvPmsRqDQlti4un7FCIQIAlPWFlChVqlBFvNQcC1FoGIeig3kMO5muQwFVssBFfNQYFwMqjSF4qrUFjsAmB2OA1Cgahzk0wiIQsXqKD6fQVnfO8wZlNW4k4veCzp7GQkDZqmvKTPzZie65CzI9TlKkfkUGIICa1PMPxWwDaJ8AmCfZfb1Ci0S1WsU+hwecgESKleZz+G7AdLn4CrzOYIUIDhKkfkUcTK3AmtQlCLzKWYvQWxhqC4z7HMUK2T1SWqd+SzzV9m1UBRW0umcfa1fh81rPVBP2dRDQ0ajDjt7sT4IV9GrS/UxArUTCkQU5UJyEJiG1kwmumIPJHTaQvNDSOMq5VboaN+kzJL/3IGdVh5SG8/pp5n59zm304vudc60PkDBMQ8BSpaG0HwanbVSLZoZ66NE8TTzZulOLGldLF0qaM6xdHjmzLCI+xHaOFi3fNE417cNonyG7xALWIXQk9Ps4WgDqd7TNdDD0ebgKpo9HG0OrqLXw9HGKEW0KMASbVtLr9elDVOKaPa69CvHTG3NqbDX5RznDh82SGod7R4gBEupo8sCVzv29XR7p9pICltvDI3bJoggzhm3TZDn23JjvgMKsZ+fFE4lGVA5kmCkUwdAO6y53KyRBxaYFg8Zq3DQ4pJWRx5mO3WlOCcxKgAvtfy1m0jQhROFZZt/7qrh7lwFv/BvltxQRLBQpEFlx8h28uR+5sWZ4jhph4NVuWANW56VvuZEmjBEKEoNXFyyCJipOuExZA0gjwmljUXskDUgR2jiKK5aXcIRkTVARxbzARa/l2OXS11Spk24uFy6kzK9Rk3WoGqdcad0v6t0mPdMAJa9Y2YsCQzwBNa3Ape8tJxdP6llHnzayjwziSnzLJEh8ORCZI2kDxH/Zo4XGkgqs86qFocuRKDWRzhzRd2jEph0cJw3pjFKx1VBCIspMBsnSUQP3nZhOg8dYLEREH5WwRpArnRBKI8YZXliBLQprcUKnJVA8pGBTASWg8xnH1N5x0jGAcw1prLM7PwCcEFPFjmR6lhhT+fgq55xMloqETmQBknpnUX0rI42QBvKGOp8TqDjOTHG37/cX75+BRmptSpogNWyltgSVEyb59eGh4n+h+CQgxxHweODCYIGGlO0evpQUW0KWIcWJm5/f0D3oEU1EwQNKqZo9fSh4tYUsA4t0NU6nosfkH8HGb1cEzTAuKglsgIVz2bJNbGXHtM4e6rXLYnnCGGnGx/hpxupp3YaY8c7zlwh0W2hE8FicrGaYny0Bq3NSbzDSXgZZ+A8mVeMLZsVUJ5FJ6y9yIKEJgu3BPsYpSA1Kpcstjrah1Ow37+Mnf3+4YTYOX5IPwGU3lsdfEvGNkDBzM0EkZv72K7m7KkJzrKEm1P2t1GYG1rg5CbevdTB+MKjs9Y9gXj23sXCaXYMFD/WV3kH49qnY3HmORVB0//yEF/l9c0rp9sYJ158xgmSGa2C3JFGwqo4PX9el7Dm5iHfUJu98YmJaGwHEFNp7wsodWanUzGW5lL8UmXuImsxk95q61rExmEeAIPVmnp4GguxxWzaK7JrnbmrsgfB9JZnt3S0lmiPAaqt1da4QGf+GRTtkmROXd0IgLKqbgsCFE1wWJrnIDQKEzgmve337RwBR6WyB95QEyLFDsGWug1OdLEc3ekThTjUOTaWdD4O2M381E7zOI4S1ZVuMIf2DES8V8EhxyHdoQRpXEVWBLXVDDer7z4/5WfMOMh6p1o+CkIvTnBKgBZ3rWMbyLM4RevEmMjwKkPfYNczls7OvORGMgT59ay1LYCE4CRPcRaR2LARXoC/Zw7ABW7HceZVPEoOdIxB4gdo7k1uc/hLa4AOYMclGZv8Oe/IxFlutG2C5ofTEsmpZw5mlS4tYQvpRYqktjnA6mk5H7r2VllBA3bBLa8jjNbo/Orm2hZAzJNqwUYzj5RXIm8Ygig2nGAZ7IYhCGxSCyzE3bAEUUCc0eUy4E1LMOD7198tht6wBQP/+nK/GHzDFgD8aaksegLNou3qdYkCvW0OvjZfwIeuPbh4uEd+PnMV95x4qM1tY3aZB01/gIrSSk8Sj4tBdcuLVJAl4Qm2BVm72mo8ckOAOaawMn/jqaoLHXvwnpQH8i3oS20RyJsU87PzbBfHOHRx6HjQYycCn0bswhVvXpbasy+JkPemZwu0517sHQ7oaKlJN4YMAqWzWr5MyYsUZINWwb3KEhSmMUoIC7d1nnvdxjwPRwiW8NZh013r+lszLOExwshd119OsIS34OO5qs7CDfFOmrrDT6RWIv8uJnRWdbvPslQILFTxzGBZIgTYDb90M+q6zrcwntcwbnftYorg9jqwe0xD5JMgy9MMu3aaRcnce+9kIov2YslHa8ww2M4HmipW83DKOJiXbNe8cXcqK+uefCfux5l0ftCi4Z6jaZ9G7ML38LUOOpgZU/MPDRF6JOzYmXRnyKDRnqTp+Bm0arQtQm9YoM0+8+lPwr5RT+efeKLv5dyDURYelcb8GLnNDEnbNRNkK7kS5eNrbTMw44O15vyjndX5gc95bgjDj7+MuQE80tKUJraTKH5aypOGOXBXoEcAx/wAHetrCpsbDBlzx9CwR9fEGYUu8QV0JHrKraZNcKeMDFuMeaQxQCHhDsoynGaLpryOSbjeEjcQIM8/RI8m/Rmy97wGkEZaG4ANxTrsypUKbTPgSdrFRy+EbeuOuNA0B+4KeKN9zJGZrXQJN2bflDHDi3nXZsgUKyaGKrqeDBoEj5NqBJLUmIslsZ5R+FjiJhaLpaZB+E7HGTt3Olfdz4ikrk14p5Z1x6AjRSdtKUcqa8a6hAt50jBnpku4kB/cluku4ULu9K2a7RIu6FbTpsEu4UIetQwa7RIu5FDHpLku4VKNgoa9bY95V2P22xnzLnjsdN7FZUOzFdxPPiDRsvKsu+2eiZ0SVXC1Z3bAp6loBCzAXZrZeF60+RmwW8uTXpfMZochgp8B0LFSL9AfsQ6UHLmkuVV5A74NGIZaatG2CjwBLBddgIWGKLAWcWnA8MYLFLrsBTt2lEqdZzgqBlhdVUzAJX+l21j007AEtnip1LQPKCEJIVvSj7bNbaQ+3XO0xn/sna0cj58yPv+utd6bShdci0DL64v0TmStdVSSGXmLX/zDLpWuVay2oO4NX+B4Pc2lzs6lVv1I9ZQzQWwREZWmgygsiITVkNKKJK6jGT1NJKB0A0TVVnsuRw0f/BxnUZSd5xRNihdI9k/ZRllmkwx27znYdjH7ywtpvcQGYWwfn5Ajc4TheCRPmFGN/CrIeDKQc8OSI9lcwlGrGKWuWYNNhXrnXR9OKFa7E7a+v4yng3IosZKafRypB4jjwfHYSRalNnJRPGNAdoJPpK3Dm/GbHVx8VJtRHgHtieoRIveetCq8dN4s5CinUFo7PEPM1oeD0wql9WjdJ/LZc1hR6x7AiQfl9aj9vYNicNiuqh5jjB4Sk0l3WF+TGyde5JI4M8k+akOPP30KHXDgjqhmeeY4OCbJzUsz+AJNqK3Hix/LBUCHKHS98GSgnBg1oUdfFj2kKoLDbWvq8Z2jNDPQWBAKzz/4neaBDM1b1jTcAuyLahH6PjReS1GLDa7ZXGnp8rARTJI2Dp7vZWrriCbo+sqaJSZcIx8m9Ipky87Qgs0JXFKLTn0F8hiY8hJjIVO5OxmMqqFn8r6Tw0l31AbgdjPa9yswSJVzyE/F/XRKM539oOSS1WzZkI1ndA1a1wnN1FYFUd0F76ovFTi+d9CdDDzknu/CnFpycubNKw7IOVGS4ceL4OpKQ3XIa9UMrKivc8/nsJHu5ZjcC6U7MEcSNL0Lk6UHi0SlVYd//UTjZsym8fnnnLQcnH+CCKiMzkkmW7rSdqX7vAaG0PTqpao6GpCGHp0DoxVKmxidAyMelAccnQOD7aoaGZ0Dox3WNzY6B8c+agNudA4MuCMKPjoHV6AJtU2NzoFhj5qAHf0CYxYIQ/X4IRj7kmZ7sczW/E6sr70UEW6rwSFzssSHiIoyWCzfr2OlpQ2zTachamcovfNxprYEW5G8ZeRZ75KAHNRtBJnm+K5UbDvI9w/Enu44nAi7bwAUnaL66Elxk6wCesuAGXSI9QzT/MoLHKSciIlRmnsN0Tfk1ygctjsM9Xja7+EHoGAHiPpDQ3Vm0h0bqtJLPTJEg6Q5FNQypjsW9I/hG+UH9TITQAaCHrsVrG3ErO0OmbFVm7/SwqbzdtXf0s3bwqHeMqSrnN8c8m0aBhrz7XtXAizuXMPucy7DhlI7cY+tFX2G6Z2jF0u/Hd+jW/aMJg9usZtAhBgmc0LDIF3yrl+fa/tdYxj3e0Vf/05LgcZQ4/MsB4oBvMaAKUkDZuvBhjFRdSGE+TtMOdTf9CnNcPA8E07BbrxEKcx0E0pt/O8wZTRmONP8kKCMNBGfZxph+VnkjvlSRmRVWNyM4v1dpq5EP9LXTE0JNpxwEjyQUArLf4dp4qx8BsaWkgShp41oD6d7oymD2BEmjI79v8f04TzTXm4RP47Zjg/RF6cL5++11/Oc260sahZovIobrh3rzzltaN1P1xs6psMhUtv0FZWJroHlzsYT6qnY3mOordMKbYsGUXshctP4f7kkur3pJ5VBZtF09+6RKWgkIzqq15QCWUUFeMDH5HFUvTeys5e4doySTOYol34vqjhs0Rs/cGtUguS0QiWNtKcHgZZ9HdCry1d4zqJiduhQI0ytKoCspp9sGVXfCsC6DiJ6dWkevGUD7IJMN0D1XQmG4MWWwFwg9sotjEb5W2YglgM92oontaow1+owqAf/bsZde4rEbSMw4O7ZRr6xfNkyAAOMHcd28uTeaNpoG4EDv8NPJxwaDvG+ISgH3BQZZ2/YgMFWvW5RkRjyhsVHO0CZSVguDwSLAyeITeJWBuCA1e4QnQEMd2voI+kJeoGXeWYLu7YRGPBE7fJMReIE7prMx+LKbnOsGRwsbZ5f4hm7AVT7AC0jQOBXC3BfwWM3ukMGwdtWoDtd5sBbNsx0ugzBiy0BuBAj11W8J0qFuyEP3nMxhNwzAgKe4JPSDhE1Yq6+0u4xP3fnDWF381MUxOSLhO1gDelSCiNhVhJbA+ZAhzIUz7FTdqFryMA4zCL4oBfjFqMlBrlrC9Clml2e3WIWXmgPdITGLH9tBAg6QKaJCwvgg0pmqduGjAwsmXegbQx6cMk0f8MOEHqSRInxhFMZARwVM4sMedEsUXuwnaPp1FEbARzOM4vMTYAO6RlGroyADuuZh4a7/bk16mYWvG0IbnjPLHUC2cfNzPNms4Bndhhb/r2/eXv9y+31xS29mg1f3LzdZY8ZvK8DZta4f4YHQ6ffHBywm/mp1rqPBCWaFwg5pNOboTCzMy/AWuPKpT9WiWX1lLVus8rOCUZsKAmSsaWqxcevHATFa4qC0NnUpBHESlmPkzR24REbonqXvPneKVS9DnUSr6WqxXcI7SDXG4LuwtWSemQoxd+9ghkl7yH2tfVYSXTkQbFsFZSzrQvBaCY8+9oQrEHkmsAsZYEI7QQ9GKLk0oCkJI7uUUqaygaRWzb02P3IqUYdzaTcIQta3M4ZU9WimQkwRdlrJ4n19ZiLMHhIkF7nuMfa1tVj1B/o7jc5541lj7WJbS+IYZOpWB6S2ETmGjahR57pTeT2MLMZc7YdpuJCDSOh2JfWIsVOXInZyIdtmIrEAWgNVFldYT3KMEui+MmOIx827rvCWpR+EKkdOTmJVylqcQVEPtWbTOuC1ZK6ZOD1YUNTjy1OISZ+e3gtWW1CNqkDDlipavPRsRzNdUEiwFpWmzBLkANb9LVU9cZekEvbz6B0DU09tjsz1XFHV5cRvHxpaGqyPSReBpvyGpogY36GYlikrsWbsAn5zD5jP8aaE+ldWoG2NquRYO0Ka1GmqV9eYmciTIXq2rzlIZPQoLWsPiHrq6c5yaOpmUQwakWbP/BSBxyXi2rTEeHLKzO9GbE8EPEdfoLPXm1pLdLH1y//2Uxq7Slr11p8zK7Is9BTVj11gBFB2AnemXt7R8Yq4fEqXaDYNhTNgIQ2Iv0VU6mRa4PlHfhkKVSH4nUTUhwXiYo2JewwotdCZZ5jyoVRg1BepX6U2QEK0QkHBosygRkwD7IoIbLGyGt5KGLswBZ3fWko0uPR1dvkPYLKtaFYtXfPj7DO2zo/zBogY6VGKQ1FGqM7Y1mLa0Oxkp6pKdRSGqzMMldcgYYoq/Ohx2Q62sDtCUO0c/eEjvBCrzISaEOympilGDZhqNVmil5gxny7cxlf2gYh20CG+Etp0DaQIVSuDdoGMsQ6b5PUMKuRAbQBfTBm4In3vjRkC9MQaSkN2sI0hMq1wVqYKHSjAH5d2LAJyLaxKWKAFRrtFqwh0BQ0LXSHNExB981Aj5yYIq/lwfdecddADiTR3p81Ety6p1Hw8OUb+PhnuDMoUOLBFA09xFIYgjENL80wlsJAjHBLLUSgMxddCGmLrTNGUGtpCE62JcEMZyUNwdnYgGCGtmMAgpke7E/aycfIDHFLHuJ0IvKX7xsqrZriEKyOmURb6kIQnhH53/6lGcyGOBhrHPl6ZyeM03J5EF62sQdux1CfuG0Agtlc2QVaajlQXdse5ayOrZgxCmKUXex3j2ZIW/IgvDQh2cj9LU8z28cn5Dzx5QlmHBi1Z8qjY0J61lB7FKR8aloE94r2tZiBwtgCXgksGvEqzenIM86W9UxgFdy7NIUZORr3prQCTk8X0i2Az83A8RvO9KA5vHF0iiHktgUI6iyx3eRgqK3TEAdgZQvCjYBWyiCUZsaNXLBxI/dspodT6gIQYgdo5q6LyIVhGA0VTZUyCOVvYNM0fc7f5k3TDJDCzCv3KaGOASz3ApuhrLUhSME2ffY45238FFKeDI20nMBGWs53rt5J4EOIXBiCkXR+zVXhLXUAWj8wUzuWugCEpaLJMaC+CQhumPV+PdYZS/0G+F4bAnwNRYiDKHmyD/nxiBMb+X5kZrhqwA6AByHpAqeRc4eBVrt0yTv6EMQe6TXewZzf1aOttQFII89MBit1AQhjbKY+LXUhCGFOKugBzjisYIDPSS/3hhi5NBCnmdK0Ugai/IMxyj9AUfLzWo2ANsQBWc2NMfUsQFJTCrPU3AIEdeQ/XV69NJTNGuIQrIl3jzJsI8fBqZmqv28Cgpuf8muEuCEOwJp4pB50L78zM+3eUoegNTQ2NWvJqJAwPSMzK8O4MAzj/vV3pihLaRjOK1OUV3CMrw21rWppCE5D83xwM3vsCBfknM20AFrqULSNA2fMQXeMQLFH0Z1nMKgreSDezKP9c2O8tTwAb32VgwncljoErRcYQ62kATjvSS7wgPZ7dkEb2gCkxlYlAK5DYEcQOYmZSqEpDsdqJvc3xcFYUzPTVE1xxU03IPfrkr4HyN268Av5CJkFu16vPBSgWACEcrqPN0QHH8MOl9bcQ6bAfSmXCLk4xqGLQ8cDbrz0XRqwaMqzO/xE0LwE4M5gad/6Nk15lz6FUfgEPN846FfT2nZ3eFB8+N0dRXhQ3cwL6VEQcZSCN/UbIS+2BO8J0P2JEp6AX6DY0ae5jlRQdAgPumUo8KZvDc6jYgW9KQ9qdUhi8IUELWLInSStc0QAj40RgPeMGOAPM/yYpQuUSOMWzXm2TL6etmrOQ/Nl8LhFOM+IeAI7KN9wohKH4zWwg6MBDLtTozw0xMRUboMZeDa3OtyiTIKmsFsGALm9381lykockDdLcsdYy6FWhyM22i0z0P+6R35uDrhWNzqiA3mL9OgjAz8Ofd1Zq4i8cOokSvrGG+vtG+vXFCepFeShG1kfQ/yOFgbWO5zeZVFsvb9+Z7/zggAnVpo47D8u3g3n7rkZ8eRpuLMRSm0JgonUpkUgSGvdeXaM3ADvAtcQRUN/giT17RPKMlLaJ/eeQ4p8zP6i/fwkKBpqRWSdcIgTlDFOUmhhIbm2MfsBJWF99TeE0SmLZZOijIt5FvEjK3fcTyg7/9EL0AmXUWB7wenlLg5PP1itZ1Tev9R8f6/5/pXm+68U30/pWWie42VPNins7f3L/evdd7u9FSdRFjmRbx1IiZ5FUXYmuc2zSKI6ZLtH8k8FG9KJAoC7V1vxEwBjeopW8SGNHOv9zdvrX26vL26xkyf44ubtLnvMxu2X9R39Sb/QEKRrkT6viEl0/IadzBqMrrLZS0zS4LVuPfJUFL5Hh9T6888f9nvrhp/eBWqXlMDl7bBFyJPPNkpJWGQLGPKjk6lgLE0RLWgL/Xy1iJHDaUmXDqc0Q86d5fsm7PFIKosUy2GnNxXH+CXLGyTZ2ZTBtx9ub26tt1GCDeXfnmtl8bxgYFYVgpeZNIcDN7m33ADRvxa0Y6V70lM+hYgeeWjSpLn8XdshVahJAwkiz5M/Pd+mlmI/P3mhdcTFonEDNUpdYpWhJ9dUMeV/MQRknWISCsaTKLXCru1K8thozotxwpb9oUUqg8qlJcuwvlGDlcKopxZKAuOGozQjPY7AQMjKNt89I7WhrHWjkUv6I+Rni607DeIoxGFGP/ANyWkex1GSlYfjbASDCOMUQ7f51WkWSJCd0c+lzJVHQJvO2uW+5wWLzo7FBcrNjkXyPu3FL+NsnJuv2MP74GohK6YLoSLU4ugBJ8ukyYFyhu5TKxtnyzV/iybpUm3tuhNvrI85ZNLDGH//cn/5+tXSlh+CQ26sWzZk9PcHdL9UGDtn0nbBx+RqX/z5eNo/Lu1v6rn4Afl3y/YaY3RBSqdyL8RicSyyXYX8flkK9pk2KOxWAcpGWlYjybyFC+9Fx7JokxR5RgdhuqYWaDBVpnw7fUozHJRrML2D59MAX8RbjGN63sEq9b9XHp+8TtujLEc5wwqdT480gLBjR+kyQzhEyEdDySpAThK9w0daipHS9Ws19cymuV5+ervf/9vPP6m8ePvefvvx3TX548Onj79c//LFvv332y/XH9hsNFvRQp1hCV9P9u37j2//j/3hp19++vn6c0u9NaGgbKTS/+nLT+8//mx/+nx9Sz7rwb67/tebt9f2p+vPN5/+5frzT+9bwOXQaD20p2nsw0/vPv9r2wIbQdeT/fnTzceWKB3z1JP8l59YiH/4+EtL+Ix8e7C9rijfo6bi+uQ3v3y5/vz5109fhCmwN5ioYoxNU9m/kARj/+vN5y+/0sSi87b9L9c/vbv+bP/l5v11i/L/+b95lP0vJ0i91A5JCrTvvSTLkb87F7+omP3w5+t3X97fkhD65S83Pwts+dn/agwx8UX8f9SLhU8f/404JoqBViNtjiOfbn+y337+909fPo761LoWdp5Pn3+6eW+/v/mz/eHX919uPn3++OXj24/v7dtfP336+PlLy+LLOdK/fiF/fPqJu1GkBlHkNBqWCCqGbq+F0VM3JDUrgY+f23FC7+adE0hX9k+fblpKl5qOv7++/vTl5kPX8arppSt/UybPjjxvXanJ35BQeHfz8afrW/vz9f/76w2p80i83f6fm19+1ueskvQAcKdNplkk3F6/tT/edmrYqsUlEC8Hg/9SLL3TXIk0ZxEJ7duxPYrWyXEskoIz/HgRXF3VTyTYxyjF9En+3Q5typVqhUrtCO2jN8npUkTSEsXJttCFAe9j+xylWeVYMwKikB6x4R6ekxvkH4cTXXLYdIR/WaxsdXyPXtr59+UU7QQ9iwTHkKunyYerdqanP9O67Rm4wuOHHpxHWsC+R/7diSH6u9343Sa922eVnwTFQvnbc/JiNAM9M0eKIYWuJ8W3z8gV0uwOscNWR6U5AcxIVSPMPaIHn1s2ogXagHPPqqQ7I1/oBh1qIEweTvfPyRunVyAU3jjPqUwQlwfMkdULhYH5HXq+zwmHxeoU8l2DnX0uD145nIL9/mXs7PcPJ2QT/5+fJ0Hk5iQ2qqk86gV/SMKb6joV0ZC28FHpB0WD0sIHw4gkI8HDJG36H+Oyl0o/3LD9WNW3u9zZ0U/OGXkh66NG7Puxx3ZOnHdHOcoEvxTBsUNwjO9fX6TxYub9CJEW48HrDOUmom2CMgR0QoauUxoH4E/t2FwOJjnQxS2CYp/dLAK2M2/CfvFM+detk3hx1jL/T3w2qM5w9Emaz3f+QkFzzMOyGVI0R1KoAFLkcFGGwBkUIilEYWQ7tPhbKwSiwMvsY0LKJzsuFqOvBBLS4zlo527F5EAYkizzVkgIfB/uBxSzKmMd/x2bXp3pshKyWXNcfr+Q/cfHAYL/+T8v/7AMQ7kjO90h318pGioEdl7N2hAxdlGYeU67Kh/YGW40Qkhlym7WS9dCoU8E3u9sI1J7RsL7fakai17Cavv4HrdTp4uPKPdFq8rEEAG6w6zKR0mwo/2BDCUnnHUpBh7rNS4vAvLNjzOamJoc2TkPDh2S8rtlALpt3IuAfPNj2dK9cC+/WwxE2NolOPT7C/L9j0ot356ZupCeJKofHapRLtLM/VGlWhmxEccKQPTAlKFKpoBSqmmAsUTtj4tjGF0U364GNdAwY2jN35ZNW7zNZA91tEihFChUDYDhtiCaSojxqtTutm0u/o19s3xAmSeaFT79htfFv5XfrRhGRqlUwmmwHXTxEaQUUA0h0zwqYTM8pHBxpL9d1L8tH1CLwqmE2viA0MWR/75q6K0CqZQvxwdzLo70gQv2wEX1wArZdR1MpVw80M26EG21NJ9tDdCIB6cGHhseTdYbRNakYsOnvcHTC9Lzwk76I/11x/65FE/V7Cs+2wGK22T/X6n39ZuLDyj+8Z/+28dfv3z69Yv97ubzf7f+6b99+vzxf1+//fLLTx+u//uOvSzJXWz02Hku3pWj+13kcrtAFLcryNa8IHgweakzcMELE37vpVklXjdp/G8vLh4SEjykjMDYZqHV+DJgd4H3vnbEXyeYf99zToGk3ndFV5P2vyWBTi/8tJFTNEGUTdGelC9axioHeXLG6hyrjkXF+GWLk/4RwdMRrB7GpIDfpZ6PDinLtql3tS8KfjfbFcvcXbZYgU1o7k5hvquKmQMqj01tREVDrn52VzxASuSjj07pP6JqibxI3qY9tovk4ZFkylOAwwwkU85IMKTpoJBkyqd5ovlHknn2SWawVQlTkM/3WqaFtkiJWjWzpcrU1kQQySI02HZRdsYJXZC8sQCc1BCsb5omDkg+ISF54ePwlJ1/FG0uW6hkU4q65vP/iDzIyOu3FWELGSNFRa9gpCcmBwcw6EfyoZK8ePCy8wXr9G+52agq53iJk/soqe5hfJq/UmE7XoUkFbu9IQW1NQY6LTUAV+pWn2IU/cAPiqi++eaHPz0GPn2lOEmHvHS5e8lEiFpE97SRr3798peL77+++FMtxAchqpWvubMr1u/uUpzl8e4t24/4qXjsEwnzPzMnfk7yIwnrqFxLvGOrdYkK0Ytxkj3dOuRvIlcNcnQjJCZSLDxuMxz/kTjU+ryCo/ouWuYhy8UjtzjL2EqbLTLmThmU+omkew9xOYY5VMx3H9+lPlvWkOHR24s793LsnMThG+SdpCAur4KssuJX0YUcA9W85L04/aT+4tsX5Tij/fnjxy8v3rz469cXn6/f//Tl5l+v7eZPX1+8Idy7ry/+Rt65vfnw6f3N25sv/27ffvn13c1H+8PHd7++v74lAv/xV3rHSxDdY5e8wwrLb4vbWYl318WFDqRAffMf/1l/fRvliVN8W48is/2X7oGO1X/b//b89QUVKJIFg+PJ5s2HD+zLb0jaC9M35bc/EndfnLMsfmNZDw8PvBwlRaqVphZPTpht/ydP1tHxtQx7+qXnss/d5Ihi5NzZh+xtEaOiNEnfjt2gJfdHFgnhN+V5Pex0sm9i4h9OCru7/0H/tMrnqtjjDv6RBUwJSoKA6v7tW93gL4+Qra+OaFyY+W3rZz86CX87ZPQfRUwVX+VJcZ1O8Uvz2eJcGaEMPdLSLksj4QOCozOaP9PLUcptr+If+UYgG7mkgMq8tLjTcPxZmQf4vrqhZ7Ny/6qL4gyNP+lkiT/xa+qcMU0OCb2HMaIHRg290DrXyI5Sx/N9lEWDXrefz+gIztCTUTL4W+NGAdt1XGfoOX6w/NDv/JxrG+cpIsnSC1NxuhAcEzPwc4k29FTrZFrJpxJ8GonQ9tF/Aw8Jj1EZfqZ3mqDEO9lgrqjPF2k8sZmSNnf+LspYXpl9/nJtv+Unu6VlXAzMojZ+aZY3neqx9dO5+1N1ipztoIyE3qn/CL6nP59R6Jbz5GM/996u8mjxRNoX6D0xrMHSciOzo9AZVRQ/P6E/8mA7Zw0FidcpbOzyp55e78EsQWFKdz+OvELruPry9gl9ViH2HtpQ5v2CA7rjE/+dZF8awGVHw6O/bSakSxMfcIboSq5nEtxK9xUSCeFlg8JfLgd/2Q/+cjX4y6vql9nX9Y2+rXVpXpEKham2uCD02+oS0G+fX4Dze1a/bd0jOhKWGtcKWRL3g54njYuv42v8c74G4dOSIfU//7sM07lvz7Nd8k8LjFzAZhWnT1bzObpCdDhVV6Mc7dLRYd2p4OpKQyOIcxslwf33GhrZ77Q9keHHqeQlfeGl1VpkBqtqo6oVB6V4yBMUwGtm0olMUtMJcmhFVs0g+ewgqUtHAKAlyWOkTIZWDRBRTtkq10i6YJEVj30fWBKDJ4GiKwUsekwTBzqqTrGTQCcqesKzAUmbXowFrHs+wgfp+fgILentoePIQ+Bliecg54yBRX1SlhiQfDwg6HKJy9Jxdy8Er059zEYWoVUNpH8fPv0HKXRiJd13aMUEOsqJIr9wF1iZtKKgAzQFr0PTp9Q5SvdvJEVNZKLcRC4y0YB4cOX7i5OSOCh79WCK5SpixqotWozfWGlGgjGPS9Hxrrq8aBNUUrO+1Jp13mUGHobezaLAk86+7XcP3kyjdOe97fiE2zuSil5iBGdQiJ2gPvddpaGK7tuJdFptv4nDXLq2aL+Z0jWxM1/NUJZLF/zddxMvlM7qrXc9gKhmx1ZWiVwtg5TvlrPi9BycYJ5CEfTzXi2Cb967pNZCvp/Kvt25KZ2NnCr0n5qvlwTsdUnrxQ2ojQSAaezLGi/eLtahsLeLf85+Pd3z9g5f3KLY/Gkp0uAogZRCo3edfPsbNZa2GEVqiymRNW6qLZb4tBYiKF6qy/6h8aqt1N0TCZQLlHQk2DI/+cpQJHFG0sNJA6/bR1JYnnVE6GIhnfejA5vx1FCI0UkrLrMEybcERQJ0ekMxnzMBmqVYSlbPSfzVMiVrCNRL7WhBavNl4/MF61SlIcJSlcb7ZarSUGCpSuP9IlFIC9Djr1klFig2sFuvKk0ydN5USMGN9+jdxvNelO90d98rbz6d97pSG77zqnwjvPeienHfEFAY5G+/p9QTF7yqE9IqTcHWiyrju60XVQZcWy8qjNF139MJIYVht9Z7CQroOUPz3lUYPmu9qDak1X2VXpww/1WtzKM0bNZ6U3FGv36XdkXnFHG08qhKcaWqo3yTWpzzHp77XlHAzHlVravXeJEVD3NeZMXDnBdp8TDnPZq/57zH8uicF8uMNufVIpdIvlnfOMz7/bTRp9CEEAuoVVdiDZVaR6ygUCoPCrBhN00ZtQJ3UEOh5B3TUC2CG1rl2E4jhtWTWUNDpeAQKyjkS7GAWj4DvK7HgLmpO3VmmKR9AosJWlz2sfiV/mLTLfx0eFY2Kcmo830uIAbKy1PJZ30FvpuOnVrPxqeli4UR0SNGWZ6ASAVH6fJhRCV7inVpyigEEQEPda4LE/BcTTvsuZBO8Md+fvJCi+/Da+7Jm1nCjSlqMcbogpSOZbM8rbL/vr99Lk/udQOkY6zYlMc/FuWlXvjIGID2gIZLkVoMGjChLdggaTCohOkJLtzGtnFObfPUS3NalqF8zrzevlQwr0TaM7nr3Ty4+PbgS4//jWlxPgA5D2P8/cv95etXxY/1Z0BlzgsnnnoufkD+XfET/wSmyoGhhB8C0rUtvmf/hNHjlCCSvz+g+zKVsn/C6HFEJUl23wX5ubXzmHzLy5JqoUf1jTllm25iTDOlhSAzrDhn7NwpzmjPMcO6oiYNmPZAcX3xDAvkgSSKnwxaOCtMmM+QZ+srQuTbd/jJZEAReRIdiXdvOnNQQ2wXvcKyrhlm2HIb2jczaEOpmzVDX6WHJCnvNfVVe69zbPD0a9JGQCqlQ/QIZoKvf6trJMnmqLpyq0YyZ6WsKswZ4OWsOQtnhSUkM+Q75Z9ZQ1X5Z85MXf6Zs6EyJiQpL8zXeibqg57SPKYb7/i6w+ZhLMhxsI8TiMpPyl4UhF5Mil7yhklz9CwYo67R0hhhelkbvB9U23ECc9oBcoyJnwyCp2d0aVJ8//o7k/KvL/fm5KuvTcnX5w2atMAO5DXlg2fSCVqOV8cGsMMYoIvvtgWS0YxYqI7pMq1PSiGjBrDjktgmf+o2n8RmGjnOkHwjsZqx4EGa4GNmpV5tov29dr6TtGOzIT2IbDhkkBsom230qpJFbWkHJIn7cu8RaxVUJYs5G+SjxeaiTQhXI0ZZkqcZdu00ixKFPREqtmicLGWPbeirIqf4gdjUHkWaMMTOZ4xRQk+85Nd56lfM0iYhxpiE5uqvFBfBzzQCNNgkNEP6jOVcrV1dbODBmmo3OiCLuraN8hsvS22VvUDy8kOZyKihZooujSKM3MWNgoyDqZsFGLtSNwo6ojXPvMlsMmEeolWtahNqzE1ouV9emzWisrhE1YSpAmeoHtA0xaO9U1XrVi8DsnYqvZxoUpkfQVAJa4dETH6yo7RaE974Rp96RNw+kKwW4EzFDDuw1WrdX1CdoNH8El5RaYHUmKwHScpTQ0tROkXIKhZL4hWSmrSwWpGkJAsI7fWDAyLaurKcWlW7cREHT7rduzl0JMsQ7l33oR62pQQPBeZ92tAugqNa9KspX3xs6td7PYq9KkCG2mHuqJyXIKWosuNJSlDhxEYpvTpcDcmq9pmF4u107KgcQCClqLJtSUqwEayKstURLq2QReSJ4iTrkDxl33tJlqtHmVibUPd+0Fcuw6P3g+rhS1MWPAD48vaRKjTKz1A6insnJ+WKGzCVFwROqOb6iB5U0HlAWDwRcirVNDego7hVclIuIS3p5IQzGrPqBdGgbDudQKnmMzxvX8hVzQ23vlWNZBnN8uovEGmvr52RrlJ5s1iWRMrFccdMnET0ZqmePf49lDwvNzvyJLnkB4XeudAIn4Nsx6wBTdt9ClHg0d2w9DXFUTUFOzG9t9eUsPLgkYJ+mfTNSBflFYh4N19pJnOx6NyAjvOqYImlzwtpvs0DMM5ndLpa27yqBSnNL1WRphVJC/aQK7cqRLoeJCqb8an21XbvbJwTt/L6OHilL84ucbT9KIr7kWhSvIxPoybmDddM2OgkH3qT6j29p04xGdHMh7zqBFv671njgUM6ZUEDIUdqYgendPmr2urQtmJanQpSnH7lHTyfju/yHQ3FbzpBIGfBrDf1qbi931TTYWUq6aQQIB2eQgDkOmGqpegBpGF+L20V9dU32loejFh1aHOlpRxow1rlyUoKB4JJq5KYNiGrcnqVtChMuHodWdVIz13so6oQKj7N1CjdLDUUHRNpsFvfvgvYSUG343Ja11QK3j6cOsew8y/kGnojgnRPMr3U0rWIW1YxrHcRXF3VTzSOM+LfTZ1aNGKPJ5O2A3KHfYhk0ww5d5bvN5xg55U0qOmBuyT6SOqegV3pl0nykNm+LzlqJ6dX3ESPfP9AfpkcY1fQrP02oEk3GkPCxuRbnOkplrm1VJSp/RXl7Ayldz7FVNcV5zFSFlQrc2kZcdXObvRndiiuesoV2vOxfY7SzKIbmGKSkj3y76bB8ne78TsbUYK2z0NZYHsJU1HoeuHJhXeL/INFWtcx9uWy1oordh3fo0vFVrBMa9JZRe6k5aK70DVdnhgIbI8U9CFm7XQ7zQ90x194EuYY0YNGsg4tDgYI4MsJ0oIT2mJjBTjxcLoHN+n0UlVh0gHPQOKExKzNTU28UmP5Xbkuq9sY+q93utMaYhrtnVqEFcJgOjIDH2MqUssZxgQkD64ekvD0Ukj5OukIRqmNXBTLnb8zIteu8vWiqZBzSRBlXip95s24mlZYcYdmtlnbOryUB/CKz37R+tKVXQowqogfy41DVRMHQrXkI6GnJVO0LGFSq793UAzhW4weEuDESpcNRS6JV1jZ9Cl0ZutUfZlmAarciak678LiQkuuF1Q6av1sqqMmzqY6isPZVEe1m790tFr5S0doIH9pSQ7nLx3ZZv4a12FH7mZnL3GJe0n2VO5is72YtiGLD2nkWO9v3l7/cnt9cUtX5+OLm7e77DEDUfbKS1Gd8s5LlqJCmX2UyhbYN3QF0nTxP19bpj2mqp4+sqMSwEUP/l256U1ul+cME+7ZRv5UKT9Hd/L2nhmi2HHkToOeqX2Hn044NBMgxUEOZqTpZnQDQSJxOOIc1Qd7+iqMGboBygzQBjhwgqlL0WbqTp5sOUM3TrzAyzwjWWR6t/4MUYkzAGRVaQ17QK8uL7Fc41VVV/KeU1XZV1iy+aMhDEp8dWmEt5aFoy0+kcqoPsoSjlkgDk1et1jgsGPkutPHt6oolu0fOMRW28eYLmgAlA0pUNZGewdct9HWAdbm7RxQWYlDGBQVWXsBVrFoK4BrTp7MqqjZaCOA6k6fC6AoKHHSgJpigk/K7aLy1LGqzcI/z+jxDUolnnJvaVArDS8htR4Sb3IRrbTgAaX4u6kbJ+TVvFOYT20dk1djO5LnVQ2DmnRSkLQOjlObeqUVHRRg34dLLvSARCipMyL/27+E1YsjX7mbNKwofbWDvCZogmHnSUJpsVnZi/1u6mx1BUU2t4Xc3/I0s318Qs6T3HEqeiaOSRTQE2PMGKFH0TALhTVzRtI8xkmKM6OG0lS5FyIn/Pj65T8DK8NGaZoheuSeF4BVV06W2G5yACsrZFbQKoiBtT/cM1glwE6qhdOCSyDY+S1Gd2BJAzvKg4KDUlK33MjLSRxNKi12gmsenO9c5VmdQS16+DtkzvQnL3iWlqqOhgZtZgQunNJrMKliz+whPx7pmZA+aUFDSYf0dINIZqG2vCRdQHD3ACUXeWBREk9e6y0vNXUekYKSk15OHWanpAaW7qjYH8DEyg050HqgLZFKVOJWKXlR0rW6vHoJFy3Fjlu2YCcFy7a05QzpdeKR7OZefgfWT03gGin0bhBArf3r7wDVrgC1XsOVLIAdnpSeLoicM1i2ZYJsgCDNvQyuwc50o+jOAyXNPFrfQilm5wSjORNNg4JeAKgmt6xaWg6yd0y1bCcBS9alHljMFnqpdieD3kEAN0JK1WDGomolPvaBcvJvHKKDj7UbfX31asm49OH3843Qg71j5MldfznfTPoURuGTfqeqYYCmlMwLi0OHU4jSVCCudJHqHAPz1+eMiBcjvaCCEH3XhqDKXRWzdMMMP2apmcTRNWIskXQNGUksRDnRbrA29GAGsxuCUB2yhmSKy7CF1PR+B42XNEtyBzITQ5fwUrfaDQr63iFByZOFfO8USlzLNClUzCXPXnrVk2OTycXWVhgpYLIgmt306CvZCZo9ECZWI+7eo5TkMW3Zxjw8XBiGdpBrq5TzxxB1ZCU5a4mbWMV+SJDy8qMxKV3ftGr7WqU5s6frXVPMpiqgeGDp1clmV1VcojjtBgoIO3F9V9z0/a+SejAlRjmBZseRr+2nH0TzZxy4SODqTG03VCByYRCnmu3uppLW7GJTiA4OzW+PNZVIc9bRTkMxciUuc5iWuQPLcUQKIvrjO60VfJUMb5RrFsDtiQxdMdmLXxWUZK62U5bTDfxaDqa90BcEJCzOAQIkBGiSd+SACsSGatl1pzmWLvIyp2yHtKuIMm/qXEYYG3B+0BUzcMQa628Easfj5P3aynJwdHP2PkzJwdFBteKakvpNsIba9GWSqmpwbGxJGhyczgo3gVyCQjcKQLpJTVXSNIZzWWP2XaCWQsZGChkXqR/xC4skrmTVUQZkLu8SB2SVup1cShGqAUofAmv0J2zvXGafsQ/RjKByUGjdtQywwkWjEUCpGPYACj8qGHipdonPVlf46eUVWG1ZK97hJ20/67UamhmCLQ3oJgy/PqaT3nVX3S5J+4Gt84MmH7QfUBKWmP9J3ggiN/fx1xdvvr74IU6i37CTvfnwgX35zWPgh+mb8tsfv379+uKcZfEby3p4eNilno/o5UVRQELS+lQ8tMO0b0Cf/KacrmWvZUlefOm57HPu7Aq7uxRnebyrbsG9ZR9/TvLjEfmR/c4L6DnnJ8dhb8du0JL749evydev4Tff/MDmWuhilPSbmPhPwo49uPsf9E+rfO4Hq+PgH1mYlaAkCKju377969cXCQ6ie+ySrwhGiuuHrh/ZnE5KfvmP/6y/vo3yxKm/3USYvmX9s1LjU5Rmf6brRP4RthBh+49QNRGqLj6i3KdlAD2PN33Wgfr1BV3wdMKhtUt9hw0FYGvnJPWhZcmWCuDc4e+vGuj/+eLbF04Ue9j9i+fj9MWbF/9BooGEIk5I+LnlY+S9UuwTys4s5Hhg01MT+XFxZZUYJd7JI1Vp9Sz7tly7SL64JJ/YcpEwo59e719/t796+f0/M5jbmw+f3t+8vfny7/btl1/f3Xy0P33++On685eb61tCR+A64cUs/JV6niKSdG6zyLn7V7o5/UD8oV+/oX/QB+j/vaBNgI9xyD++4f84nIL9/mXs7PcPJ8S//Jb/owiiW/fufeSwSr33/kDrg//8t+IPGhDvikz3vLj/RqKGRMT/vn77xb79+Ovntyw2fvgTyS/flDH749cXl7uXJOHi0Ilou4x88euXv1x8//XFn/5IkmTIM9s35G/S0M2ebgke/rFKWzSJJyyBHyPfxck3IQroz2VSq37uPVBn+MYz9CmSpKtnuiXBN3nike/pM2+st2+sX0kLLrWCPHQj62OI39HRResdTu+yKLbeX78rk1txKAP5T6a0sWpiq0BuuNCAYy1I97ADxGpIWuNGz/BGz4NGu8UFlOWurox5QMe7ugPmP3+5tt/ylncKCdBXHg6Bqu1vkzKBFKQn4JAQ6g/j4Hv66BmFbnn/KyBKT1sWAzZp9rSHMaoriIunQRPJgLwCDGywiOQlYNhVMx5bweKYC6C+FVm04uLsxruGQm3Q2GxQk0EpMjYI6tnlIA1fm1/KwhKOWZFHyxIUpmx5wDKQQnvDUd69xdRE+TZoYyQU2QC50cgVW5hAqndsmEYbtjSASC8Xwwn9Zue7cDwd2aHWIkEr2+0e7XCDNRk7utx8p8HcafEXYTbcIzhk9Inh3kBx+RMTyZNiOJe/outYoWoVctaIIdnOAYpjG6WEonnxCBClUHsgBdBnSWPODERbWKL1Lr5rBIho2pAkoVmsSRaHLUvn5XKUOp7voyxKjKBJGJMlJc0GvABjx4xEs6nRiDHCN2FomDBBnl/M6saZZwRtyIJsy8ME05CFAabwPriyyzFveJ4B9QGW1uI+YBKh9nA8VVOWpJXuOq5jJKpGjAyTlWf1mExCgyYGqNwAuck9PEpPd6SGKe89NVC7dJRHGMp7eU1AdKUnKVLnjOkMR0I3n0YJHcs2CDZqTTotJ/hkqukyZUmm7SK8m8tEM0ZoaCzGu/c4GYrqETNStXCrZmKlnuFKecygFDEyTYikiMql7gbafm3hYYIjLnZ6GKEQiA+TpD7GMd2jZyYXCuVHSrDWOBRwmdXTnuYomxQmcXom5IYnvIDkwtboRMMDumqN7eM8vdzF4Ukfm1mzerIDAVg/d2nG/KWk+b0Z83tJ81dmzF9Jmn9lxvyrtvnxZDo09z84rMY3wnUG1lrPvGNZpvVE75lbj5iNwvfokHYe7D36558/7Pe9h/qKbCGQ4Llu8cEurrbZqgmIQfChRac8pKwiOKyGxxZzySqIrS6QNelBhpIsj7fkQpeo70NvhHMgGm+KEzym47G17AWi7J8fCiWz1UOajEr2Br+FcSMOcBxJ+EOeoGBL+BWQvAOZszEHCiBJB5wg3xJ+iSMLz0apkLOpGGhBSTpCh7S25APnkcUnquVxhpvxoEaSdSJA5K3USTwSfSAricB86ZHJuhQXp4NsxpGSRxIfb6tswkplUzEFsyn+ikjShSOxvqlMXQFJOnCKnWRT5WoFJO2At6kI4DwK+HYcbSsbtKAkHTkfN5YTKiBpBx43xv+ogu/tN5WNSxxZeLStxh3nkcWvjoffjAMVkaQLPmlBbckBzqOA/3hAm2qTNpkU3aCrHLxwW8MWIjZZtzCbA9mUNzWSrBNbq+B8xQrO31gF56tVcEG6qSqixJGEj91NjeGVOLLwyaYKohJHHt5OvVOI/K050cSSdCbJtjWQx3kk8dNtjVakSqMV6VPqHEFmwcH4KyJJFzZXC6vWwfnmKuFctRbe3JiX6pDXgwuznxWKn/NM4uOgXG2yDfoWzvSkdHMWexP8XSLpOWnh14IvRV91NynR84DGV0J4oSNYAdFe74SyKPCWqVgLZHqRhtUy3A293rJMb5lCo81XWp2CcyIX246P0tQ7ek51/83CsAMUE/DeNugHMabCHof5Ml2LdmBzs1N4xd63NbJWZXg69fJTnxdPsNywBGLsAR3eoA5ZmZ7GTJapXLuIibAS7S32zZLyqsiFAWvDk4i+l66RWyq702GIsnyZnnQ3DLlha6rh0F+GmUi0AYryYonlfqVj7NmmYZnsRf/I8GOwAmjXvGR2Wx60NjyJSHrQyPdBDhBRhWyYlisVVmDkdiez3HRbvTy+dbyx3to9PLVwWZSrp/Y90207iwRk6a7VMl/lJCGToAPVa6r2XrTPaJn1S2MOjYFNejXwrp0us/ZaMaIaaIqebcybWSlui4ltZjrbZhIbTl1DgynTox1SZeJ6scob8UIm1Ty2LTekPPA25oKARyotyjTEy91+oBU830HILmpbMju3neH5uYsznYLLN9jCwc3wcxpp/Bgn7BoI5G/HiTaTyRK1FetL5uCO/2Up1MVRS4Sb4R9eSzt0wspCiyCl6AeXQE7noM340Gaa4Up93/jWHKrJ5hUMLHP1d9eOlw02PiZX+8fTQhtLB4KkQO8WFG22eYFS6CmESiM+aNt3E8FTOiFONT1K6MYRbfqCtozqE6EW7u807Hcq5i7SAlVzZXKNsogFQad2aPKApSF2yVKSx5lsG3soDNv3A3QOJBAGtROkXmqHxDn73kuyfOFqrOc5C29ExzSFYEpb6NspqmdqA44OYc3LWVLli7e5gOADRFIhIRGvi062TLk1jgdXgpQHZMJUQVxt2RAsjVYB14CQSAXtE0I3Qd5gUXAgwRlKTjiz08xdeGxh0JE+k4JD5B3fO1QXwGzBnx6Sgjv5ZpJXPpC4INthVS5ctI7gHvM6sgEhMTK7BWZPDbpXZmwhuEc31ktm90340UNSze6b8CKXjQtvO/QCFLA2T/s8V5iWT1tz0WK+bZoX9n2g6bTbOejWfSI/kW5Ugqmp6pLeTTk2BCmR1nsnVbPlmas7OAKmHIO8+bW+V2NkynG1aMEkFUlydUMnDOIo8jeT7CbgZjm3Ta9m5qTTJou/mstkY3472a9s2wDkvjLktuZLg0u9DiOlKg756epZEi07Jit0T45xXuKNk4h61W/CSTbihgOUK5MeQH5YZr3wQChykm7F0yecf0qsuBCYDp01U1cVLp1k1mQD36PY70rEOVD/Ic6Xnq8jJqtKpbJutBaJlzkPoOkgL2Nj4d7/2fHeuh1ibgqY3twqDsfuLU2LNyBbAOxVvpFgGG56y3P3XRy82qhXJdn8ApddFGH7URSrR/jKYVKj98JlXjS7+JAvO7qv5FTNp+7aCovO1Xwb290gqP7bL8cEGmXL7ACVdG8EUa8tMLPGa2eP9QKqrAV7ONOdJlFe2JYfNZREf2lbESLgAWuh0EYP8voNinmtU6K0/Ga60nDVSG1CSHT3+eNlz2AT6A0Wmd5997UlE2zbBTGMZCyQPpmD09RGzuJzCKKI6OMY7fVUyXaN2OP9nybEjLyzBXTtdLe2E32cmcv12HZyehoTPa0DZd7B8wkR2CiYUH2dXCtm4bl5iNP4SBi3vFq2HgoYfnpGG0+m51K+soEsI+fbdGaCH+2r73eEaVbVegvnLm62ykgtkOnStXHRJe1CsnNBt+JBi0jZFZKs6HVRm3KmZlJ2p7j8alPeVEjKzmwrp7SRJFrz7VcXLlo7fohoTDaCGwXMSn5XJ181QZRibV3yLgnYQEHuYh/1G4+zKrRCa9EsWpjk2bMGmC5dimdtlAT33wX2iVQYtytzd1hMZsgyoJZM0qXHZUasAeam5OlDqN5+uL25HT+C6m2U9G9Hlb5EVbAjbtGzG5mDFvWhOqe3TzGRE4oX7gnZUg3+QeoGxAR09jtbPYIfl+l+CYjbBFJhfFroNP/B8D0NHd/fhmUH/wVXV6vBNgEmYOnKBVpqfr8WbAvAXFGGAze5Hy/K3AD1n5lTkRdCi9TizC2rMMjeqG3D1n7tMNjzyzimB3sKoEXvFGkFCqsuK16rjzN3Z3MZ0qs4VNsGa8YOrJ9RbxxhejL3gsHSOPe2Mg0WKvRInWojMUDR0NJbsIRo2WUv9kiMtZbblpZLGG2fafrokYClk/A+uALIO1SGXhiHcn/JkKJmWQB17U80Hujja2FK4tknHOJkodsqRKHZsC+Du9zVmCLYkWsw+6hLDcKJQOVOMeWP2kcfpec1YWsCGeTFjsUT0UoegseejQ6/YWe9kqo2LwMbo9N6OYsblwHNErTQrUsi0sq6DGqeeYs26tuolXVjx/Y0K8RyMbbte+HdQvMoDafp8+M0MpX1StCSeGX9s1bIVtbVqpW1cFsE0tXKWrSSB/w2y/W1UGvz0tXKWqjcuHxZvRZpZX3m8aHsCBGp4nrBA1AajhZWrQ6ByQFN3zuMD2iK6rf2UE2w4AIHBswebZodvcuFLmEK8uXpSqNTbHgNNizJttxpbG28wZPXuoSLHeDe4hs6qL1L5yF3hWzBrU7R+W6AlqfjVqfo6F3vi8OVRqfY6G3oi7OVRqfYFlsG2IIbWurXpSvWjS7PV9udIlxufVsLcGANm9z5w7I19DKtGeoVm0hpmJ2soc9evDwetyrTflgeLhDvlu+zlUu0V0Fs2B4lpWvnVgnJtuGp0Fzw6txWSErenMuy1FJDZa18LB4h66bF5W71badDuUt9aT2FgmMerlASNgxPMS65CqzFOLLyqx/TC9063IlniUuHy+cWnrPrUI7N2Il6gItDYrnycMHzbNt4g2fXiglXqwJ75qV6rItjDt3qJOyxLk7HrUr1WBen41ZleqyLw5VGJdhWyyJt2zJ968URS6NSfevlmw6ZeMWwoG/tHJcasm7w1XYle/9rEJZ25QjXazv07cuNVywOOrAFatYsRIJcLxqfhUiQ59v9uYrec7GfnwTnrfSeOxIX6GSS1D5z/vAio0IsMCzur1U4ZHEEq4Mjs6m8en6JRKKAr7psuh3R6MKJwrLHMrSCvD3XxS+QEz7cDzbmAwW1Y2Q7eXK/0JWK4hBs+2tVzljDpMK0MRS8Hf+pUG2uuHxvxeTf8X6IbjI3CF/cTKQO0Um5RaO9uF5zi26J6KTd2qxHKs708ul206EUqrrD202hUqjz66qGduvMPOGtoxPh2BNYsVQew7IksBWTUF9jvQSk5TpUYso81dSTedtILplnicAUEwR5aRMpQOSN9lFIsnvrxCG0RsDUBzVzgunjH9jLwXGZMYFRXk4hyVxM2Nk4SSJ6wLa7Tueg44IYStKj5S6NH3di8Ir4Ae4jRlmebAK9iTJBv3ImlcyhG8ieCnlzexlzfq7cRJZUyo9byYyTOVH6WpssciLRCGHnyYMvOpVmoLQiD6/SaCm9sYh9q8My2eraDPg4tfTxohjj71/uL1+/ko+2+p1VA6HGsMRkcnG5PW+kXJGN4IfgkEscKsJDkD2+akAwAqvHIxeZW8GfYpeNvd8f0L1CgcoeX9V9RmD1eORibyv4U+zSl+p4Ln5A/p18BPI3Vg0EDmGJqORiclt+SDihNxpx9kTXJonm3FQm5x5VJucog53G2PGOC83Vd1ucBKCYiqsm5B6tQTpRMhIlpG26Je/TcFGhk+BQnkUnLDG1TzxgrAn2MUolahL+QrHh0j6cgv3+Zezs9w8nxE7rQ8tHQemt1XHGkmGdLK64SBC5uY/tai6ZCnBLW3R6ihf87PnppSsuDYPuQfSC479gTvZdbLdj4RY76qp4wR/e8wh4Hu5ia2Ob/pVH4Q6ukAVLKzFOvPiME9QdU1Ddz0VoizPcl2n219w8rBrWJzb9sEcXXEQuZpVcTV4+vVgqFMNKLdUun11qsayYVGbVbP2ojcM8WBm3ZpCBXnBBrZhYcmVt/fRSq2sHcWWW2baeXnSp7Rj28JpbqUtppk7JaJdES9ThDWfLKrwNIF0Urgcrdc5CozBaj1Rmc347l6zHOrQXflajJsUO8aJ371n/sjS6AyQKcTh9AC5p6B+wm/mpneZxHCWiNVKyB/v0osCrxJHjkK5Dgha8YqsIKqsZGlbfXX4K0BisxEqZ+uUoCL04wSkxt3lHO6xSfsYpeh6xKQLVGGqVvEiwBFroQhjJUCnLowbbZFQ7yVOcRST8bIQ36E0Pb9IhruI4y1QHSu504OSdCdBSd53N8aakk3YHOy7JtOTPZY5onOVUm1EhH522mPB6eDKrQmnJWry4PYd6eNKV2nY96vJprMaQvOyV1xSbqtv5xcI122TcksrBRgsdzK/kRwNsughxgm060QCbdoLUBRv1okE2XVic0eU23WiSybixf/3dZh1psMm48vpyv1lXGmyTrpy2mtFPChm9XQFvzpUenmr7YIMedflk4+ge+flCq4fnxFGNB7ycptQXTieLHpfr+hexkCXhad02ZO1aq/nIwaTTe6Gx3LZHVYc6fKp+lcfYbdizmlDKtxTzM+VsF8c4dHHoeGuP3Qg8HOGULbi8LLUXuxxD3rcem8LoQLFnNaAjsVtyaghQKkXWL5cpepOF4yCloo9ZgsI0RgmxxJXOS102Ms/fEWJ93x02Gfa8vK+Z9f1HGLnPy3tOrO/76qPSqq7LDlRPCt3hJ1KrkX8XU07PKhD67DDhsdGqbQa7fniwW4zpZsnnFRQtbBPDz+21mymS2ZnA7oUNkU+A8zTDrp1mUbLUjYEyQUv7suSjNQYqsU+Bxs6z8XUKVsJftnd7c45VVDonvYl7eFtydZBQqw+6NQ9HOFXHERbdhD8zFsePypDpk27JuSFAjT7pltwbpdRogdAbEWjDbnspVYJXw+/lzvXQ93ns+A+tEW/MD0UDG+62a80127IVBB+Da2PJjCjWbyx38LC6N0qnEDdeW38cZswppRGX5otEOYnip6361cBTdGztMcMxrxRGB5uvbWdQZMy5WcMfXYEzCl3fW3eUe8rJJqOii5sYvhjzb2KgYtQ5lGU4zTadRjuIsn0y/nqAPP8QPW7JuyE+82scGw2FFRuHdXiUKx/aWIpJ2MVHL1y3tTviUBNP0bHVG/Fjbo202qdbmxv1afjSiPEiZgvDIV2/BgEV46sa1yS16KYcHIVUjUEusCUHBwFVO0Nn7NyV57lsyb8xRlUXt+3cbLeKjuJW3aroZnZjN+pXA29ON3ajXnE2vW7sRp3rU+p0YzfsZJNxdjd2o/61ADW6sRt1r4M4txu7Ie+G+MBXrvOZA7hx/ELPTpe5cmxojoT7xQc9WlTGBwO8LezuqIKgPUekOP1Fg2yDXpRYBnZylKexQucLr6tsswMUVz8NoUNVbxwYoZVKPvyF7azXG/B0AFRu4UZbc+VpYbmolC4ARAGzSQcHQA1UljFhs6O0dwqk4HHpqqLSXLmcrTgaS34aZJILmco37ANKSERkW/aqzWj+ANr+F51TkuP2qdwyd4h1nhFei9w3U15rM3Wqa/2kyUgkVvj1L+ya4dqq1QaYvlNqdeAew7wTd6mGH4nOROvFD3nMZLUq8pWYtBqmJ6KFP7lwhDQhpdPOSpxt6+YOMT74Oc6iKDuPFyIDlxV2T8YmvW7SS03uPQfbLmZ/eSEtjVlH3PbxCTndowVFAT8hZDpCqkDhUSPnmCVHDhaZU5WH8MqrefEvc4b14YRiszd41ndH8fgpB34q0xMHdnorQnqqlHaSRamNXBQvMNQ2QS1imfYi4/cauPhodjZzBL8HIcON3HtSW3vpMrNdo/RCFMmwDzFb37y6D0IUGR/cJ/LZc1ix6h5W92MQR8YXf++geHUXuhQy5DF6SLaUJYZ5pLzBiRe5JBa35NEok4xX6VPorO5GB0KqpHUcHJNk6aXZ6vhiFhkv8GO5JOYQha4XnjZQVo0iyfhUFnKk2lzPiTaDDPU5SrMNNJqEIFPHydMclKFllg8Nt6X7EBLcvr82dItAgni9zkplW46SjV6SNHTwfGJlTeY+iVQJv16HSyWki0TPzvpaN99xBAlm82uWx3AHFyULSMu90KuxNuyr3wZzOMmNf4nnfQW9+0KOVGuH/FTcf2d0HrQfMByhmi8bYjJ4PVzX6MJpowqCeqCjSzPPed87SFwyn3u+K3NSyckRzxkKhmiTDD9eBFdXA8/LJ+vBN8bu4BTGMgkLbsXoDZQj0UtvomShbZGgtOpQqp9o3EvZhBWfIzKSDqR+HjvHA+KiVaDbrQaGnpYtparCaQBl3ijYaj4IUeaPgq3mxyCO8ijYai50KTRGwVbzYZhHcxRsPY9GmVRHwVZzowMxcxRsvaJWyKI3CraaM6NIc8aTVvNEAKLWq12DvI8wp/fFFKY6X77EAjzZBeuHzMkSf41gK521fL8OwRaLzFaNxit2htI7H2dmlxQr+tGCMr8Nf8XhyUYwSI5UjsSng3z/QNSWHvEROdEHUnDE98I7Hz0Z3myp4EgLaI4ja6xwmPZmcMnDiEsxkaQ5cyO+NHDmFxTwgy2Pp/1edphletCkO2RSJ8elx0yqWKhHTKirzSGSFtzQGMnmh0DESUIqOaiNu/XW22HWkpNLZkNNn4HH1VNa1SpeOqUJB+TKsKnSYXNgrgk6MjLX9a+U3Lx7DU7oPCVMg2xVn8F0xU0UC2Id36MbcDYVCZywGw1CbLUU15CgS4GXL8e1Pa+xZ3j+jLxdJL81BlTM5rhiiKAxfJNm+bZK9gacqPgTwi9SHqZPaYYDs9FT2NhUfNRY3eioYY2Hf2NeJM0PCcpIRb9ARhGZ3V6OEVEKs86oOwvEYTIcCZBxluCNRU+CB6KjIDUe8mfhzmPogCdWaKPAw+l+U+FPuITB3+E1HwuO4dZ04ZWzrcYV4RGHvrNMy2qJWps5tMGqW1xtd2gXG58RDF3QzoRwC+LgO+QN6cVLMyLzVCxh3UgN0gofi7reXojUhH22w2yiQYb+wPPukT23YJTQ/mDT9OSspPLm296xC53fs7OXuHaMkqy7IbrbsioO2/HiqdFKkmqKZ9NIYthSair0gF5dvsJLLNdhm98bYWJVbltNv5hGn2pyfoO8cnW5PTdaTJLXJrkBqs+n3YgrYjJJh4hauZR8U960sKYn0B5tw+d2qXhQ08iAH/y7Be5wUeRvQ8m44Z5t5G8md7eAZPCx49hOntxvKhW1oWTduMNPJxxuLDb6YHLuuCnanCcNJhknTF/4o8gvf8fPox2gbEvoHEcKHQdOEG8JvgKSxTd7+9UMfNn7rh5Jz8oLvMzbVnHahpJxIzF70ZMifyJ7pdNjcZ3kdsgzWXTaubjEC6wWVO3xtKCk3LjaoBdXqk40OnobcqNNpdb93I4bLaY53c+NuCImm3QoRq5r+AYCFS8aOIq9to040IOScCPBJ6NrTdX4OY3WmnQ/d8XD0u3cFAUx+ZiwHSqh8VuTZcOh5LcG8BSGdAyfG6PsUBdMeXRqk84oXAxXjAltyIuaSK28s8s92ttyRcinMG61LW9qKCkXArQ1/oJIceBtWz60wWYMvm3PnTac2gDc1rxpcEk5kiRRsrkkVkFJjyNuywH5i9bIsw+2c9xaOqqhpIdDt+UAR1IYEt2YAxWUwrDo9lyQvUOxNQq5LTfaYLLDo9vyIZHvwWfbo88G8Uc6wA2v3t+8vf7l9vrill6+gi9u3u6yx2x9Dwew5p7E3+v1BwfsZn4qsUInQcnkBQgO6WxnKMzszAvwomPopR9WCWr1SCbuzMjOCUZsEGtN6hbFBDG/LmhV4CaEJG9xe/oWoCuSKXLSXF4fugExdUmN751C0xecTQK3KCaID6Ed5MsOyndxa4QpVpTi716tM5PQg+6zTNGTSMmDYnnuquRtDjnqbYR5n0WOPojcLYCXGNLMdoIeNsLNUZTYSUzdo5TAbciJFtOUN37kVOOz28gBQ0QTnjhnTN8rGrorTCn32ohinikvCr8fErTscECPvs0xRb38xEO/ST48tzDci7CpuZW5RThqPmwh2w4jTfmSLTtR3wPPBubkW5TF8d+bCOk+ygQ7duLqcRv56zbcRTBS/BuoZrsgU9xhlkTxkx1H/roppgsywe0HkdmDziaBK4IJ0oAIpMtOsXZRa4Rp1tVr9QbDFG2crrGcoAfcwpBgZhN3qyNXFBLEdExu4bVqIuQaQ4I5S5CzblHcopgaYUMu7VOsyttgmKK920Yzo8MxTb166dZgmKR9SLxs3RTcYJAcId5IuhDRTHiQsCUhmX3GfowXXuzR5RewSNBvIui7IBPcaeqX1xZtIdyFNBIelIcNro1eY8gws9GTNCf5O91G0hmlkvAo8FJndQc4hAQvefXyahu9RjGOtA93+Gn9jNtGmWB/fP3yn7eR6nskEjUtH7Et8vvak7I9Gqnx43UXR4ycTjA41r0+cMUhnUY2kjiUmG1E+nkbAa9YFHLl+slbSCPvgUvBisRGG0F2GNGLYDLP2YpTo4DyfqZ+lNkBCtEJBxsqSAVYCj5lUUJe3IwvNY68D9hZt7Dto8izH4/usodejMBzFnn6xU8bGaEfPmpkiD5AmymhShR59hjdbSbTchZ5etLr3wp8iaJQYm4m3FPFUGdtk7XH2Tosyu2kjfCP7Xwf9GDtNYQCFjX6LcyfDSPNbrFuxR8BFkQrfJvetQHVWnsb8ahEUWztbQSesyi29jZCP7wZdIh+EwOnAzwKXqy8jKWPotbe3gh7iaLY3t4IPGdRaG8jwhesvzJ0GEmt77AVH6RWSbVb7BtBTxVTUHeQaStu9LHUx7624kuNI7VbVeFAKsk9rL3AWvoUIR46fJsy/yx7dhBKvHUKhx5wCTJNnIaX2yAuQaSI11tqJMIeWXQk3Iq4CfAaZZqabYXaBnWFMk3d2PS0DfYO0LQH9DIX0k4/Rtvgb+FMn2lH/vL9jZSHTZhpcmcbib3kmOY9I/K//cttQDdgJMnjyF/2lJtxdo4jQc+2I663L7LP3waa9mA7paNCueis1ZHvMQ924wUnsKLsYr973AZ3C0eCniYoG7m/5Wlm+/iEnCe+UGYb7ozyzfPvmETBajuhpDxsEir6SHt97PVCaoM+Cghn+JjmdKQfZ9v2U0Cp6GuarjOuNu5bSaXoC11gukFnOJasNxsrOhTKicYxXBtxoE007UOW2G5y2EibrAEzSc42c2wCuyKRYN7GGJ0rOUbnnrfRuys5Jnmxs9KcbReYg8gQb6Twq0gkmH9bbYqtT/3b8BRb/yCHjTDLHWtbnpuwDeaaZZp7tU3wPerhjfAd5tNGxrFOkuNY5zt32Xs8hoA5yDRxgJztNDVaNJPsfrCNervkmOQtn9/SeFsfadqLdVbA9sgHFr/2aF9vBPe1HC8OouTJPuTHI05s5PvRNgYKB7gm/Qkx6UVHzh1eadVV148OzzS/R3rOd+ucRtljr1kmuSNvG9m05JjkjfE2avqSY5p3nZNjergDh8f0aJ30cr8RYo4iRb2N0rsikWL+w2aY/yDHzE9U3wR2A0aafDtjfT0ieR+ojW35wImmfYj8p8urlxvJrA2YaXKCgzJsI8fB6TaaKH2kaS/4Sf2b4G/ATJInHqlx3cvvtrH0o0Uzzb6RMcLBRdTd42POaBsrJTmIDPH+9XdbYS5RZKivtsJ8JUv8eiPtwxplmnojc8ays8TsuC3knLfRUmnRyLE3jgrbjgsdKDlPoujO21A0VDhS9JlHxy82Q1/jTNLXl01tAb5FM83uBZsBr1Amqe8JmrfSfvMudoNlknsza2ikV82wY+WcZBtVUhNGlnwbJUoTRpI83ca0ZhNGsIVu+ErI1s4y0nua3lW2gaWrhNNSWaFaHlpSLEVDOd37H6KDj9cdpq69GEJT9KxcrObiGIcuDh1v5aZS38EBwnl+3uEnYthL7Owp3qqnfcZ5vqZPYRQ+rTznPOhlk+657MuizqjuySp8p29lXkiPromjdPUOSSNWxGSqfq1067SEX4rXTnfepnmRVHZ0gHPtVqnAtz6drH/FfpSt+FPTyPOvviSlxS+//6t1MtKKh2sJ3OhBKXsTZvgxSzdYyo0TzvVzm6XDNOVcf7dXyo8TyvpJXk3WnRppuFTByNJvYKdVA19lR1V5uNEWpvMbHijN6FeH65RJcStOtICkvfB+307WrmCk6bMkdzbTpqlpZPk31SVV7nveIz/fDn5NIz2yJfxa8GXvq84X3Y+t1bLICyHOEuY6lsgIikEORy9lBk0AxHQpIzRBpzoCvAtcfTMNKaGp1LdPKMtImZncew4pODH7i/bxk6BoNEGc/yxlZSag/YCSkM6xLALatCYEnnq/bCRARK6CqQq16K/lCXuCM7/DR5T7GSHy0QH7rW8OEUrct6yX6h08nxRNP7IjJnapRx5Od+z3XRiF+M3LHfl/8gotorpvBE6+Q6RhgY/J1X53OO3pH8F+/zJ29vuHEyKvZVHkO2eSvUespemOPrbzXMzkqnd2pzDfOW725nK/2+8ud6To3F/uX74muqQkHVN073Zphhzyp0f+/YaXuTv74rtXly+/u3r9+qoxyv8DfmQlrvsJZec/egE64TKT2V5wermLw9MPVusZuTcvZ7+5n/3m1ew3X0m/OVSjxUmURU7kWwdSW5FYzM6kSPRoBjxku0fyTyl16RygxdqrffmZsDE92bD4kEaO9f7m7fUvt9cXt9jJE3xx83aXPWZDll2cOokXU8w//mA1P/G6tJVV2bc/0GD7DTsZ+/Tib/8/5WShbg===END_SIMPLICITY_STUDIO_METADATA