####################################################################
# Automatically-generated file. Do not edit!                       #
####################################################################

set(SDK_PATH "C:/Users/mundo/.silabs/slt/installs/conan/p/simpleb526998f4a4d/p")
set(COPIED_SDK_PATH "simplicity_sdk_2025.6.2")
set(PKG_PATH "C:/Users/mundo/.silabs/slt/installs")

add_library(slc OBJECT
    "../${COPIED_SDK_PATH}/app/common/util/app_log/app_log.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_assert.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_core_cortexm.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_slist.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_string.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_syscalls.c"
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/BGM22/Source/startup_bgm22.c"
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/BGM22/Source/system_bgm22.c"
    "../${COPIED_SDK_PATH}/platform/driver/gpio/src/sl_gpio.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/dmadrv/src/dmadrv.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/gpiointerrupt/src/gpiointerrupt.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_cache.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_hal_flash.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_object.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_page.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_utils.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_burtc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_cmu.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_emu.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_eusart.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_gpio.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_iadc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_ldma.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_msc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_prs.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_rtcc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_system.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_timer.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_eusart.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_gpio.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_prs.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_system.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/fem_util/sl_fem_util.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/pa_conversions_efr32.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_power_manager_init/sl_rail_util_power_manager_init.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_pti/sl_rail_util_pti.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_attestation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_entropy.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_hash.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_handling.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_signature.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_util.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sli_se_manager_mailbox.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/cryptoacc_aes.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/cryptoacc_gcm.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ccm.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_cmac.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ecdsa_ecdh.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_protocol_crypto/src/sli_protocol_crypto_radioaes.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_protocol_crypto/src/sli_radioaes_management.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/cryptoacc_management.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sl_psa_its_nvm3.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_driver_trng.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_aead.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_hash.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_key_management.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_mac.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_signature.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_trng.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sli_crypto/src/sl_crypto_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager_init.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager_init_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_init/src/sl_device_init_dcdc_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/clocks/sl_device_clock_efr32xg22.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/devices/sl_device_peripheral_hal_efr32xg22.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_clock.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_gpio.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_peripheral.c"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/src/sl_interrupt_manager_cortexm.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream_eusart.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream_retarget_stdio.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream_stdlib_config.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream_uart.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/profiler/src/sli_memory_profiler_stubs.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_dynamic_reservation.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_pool.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_pool_common.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_region.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_retarget.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sli_memory_manager_common.c"
    "../${COPIED_SDK_PATH}/platform/service/mpu/src/sl_mpu_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/common/sl_power_manager_common.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/common/sl_power_manager_em4.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/sleep_loop/sl_power_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/sleep_loop/sl_power_manager_debug.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/sleep_loop/sl_power_manager_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/sl_system_compatibility/src/sl_system_compatibility.c"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/src/sl_main_init.c"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/src/sl_main_init_memory.c"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/src/sl_main_process_action.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c"
    "../${COPIED_SDK_PATH}/platform/service/udelay/src/sl_udelay.c"
    "../${COPIED_SDK_PATH}/platform/service/udelay/src/sl_udelay_armv6m_gcc.S"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgcommon/src/sli_bgcommon_debug_efr32.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgstack/ll/src/sl_btctrl_init.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgstack/ll/src/sl_btctrl_init_tasklets.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sl_bt_stack_init.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_accept_list_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_advertiser_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_connection_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_dynamic_gattdb_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_external_bondingdb_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_host_adaptation.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_l2cap_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_pawr_advertiser_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_periodic_advertiser_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_sync_config.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/ba414ep_config.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/ba431_config.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/cryptodma_internal.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/cryptolib_types.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_aes.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_blk_cipher.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_dh_alg.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_ecc_curves.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_ecc_keygen_alg.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_ecdsa_alg.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_hash.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_math.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_memcmp.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_memcpy.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_primitives.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_rng.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_trng.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/cipher.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/cipher_wrap.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/constant_time.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/platform.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/platform_util.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_aead.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_cipher.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_client.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_driver_wrappers_no_static.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ecp.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ffdh.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_hash.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_mac.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_pake.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_rsa.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_se.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_slot_management.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_storage.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_util.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/threading.c"
    "../app.c"
    "../autogen/gatt_db.c"
    "../autogen/sl_bluetooth.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
    "../autogen/sl_iostream_init_eusart_instances.c"
    "../autogen/sl_power_manager_handler.c"
    "../main.c"
    "../sl_gatt_service_device_information_override.c"
)

target_include_directories(slc PUBLIC
   "../autogen"
   "../config"
   "../config/btconf"
   "../."
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/BGM22/Include"
    "../${COPIED_SDK_PATH}/app/common/util/app_assert"
    "../${COPIED_SDK_PATH}/app/common/util/app_log"
    "../${COPIED_SDK_PATH}/platform/common/inc"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/inc"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgcommon/inc"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgstack/ll/inc"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src"
    "../${COPIED_SDK_PATH}/platform/CMSIS/Core/Include"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/device_init/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/dmadrv/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/dmadrv/inc/s2_signals"
    "../${COPIED_SDK_PATH}/platform/emdrv/common/inc"
    "../${COPIED_SDK_PATH}/platform/emlib/inc"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/fem_util"
    "../${COPIED_SDK_PATH}/app/bluetooth/common/gatt_service_device_information_override"
    "../${COPIED_SDK_PATH}/platform/driver/gpio/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/gpiointerrupt/inc"
    "../${COPIED_SDK_PATH}/platform/peripheral/inc"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/src"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/inc/arm"
    "../${COPIED_SDK_PATH}/platform/service/iostream/inc"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/include"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/inc"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/include"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/profiler/inc"
    "../${COPIED_SDK_PATH}/platform/service/mpu/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/config"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/inc"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/inc"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/common"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/ble"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/ieee802154"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/wmbus"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/zwave"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/chip/efr32/efr32xg2x"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/sidewalk"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/efr32xg22"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_power_manager_init"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_pti"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/inc"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/src"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/sl_system_compatibility/inc"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/inc"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sli_crypto/inc"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_protocol_crypto/src"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sli_psec_osal/inc"
    "../${COPIED_SDK_PATH}/platform/service/udelay/inc"
)

target_compile_definitions(slc PUBLIC
    "BGM220PC22WGA=1"
    "SL_CODE_COMPONENT_SYSTEM=system"
    "SL_CODE_COMPONENT_CLOCK_MANAGER=clock_manager"
    "SL_COMPONENT_CATALOG_PRESENT=1"
    "SL_CODE_COMPONENT_DEVICE_PERIPHERAL=device_peripheral"
    "SL_CODE_COMPONENT_DMADRV=dmadrv"
    "SL_CODE_COMPONENT_GPIO=gpio"
    "SL_CODE_COMPONENT_HAL_COMMON=hal_common"
    "SL_CODE_COMPONENT_HAL_GPIO=hal_gpio"
    "SL_CODE_COMPONENT_INTERRUPT_MANAGER=interrupt_manager"
    "CMSIS_NVIC_VIRTUAL=1"
    "CMSIS_NVIC_VIRTUAL_HEADER_FILE=\"cmsis_nvic_virtual.h\""
    "MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>"
    "SL_CODE_COMPONENT_POWER_MANAGER=power_manager"
    "MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>"
    "SL_RAIL_LIB_MULTIPROTOCOL_SUPPORT=0"
    "SL_RAIL_UTIL_PA_CONFIG_HEADER=<sl_rail_util_pa_config.h>"
    "SL_CODE_COMPONENT_SE_MANAGER=se_manager"
    "SL_CODE_COMPONENT_CORE=core"
    "SL_RAIL_3_API=1"
    "SL_CODE_COMPONENT_SLEEPTIMER=sleeptimer"
    "SL_CODE_COMPONENT_SLI_CRYPTO=sli_crypto"
    "SLI_RADIOAES_REQUIRES_MASKING=1"
    "SL_CODE_COMPONENT_SLI_PROTOCOL_CRYPTO=sli_protocol_crypto"
    "SL_CODE_COMPONENT_PSEC_OSAL=psec_osal"
)

target_link_libraries(slc PUBLIC
    "-Wl,--start-group"
    "gcc"
    "c"
    "m"
    "nosys"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/bgcommon/lib/build/gcc/cortex-m33/bgcommon/release/libbgcommon.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/bgstack/ll/build/gcc/xg22/release/liblinklayer.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/bgstack/release/libbondingdb.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/ble_bgapi/release/libble_bgapi_gatt_client.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/ble_bgapi/release/libble_bgapi_gatt_server.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/bgapi_protocol/api3/release/libbgapi_core.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/accept_list/release/libble_host_accept_list_stub.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/bgstack/release/libble_host.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/ble_bgapi/release/libble_bgapi.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/ble_system/release/libble_system.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/connection_subrating/release/libble_host_connection_subrating_stub.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/core/release/libble_host_core.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/hal/release/libble_host_hal_series2.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/hci/release/libble_host_hci.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/system/release/libble_host_system.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/platform/radio/rail_lib/autogen/librail_release/librail_config_bgm220pc22wga_gcc.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/platform/radio/rail_lib/autogen/librail_release/librail_module_efr32xg22_gcc_release.a"
    "-Wl,--end-group"
)
target_compile_options(slc PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:C>:-mcmse>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:C>:-fno-lto>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-mcmse>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-lto>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=hard>
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-x assembler-with-cpp>"
)

set(post_build_command )
set_property(TARGET slc PROPERTY C_STANDARD 17)
set_property(TARGET slc PROPERTY CXX_STANDARD 17)
set_property(TARGET slc PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc INTERFACE
    -mcpu=cortex-m33
    -mthumb
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    "SHELL:-Xlinker -Map=$<TARGET_FILE_DIR:Gruffalo_Dimmer>/Gruffalo_Dimmer.map"
    "SHELL:-Wl,--wrap=_free_r -Wl,--wrap=_malloc_r -Wl,--wrap=_calloc_r -Wl,--wrap=_realloc_r"
    -Wl,--wrap=sl_system_init,--wrap=sl_system_process_action
    -fno-lto
    -Wl,--gc-sections
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztvQuT3DaWJvpXHIqJG/twFVVZktujtbvDLVV7aleydFXyzJ0YTTCQJDKTLr6WBOvhjv7vF+D7AZIAcUAie3q3R67MJL/zfXjjADj464u72w+f3t++vf3y7/bdl1/f3X60P737cPfizYsf/vQU+F+/fvOAk9SLwh+/vri6fPn1Bf0Gh07keuGRfvXrl79cfP/1xZ/++PXr14T+X/hDnES/YYfQx0IUYPpI5lwGkZv5+DLFJIsvUYyce3tP3kbhwTte/pxkhwPyI/udFwQ4uTw6Tm6E4sQ4Ic93Dv0vhalwX9Sm6EP0fz8cIt/FSWMPZSQ64nDwYPW45+Pm4SMixHb3l4XNfeb5xGNSSZLh/CuKhBNEsFt/acngnpbj/mAVyvpfe6HjZy7+hMiJfswSjyKkJHO96I1VJpJVp0ED+kP1Y/3NN7pyOHN05a2T445mbe/pPWHPjzw9nm2FkYzmDk2UywqEm2f0S98L7/NvqNB0vHjwM5NLAsWxjdKUJlBJpSxFKuaHFvzoqAs+9e29n2ESReTEbIQ0b2lSrmVOkw3Hj2i7FaAQHXFiR6nj+T4iUbKaSZJgrNGYF6XUAgpsnKWIlj0vTLUVQGouQZ5vZ4T+ExNPo504eqRpV6WhJjvhQ3Btu/iAMl9bmsUpsp3kOSaRxtRy8YPnYJr3Hu2+HNfRaCrAQZQ8684ZN0Bu8qCz6TmiWGf5pf0PSXz9BlLnhFkfnthx4kWJR57Xy/sEH9fqH5BLRzvES/WVuDxJ7RNtTakxFBOkue9rNaSdpi6vw6uYRTq7wCjR2ekdcFCI0Gci9TGmXVygtcQFe+wSP13BQtlDqBtSmd9U84ABpvjLVjWw32iK9AUHMR0/4o0nwO3GEXwW3AFXmApzwT9/ubHfRkEchTgkKTh83vaU6LaDCM2how4j+IEZOKHQpX2vfgMasrieOBQ2tGTFwIZOHXnPyaY/KHQ0y8lNtSZchUXt4gYW4TV6vT7JLpulNUyRBIXpIUoCjUZ7oy199cuz85mf/kRkZkpE3ebysUHCvrv03f+KLtLygQ+Y0DkCQVt7wWkWl5Y8nP5XzI+6q7/LP4JnhxfQVkIsM2gr7QbY9oLjy8s4PHLH0nUqslffWG/fWL/SGW1qBVnoRtbHEL9LvAdsvcPpPYli6/3Nu1KJdfCS4BEl2OpJtHKG1sC4UHVu3rrakvLVIsq7LSnvFlG+3pLy9SLKr7ak/IpPeay56lfe1KNTNc9hLrHUvbd3L3evL7+73IkuQ7FpHhuMzCxE9d56l8+zJ98ZefPOo2Sj8D3apwKvj4D8+ecPuzGF4kyiLBHSwMPqjk+eU4IDe38MdrtyjDVajqqeheaVVaW9VSSn1UobK5doFRytvgF+8ZbjTOgYO4t1ku5bkGM9uSgpnMm3RecOkcu5jpexs9s9HlE56ARKsZKlNTABkNE5po3qaZQOyhU8GN19lqBAJ+HaACRl4mimXBgAo+wEmU7CJTwc3Xx9ETlaU7ljBIw6W63UybrChyNM7YaHSCvnxgQc7QBR3NRJPJqJiVb2A0twImLf10q9xAcjjPW2Ixi4HSn8i1oZ1xbASB/SxNFaHWsDYJSPsZNobfVqA4CUPa2JXOGDErbjSG9x7hgBo346aC7RtQFAyk+aGT/BEvZ2WitgCQ9HF+kdJlX4cIQd5JywVsq1BTDSPh276KRc4YMSftojreO5tg1w4mz3pRfqnYLzbMEJwfkeIa38GxNwtHV3MT54F+Nr7mJ86C4mSLU22SU8GN3Y1epXKuHh6CZaG40SHpKunXrHkFLUTLttBox+QvQ6lyp8MMKp3pl3CjzzTp9T53DUyri2AEZae88H3+9l2ju+DL7n0+6VgXfKPLqR1tJc4QMQxkG5OVoP3w48xPJke8VTC+O+Ba2rk8KPCzwo8sjwaGoQRGP7rSbf9EJHYp2+vw0RkSjwlnWpBWWL2rc6QKL5xNnt7S1rXrpMSpTlNJzIxbbjozT1DnR2n5/jVac1grqYpqeH5yjs8vTEYbZsSN9NwApmOZHiWDREYa+BVEoZQwQpWBWQEpnY8xeOogZ0aigVQsmyjrBPJpHq8Djnr0jihcvGEF0qDZACGd9LIcpvjaOSLohky+aQ/XSpgObJiPfSg014iVIvWdT3JZuwSrHUvtUBUqsa7B+CnwIASn045aqiTqkBUiBD55nI91MIOi0o1boLwKbCAakuS8aqtAgv3VzaCUmxfHupTG0erUad6BjsXNOizCkTw+rA1XWLa0NyIsMZ+A1g7RNatiNliv6UIUUNI8h2umynq2QmtEyB6tDMXUPZWaPYaCkx6xQW+XIi63ZQmc1LtGxweVwNrLk2YGuTXtIAfD3NhDn44OVw+ZC6DOVgRGdehZVgyaXUKHRFVa1CH161nJd4+WYzbWwrdCCyMU68+IQT2ppro9y1cU5tbqeEqLQDvfQpW64+PGQB1MZ22V7K8ahiC7fKCXFdtFFOpK5oY9y1AU7cJs/xwv1QkvQbS2tV+LwaiZ9uFKnzNj4k17un48KjeiNJVhDtNwBdW2slWsEALNVa+c9G2VqSr6TML3UDq+YNrdiw2ohxVRPQUXHO1cLrdf19E2fY+dcSIFrNPIl6fVQb36DS6oUEJ0kWE/W5wJLc6IcumTkqL5itTpB6qR3ShLcfvIRkil35II3yvEXMu8s1tMpR7EGUpz5JDZLHzKxV3wFaRU97QlWONKWUEs5lpcWkORHT5kxqxcoQZ9t2uBULtbwoQeosaIEql55unG8tPFvYYHQTTFByxMROiavodRmlPbQBRp8i+t6+ipuqhf3ABBj5TFtBySSLiQmjxbo2KvUZVYpUfWoLVNmrrYOhB0lx0FLoSMrFh8SFq7EW1gMTsNVYC+cMJp09fVw50AaNXboB8bcdwXS5KDX7Xaiq8R8aUC3hvfsE3Gf6E52OJZgRKTbA6pYxZlS5Rgzuycg3i4LLmTAEnDvVIEt/lrQtAeeDUtMklAEQLX8vPeIo8rUVoBljGqSso0FLDTiu0iQ1ds5peK2vopWjFu31rEx33cxbdqB7Gdpy4rC6uIYkkZrvlCtGzOZaBTdOIpYo4kOvERz5AdhcllTM6Lwg2y/bDT2SDxVyvwMaWtwirqh8UyKakpBluU7DXqFu2zqbc48jORHE2cYzkjhTXbekEHUnWaOdVa8YL4tD0E6AqheJpWIOrFDCOndprFvWlh7jFcmz/t2TygPvDmBenqujJePGII6K99Fx8GolHaWlLTqg/OI224+iWEdxAE6/huwgDXUVAhfvM7WVDCkZjT0dYgCOI8ipWXqCZUSO14OPE++B3S6n0mXMCJowacaIZ6ReQ/TG3QoGl8hlDz2AV52g8mqSXtaNEeW5qd7E5uAbNDJiwzXkiQ9I9Iy/KQP1A5YlUD0Mb4MqO2AqsHL+pYVoC1vd39IHVSnWXcJ8cJAUprNaB6epjRzlNRVeIg/hz2qGVhdoiLys5mptUPBaooOo5jIHTXkIv9pGxjwwAYuQxSKuIOLtPd8jz8Z4ILnsYOo8H7sVroFr96y9kJUqsAZiLBGrqCxdczBzphJUQ5UUU7O8si6rsmuM76rb4bcd4jU8FGt4BdNEO2kDq/YIDVo+gc6jveri27EATJwWZHbVlFbqjQ1g8sU1WVq51yaAqest4V0TynOELrBiM9tjzUM/p8F2q1kBSpc6slobGDAPYXn2kQ1yWWQu9pH4MFZLd1ZwUKroBURVyRtA1RapQLJREjx8F9hH2r3cAbPsYZ9TtS6TWaWqlClSVucGcIsasiQ429sPd7d3S0KzvY0SkZBuI28vu8aVe+ZSKRZpLt9iWuo40kNUpTpYwJU3yMNybIEqUSS/53ug8NOyqSKHXxcRIP2OC+9xGE2745KLG/rU8lCYwfU1GLU2oBI1tuuEtcvfQ1HrAJ5L44YDN3lY0ri5ARJ7c+R95UFFQWDRiCIXbRUAeU/dYJncN/dTcFddCAPhECuSQOkmm06y5t19zdAawq9/Hr/MZRBpDZZBA33JvVLwA0bMIt0rJHArjnUNZVD6svBb9eH7DZu+Dg+FFrCDkzeEA2ST28OJNFleBLtpwkriANmgEhk+BNcb1ndmnl2+iDJfJc0ZTJ7UfTylAR4DgyIFQsY+4hAnC++G4aVUC0+d3PJrXXnUFl7hyiO21NXKowURObkCsg8+Sk+Q1BpEdYKLw2byuIEEycyRov1v2IFrKxo4dWoxOsKV/wpMnRZJ0MIbzHi8ajR1YhnxlCYKXWI12tmErWp3VuX2fjtPh2XrWa1EYSOxaXT1jhGIIgiZsreASrUaDbKZhyLXQQRq5qG4gQTjbrfLUMQaOKBmHopYBQbVmkLxqtFWCwCcB8cBaFAVAvm0EqJAsXqI5+OU9b39Eqeswp1c7F7QxdtIcsJ56WvDLLzZiW05CzJ1HiXIchYYggVWZrE8KmCXiHQEwCGXxdcrdJjIXqMw5OEhF6CgVijLefhugNR5VCjLeQQpQHKUIMtZxMnSDqzFogRZzmLxFsQODdlthkMexQ5ZdSYNznIuy3fZdahI7KRTiX2t3octGz0wpfnSQwtGoQ87ebE6kQpFrS9VpxHIRSjgsSg3koOQaWEt5MR27IGkThdoeQopXKXcSR3lm5Tz4r/UsdOpQ3L+nGGZWX6fc7e8qF7nzPoDFByyEKBlaQEtZ6OyV6rDZsH+KF4+LbxZupdLShdLlwiKayw9PktWWPjzCGU6WLV9UYjr2yUiHcN3jAtYhzCAU5zhKBOSvadrZIajzKNCUZzhKPOoUNRmOMo0ShAlFmCFtoulNutSJlOCKM661DtHIrfnlDvrcg5L3YctJg2O8gwQgkuJo8oFrncc4qnOTpUpSRy90eS3TRCluMRvmyDPt8V8viMIsZ8dJaKSjKAcaDKypQOgE9YV3CLPQ56YVpUyViHQqiCtHjzMceoacUlhlCC81vbXfiFBF04UlmP+pbuG+2sV1YV/i+DGMiJPRZZUdoxsJ0seFl6cyc+TbjpYtQRr3PKi8rUk07gpwqg0hItLFgErVS89xqwB1DEutLaMHbMGJIQVjuKq1TWE8KwBCllNAyz9QY1dr3QJmdYhcb1yJ2R6i56sxaoT407qflfhNB+YAGx7p8xYAjTAC9jQClzxUhK7fVEjHnzZIp6ewkQ8i2cIvLhQWC3lg8ffmPBCI0VlUaxqfupCJGoTwrlCVA2VkEMHh2U+jUl2FSoIw2IJzMZJErHA2y7M5KFHmG8EhH/ewWqgXOOCsDxgRLJEC9E2tBJX4KoEUo80VCKwGqS/+uiqO1oqDmCt0VVlFtcXgAt6SOREsr7CAc7el41xMtkqUTiQAUmpzqJ4Vg8bYAyljepynkDhOTHG37/cXb1+BZmpDSpogjWwFt8SVE7r569MHib7H4N9BhKOosqPHBA00XJEa4APldW6CKuwhcnb3x/RA2hTnQOCJlWOaA3wofJWF2EVtkBX63gufkT+PWT2VpigCVaBWjwrUPmsl7ki7bV9GidP9rol/hoh7HLjE/xyI1NqpzF2vMPCHRL9EToFLBYX6yXGJ2vU2pLCO16E1xEDp2RZM7ZuVUAZiY5YeZMFTc083RLsY5SC9KgVZHHU0d4fg93uZezsdo9HlMfxQ+oFoFRv9ehbIrYBGubKTBC5mY/tes2emai4rCFzzr4ZjbmmDU5u4j0IBcbnhs7aNgLx4rOLheg8DFQV1lf6BOPW0bEqzks6grb+Moiv9P7mjcttjBMvPuEEiXirIE+k0bQqoucvmxI2vKuUb6EtPviUgygcB+CzUj4XUOIsLqd8Wopb8UuUpZus+ZzUdls3IDYOswCYWIOpRk9hIzafm/KO7AZn6a7sUWJq27M7OEpbtKcIyu3VVrhAZ3kMim5LsqSvbiVA2VV3AQGaJjhainEQWo0JHCe14/fdGgHHSuYMvKYhRIodSlvoNjjexXLspE8U4lAlbCydfOyxS/zUTrM4jhLZnW4wQXtGMt6rySHHodOhBClcRVYktdVON2sov4ryM2UcZL9TAx8FoRcnOKWEVpfWsw2kLE7RNjnGM7yJ6xvsesZS7MJLbgRTsLqetbEFUBCc5DkmEc0NG+EV+A/MAUio7DjOso5HSkDPGCT9AC29yW0J/9IaoADsuLRi03+XhUxcJKNrE7Q+HNcoTgNzMLt0WQtbQK/SJHXNAXZP62no29tkBw3YBbdVH6G1R6+ubm5sAeQ87RZstDCkvBTzliGIZsMJ1qHdMgRBm/YCK/FuWYJoIE7oah3ibUswxHevv1uNessWDPnXV7vVyLdsAZA/rlVFj6BVtNu9rtGgd83B9+YraOjbg8uHB+RnC3dxL8mHxpwZq8tV0gwdVIyt8CLxNBjUtLwoBSQJj7AjyEZqZ/BYGQKsMYWV5QdPZSX07MErKQPyrailsQikJsVV7DzbxTEOXRw6HrTvhKNpwi5c8+aR1F58SYS4moEt0Jl7cXY4YN5SnTLGDAKVswa+LMmrNGSjVsFVkQSFaYwSyqWydVp63cYyhRMM1lDr5Mtd2+ptOKyhGGHkbqu3YrCGWnB/rqxYOBfvrKl7/Ex7Jfp3saCzqewhl7VSYKWOZwGXNVIgv+GXHUbdVnyHxnm5cft7F1MEd9Yhv8c0RD5Nsiwl2LVTEiVL770TySw2i6UfrSnDYCcfWKnYTOGccTCV+al57XJqK9tGvuPP43SKH7WoeeaoW9OEXfgZvlKgg4U5tTxoCFcRd2KnU86YQa0zSd35M2pV61iE3bDAhn36y5+Afa1Kl0c8UVe5NDDKyl5pXIWRM8YlbTecIEfJNWjlX+uagfEPNpjLQzvL8weO89wChve/TMkA9rS0oantJIqf11LSMgcuBdoDOKUD1NfXBtbnDJmSo8nt0TdxQqFLtYB6oudktW2Ci9LitphSpOCgEJCDCMEpWbXk9UzCzZYqAwHy/H30pFPPmL3zciBNjDYAB4pN2pU7FbpmwIu0iw9eCDvWnZDQNgcuBXzQPiVk4ShdQMbimzIWqFh2bYZIs6LDVdFXMmoQPE9qDyTtMVcrYgOj8LlUmVgtl9oG4ScdJ+zcq1x1vyCT+jbhRa0rR6OQYpK2lpDamrYp4UpKWub0TAlX0lHZ0j0lXEnO0KreKeGKsto2NU4JV1LUMah1SriSoJ5JfVPCtQYFLXtm+7xrn705Pu+Cj50uu7hsbLWi0lk5JDpWznra7uk4KVEnV3dlB3yZimXACrxLM4bXRbuKAWtanfT6zOw8GCJ4DICelWaD/oR1oOJYQerblTeibcQw1FaLrlXgBWCx7AJsNHiJtYqkEcOGNyhs2wt27CgVimc4CQbYXdWcgFv+Gre16adlCWzzUolp71FCCwJZU0fXphmlTzWO1vSPg9jK8XSU8eV3rQ3elLrgmke0vL5ILSJrgyNTzOhb1cU/+aXSDYrVBVS94Quc3gBzrdi5zKofyUY54+QWBZEZOvDSgkJYLSilTKpwFLOnTQmo3ACx6qKdS6jhvZ9hEkXktKRpkrxAchhlGxFi0wr24DnYdnH+Hy9k/VLuhLGjB5wknisbc54TTFrQkGw5qFOvKhGihixJUsYVJ7nuUujyNdiyqRYFe39EsdxNsc2tZlWRKB2MNdTiIKUeIB0Pjo+dkCi1kYviBW7aGX48bBW+pLrvwcUHuXXmCaIDUDWGyKUVnnjpsrXJSZ5caOX0DHG+axycLRdaja37TD97Tt7muntwxqPwaqz9nYNicLJ9VDWOMXpMdBbdcXxF3jjxIpfmmU7ukzbU+KfPoQNOuAeq2J45Do5pcfNSAt+gcbHV+OKnclvQPgpdLzxqaCcmTaixL5se2hXB0e1iqvE7RSnRMFjgAi8PB8/qAEHLNjuNjwCHoEoMfR+aXgdRiRvcsLnGUuWT+zVp2dh7vkfkdhfNsBsiK7aYcIN8mNQrim0eWQu2JlSQSuzk9yVPEZPeeMzlVJ5ZBmPVwtN5C8r+qOrLAbjzjM39Chq0y9lnx+LWOqn1z2FSVpD1GtqYjTO6HK0vQrG01UnUTMH76Gslju/tVZcI95nnuzCxTI7OstXGETgnSgh+ugiurxVQx1TLVmBJfJXbP8eN9K/MrFRI3Yw5UaDZDZl5ebBoVlpN+jdPtO7LbBtfHv2kI3B5XBFQGJX4JiZddLvRLV8jLjS1fqnujkagob1zYGy50Dq8c2CMR+EBvXNgZPuoWrxzYGzH8bV55+C4T9qA886BEe6Bgnvn4Bo0LrYu7xwY7UkTsN4vMM4cYKgZPwTHIaTeWWxua/kk1lfeoAh3AGFPHJL4EFlRJovl+02udLBhDu+0QG2C0nsfE7mN2ZLMO0bO+uwEpFO3lWSK/l2h3HaQ7++pPVU/HI/20AAodUbVR8+SR2clqHcM6KEOsZ9hnr/0BgchETE1ymqvJvYt+C0aB3PdUE/H3Q7eAQXrIBq6hprKpOobqstL4xliSdJ2BXWMqfqC/uG+kX5QrTIBVCBo3y1nbyPOx+6QFVt2+CsMrLtu1/Mt1brNdfWWKV3X/LbLt20YyOc7VFcSWF1cy+45t2FjpZ3Ky/eKnmF5r6gXe8Ad32MH+bQWj8piv4BwaeisCS2DbO+7en+urLuhoV33hlr/TluBlqvxPNuBwoHXcpjSMqC3H2wZ43UXXDJ/hyWH6U2fU4KD8yw4BXftLUphpl9QGuN/hyWjtcKZZvsEETpEPM8yktdnnhz9rQzPKre5maT3d1m6EvVM37I0JVhzwUnwSEEpLP8dlomTdGQMk4oEZc8G0R5Od1pLBrXDLRg9+3+P5cM501lukT+O3okPxeeXC+fvddZzzuPWPGtWGLzyB6496+dcNpRurRu4jpk7ROiYviQyxdWw3Vl7QT0Wx3s0jXU6qW2xJOpuRG4b/y9XRM1bfpJxMvOWuy+fcgSFYsS8em0okF1UgAE+ZoNUDd4gJy9x7Rgl5HlR6JkiBKM3HYZrEoLWtAIljZSXB4G2fe3Rq6tXeMmm4jwUUStNrTqBrLbOfBvV0ArAvg4Ken2ln3jHBti1mW6AmhsUNJHnWwKTQO2VRxi18u+YgdgO9GRLxm+V4dygw1Dd+/cLbuCTZNw1AkPcPdnI11YvOwZgCGPHsZ0sedBaNrpG4Ijf4+cjDjWn+NAQlAA3Rdq5t2zA0Ja9hFGSMeS9i092gIhOshU8EFkcOEGsk25tAI6w3M2iCwjD3SX6RGeCXuART29j1zUCQzyRu1JTknECd3nmU3GRtz6uBI4sG55f4QWnAWTnAB0jQMSvV+B9DU+7NR3SSLxrBXrSpY94x4aeSZcm8nxLABJi5LqSt0fJ8G7Bg89cNFEeGAEhnuCj1AkROcYV+kanx/xMOrYxvz5FQUy/SPITrCHbSqElzUrG1og5UFeGZBw7aQl9Qxr8MKvQB70ut/CWaOTdWIBu1ewydote8lx7oB4avfwbI0CkA6SbcWEB3Kmkl3XXkBbHkn4BXWPQziXd/Ft2gKgnSZRoLzi1EUCvmF7KkNfPUrRH2znoLh2NEUB3nl7KlQlQl55myrURULeeftJwd0J3vG56iXcNwbn39LJOIOe4RD9fsojwwgljR9/727c3v9zdXNyxC9vwxe3bS/JE4LWOmNni/pkqGXrz5mCPXeKnSvs+EpSI7DqZyA6HTnoJColNvAAr+ZVLPVZJyxogK91xRU4JRrkrCZJjB1WJX3URISi9NigIO5uZ1EKxRlbjSQe78BRboGpXv/neMZS9JHWWXgdVid8+tINMzQXdJ9dAqjFDKf7uFYyXfEBxiK3GlWZHFhTbVkF5dnEhOOpJzyE2BNcgcnXQLGGBGNoJetTEsoIGZErz6AGldKiskXLHhhp3P3Jqr6OekjtmQYm3c8IMtRhmAixRDsZJfHw1zkUaPCZIbXI84NrFVeOo7ugeDjmX+bKnxsS2F8SwxZQPD8lYR+UaN6HGnKgt5A5okgVrtj1OxYUaWlJxCK3EFDtxDWYjH3ZgygMHYKuhy+oDq7EMSRLFz3Yc+bB53wdWYukHkVzIyVl6NaISr4DCp2qLaX1iDaQqM/D+sIWpxi1OIRZ+B/Q6sMoM80UdcII1qjI/5stR3BfEI9jAKjMkCXJgm74OqprvBbls/AzKroWpxu1eT3fcw1XlCN6+tDAVuT0mHoEteS1MEJ+fphzmoSvxTfIFeWKfsB9jxYX0PlsOtjJXLcnaB1ZimaZ+eYmdjjTloivzLYNMQhNtYNUZ5nP1NKN1NNVTCCatKPMPvNQBp1uBKrOjwFfXemYzfHggxvf4Gb56daGVmD69fvnPekrrAFm516p8dkWdhV6yGqADeARhF3gXnu2d8FXC06txgXJbUzYDMrQRna/oKo0VNljdgS+WXHQovm5Cm+OiULGhhB1G7Foo4jm6JEwahFKV+hGxAxSiIw40NmUcM2AKSJRQWG3MG3goxtiBbe6G0FBMDwdX7ZD3BNUKG4qr8un5Ca7Ljs6Pcw2QtlajhIZiGqN7bVWrwobiSmemuqiW0GBtlr7mCjRF8z4f2ifTwwYeT2hiu/RM6ARf6F1GHGxIrjpWKcZNaBq16WLPMaN/3LmOlq5ByDGQJv4lNOgYSBPVCht0DKSJ67JDUuNctTjQRvDBOAMvvA+hIUeYmpiW0KAjTE1UK2ywESYK3SiA3xc2bgJybKyLMcAOje4IVhPRFLQs9F0aukgPzUB7TnQxb+DBz15V0kACkiifz5pIbtVoFFX6Vgf4qs9wMShQ4sE0DQOKJTAExzS80sOxBAbiCLfVgkd04aYLLtvi6IwWqg00BM/8SIIenjU0BM/WAQQ9bHsGIDizwP50nHyI9DDuwENEJ6L/8X1NrVUbHIKro6fQlrgQDE+I/m/3Ug/NFjgY1zjy1WInTLOt4EH45gd74E4MDRl3DUBw1td2gbZaDtTUdsBy0cSWzzEKYkQudpdPeph24EH4soJkI/e3LCW2j4/Iea62J+gRMGlPl6JDQmfWUGcUhDS1LYKrYnOt3EBhbAVVHItaVKUZ8zxjsq4yjlVwdWkK4zmaVlNaAWfPNtKtQL8yA8dfc6UHreGt0CmaKHctQLAmie0me01jnRY4ANd8Q7gWojUyCEs9fiMXzG/knvTMcEpcAIbYAVq561OsgGE4amqaamQQlr+BLdMMef62bJlmhCnMuvKQJVQYwPIssB6WDTYEU7BDnwOeyw5+clkeNXlajmCeltO9qxYJfIxiBQzBkU5+9XXhHXQAtn6gp3cscQEYlog6fUBDExC8Yfb7Dbgu2Oo3wu+1JoKvoRjiIEqe7X12OODERr4f6XFXjdgBUBDSKXAaOfcYaLdLn3kPH4KxR2eN9zDxuwZsG2wAppGnp4KVuAAMY6ynPy1xIRjCRCoYEFwQrGCEn5Ne7TRxrKCBeOppTWtkIJZ/0MbyD1Asq3itWoi2wAG56vMxDSxAsmYs9LKuLECwjvznq+uXmqpZCxyCa+I9IIJt5Dg41dP1D01A8K6i/Gph3AIH4Jp4tB90r77Ts+zeQYdgq8k3tWjLKJdhekJ6doZVwDAcd6+/08WyhIbhea2L5TUcx9eaxlYNNARPTet8cCt7eQgX5Jz0jAA66FBsWwFn9JHuGYHiHkX3nsakruGB+BKPzc+18W3gAfg2VznooNtBh2DrBdqo1tAAPB9oLfCAznv2ibawAZhq25UAuA8hD0HkJHo6hTY4HFc9tb8NDsY11bNM1QaXPHQDcr8unXuA3K0Lv5GPMrNg9+uVQQGKDUAoY+d4Q7T3May7tOE9ZgpcS7lFyMUxDl0cOh7w4GUoacSiLmX3+JlS8xKAO4OFtQ1t6lKXPodR+Ay83jiqq23N3BMejD786Y4iPRgu8UIWCiKOUvChfivl+ZbglQDdnyigBPwCxR4+q3W0g2IuPOiRIUfN0BqcomIHvS4FDTokY/CNBB3GkCdJOnFEAMPGcIgPjGjgHxL8RNIVWqRpi/qUrVOv563qU6i/DZ62CKeMgiewTvmWiBocjq+GExwtwrAnNcqgITqWclucgVdz6+AWZRHURbtjAJC397u+SlmDA/IlSeZoGzk06HCMtU7LNMy/HpCf6SPcoGv16EDeIj35yMiPY1/39ioiL5yLRMneeGO9fWP9muIktYIsdCPrY4jfscbAeofTexLF1vubd/Y7LwhwYh28JHhECbZ+TrIDRYuqHypr/YTvB9KIZ8PjwnEqjQlQmimPsJQ4xbO/NI+RG+DLwF2LVsvgDLXUt4+IENpjJA+eQ7sNnP+H+QqSIB/s2RHtRxLPrcKgHnGIE0RyBbQFxFxNA6v4Ka/d7idETn/0AnTEJUnbC44vL+Pw+IPVeUbm/SvF93eK718rvv9K8v2URRzzHI8827RJtXcvd68vv7vcWXESkciJfGtP200SReREC6hn0Tzek8sn+ieAjUH7XcXEi1lcqeJDGjnW+9u3N7/c3VzcYSdL8MXt20vyRKbtlz0A+0lDneAUSp7Bqq+iafkbdog1mtblyJByYDXGuvPoU1H4Hu1T688/f9jtrNsqwBWoXdrilBeoFllBP9sopYlDVjDkR0ddyViaoljQFoaVYhUj++OakvbHlCDn3vJ9HfaqTCp7CcvJAxwVke6S9Q2miTaDbz/c3d5ZbyPagOipvwNpZY+7YmLWfbxHdJrDgZs8WG6A2H9WtGOlOzqZPIaIRQXUaVJf/W7s0D5Vp4EE0efpv55vM0uxnx290DrgYl+1hh6labHK1BMdfepKgcJPYh1jmg7aCymzkt9tlWSx1roX4yTfG4dW6Q5qSWu2YkOjGruFSaUWSgLthqOU0AlDoCFlRUf0npb+UNS61sylUxT6s5VvzgziKMQhYR+qU7tpFsdRQsoIMobQoMA4xdCjfnk2KxTInotwLXNlnGTdVbs8HLxi09mzuEK72bNI32cT+3XExpn+jj18CK5XsqK7ESpSLY4ecbJOmRxpZ9hhrnJwtt4AuBiUrjXabqbx2oa3YyY9jPH3L3dXr1+tbfkx2GfaJmZjRn9/RA9rpbFzomMXfEiud8W/T8fd09p6UzpjekT+/brzxhhd0NapPDCwWh7zbNcpv1uXRf6ZDSjsTgOa+1o2Y0K8lRvvVb1ZbEiKPK1umL6pFQZMtSnfTp9TgoNyo6K393yW4KuoxThmQQE26f+9MsbwNmOPsh2tOGww+fToAAg7dpSu48KhQD4aK1YBcpLoHT6wVoy2rl/r1eN8oevlp7e73b/9/JPMi3fv7bcf393Qfz58+vjLzS9f7Lt/v/ty8yFfTM63fTAxecFXg337/uPb/2N/+OmXn36++dxB7ywpSBup8X/68tP7jz/bnz7f3NHPamTf3fzr7dsb+9PN59tP/3Lz+af3HcKlc7Rx7Ska+/DTu8//2rWQ+9DVYH/+dPuxA8p8nmqQ//JTnuIfPv7SAT4h3x4dr0vCD1gzcHXmt798ufn8+ddPX7glcOBMlDGWL1TZv9ACY//r7ecvv7LCovK2/S83P727+Wz/5fb9TYfl//N/s4j8LydIvdQOaQm0H7yEZMi/PBW/yJj98Oebd1/e39EU+uUvtz9zbPnkf7VcTNVO9z+q5cKnj/9GhfFyoDNIWyLk091P9tvP//7py8dJTZ27U5dp+vzT7Xv7/e2f7Q+/vv9y++nzxy8f3358b9/9+unTx89fOhZfLoH+9Qv959NPlYyiNPAypzWwRFA5dHfDzZ5mIKnYCXz83M0TdoHtkkS6tn/6dNtBulIU/v7m5tOX2w994fXQSxX+tiyePfhqdCUHf0tT4d3tx59u7uzPN//vr7e0z6P5dvd/bn/5WZ1nXaRHCPfGZIpNwt3NW/vjXa+HrUdcHPDSGfyXYvcc9OakJftK2GQvP9lnHR3HokWa4KeL4Pq6eSLBPkYpZk9W310is7XVu1gaZWwW35bC9hrSsSpODNfCzRof26coJbXSdhZFIQtd4e7PWhf9Y39kuw7byqovi72mju+x2zH/zlWymdV5ltFcQ/00/XDdbUnYz/mt9WeorcpBFtSODrx9j/7dy0P2u9363aaT6vOuk5y2pvztrGVNVsJzV1Y4P/rSim/PWRudMYTYybd2pRllTGiXx62BvAfPviqyZnNE7Xm3pyfkc3UxPwol6eF0d9bynEErU8hzzrqh4TcyuTLzWpqR9S4WFOiIw2K3Dv2uJSb/XEZr2R+D3e5l7Ox2j0dk0wT5O5AWRG5G86te62SyqocE5NWXsvB8/txHhR/kee25D4YRLWich2np9T/G5TSefbjNz5vV315mziX75JyQF+aT+Cj/fuqxSyfO+m6gskqsxeDQY3CIH15fpPFq5v0I0bHt3uv5uhPeQUERBmzFim3kmiZQPXWZL3ZhWiVd3GFQnCNcxCA/eThjv3im/M+dk3gx6Zj/p2q5rKlw7ElW8S/9lZLmkIXlYKcY9KRQCSTJw0UEgXOQyKQQhZHtsOZvqxSIAo/Yh4S2T3Zc7NbfiEjIgnywaeiGxYFySAjxNigI1TnjDyjOu4xt9Ds2u4DTzVvIds9x9f1K9p+eRhj8z/959Yd1ONCxTEgnX+kl8v2NsqGmkEe92ZpEjF0UEs/pduUjJ9+1ZgjtTPP7+dKtqLAnAu/3/KxWd8nG+32tHotd5Wr7+AF3S6eLDyjzedvu+CQCdI/zLh8lwSWbIBCUHDHpsxh5bDC4vAjoNz8uGGIq8iCnLNj3mJTfrUOgP8a9COg3P5Yj3Qv36rvViHBHu5QO+/6Cfv+j1Mh3YKZppGcZNY+O9SgXKXF/lOlWJmzEsQQhFlRlrJMpSEn1NMC0eOOPi0MYXRTfbkZqZGCWU2v/tm7ZqsZM9thEizZKgUTXAJhuK1KTSbGqK7X7Y5uLf8u/WT+h9DNalD7DgdfFv5XfbZhGWlnJpNPoOOjiI0grIJtCuvnIpM24S+HiwH67aH5bP6FWJSeTatMOoYtD9fumqbcJSal6Oe3MuTiwBy7yBy7qBzaortvQlKrFI9OsC95ZVP3VVgMbvnNq5LFxb7KaE1mRVe4+HThPL+jMCzvpj+zXy/zPtfjUw77isx2guMvs/yvxvn5z8QHFP/7Tf/v465dPv36x391+/u/WP/23T58//u+bt19++enDzX+/zF8W5F2chLlkcQtL736fcnmeIoq7HWRnoRA8mbzUGbkmJgd+76WkBm+GNP63FxePCU0e2kZgbOep1foyyG8UH3zt8L9OcPX9QJwEk+ZgGttuO/yWJjq7NtRGTjEEkTbFZlI+b5+vGMmjM9XnWE0uSuZvvmvqHxk8n8HyaUwb+MvU89E+zatt6l3viobfJZfFOQA3386QL2heHsPssm5m9qiMpNrKihZc8+xl8QBtkQ8+Oqb/yKo16iJ9m83YLpLHJ1opjwEOCUilXFBg6NBBosiUT1eF5h9F5uyLzOioEqYhX65aZIS2SotaD7OF2tTOQhCtIizZLiNywgnbOm1YAs5icPY3zTMOaD2hKXnh4/BITj/yTt+t1LJJZV37+X9kHmTmDceKsI2MlqZi0DCyoNLBHoz0E/1QQ148euR0kU/6TR42ysI5XuJkPkrq2xyfl+9UMEdVSEuxO3ApyO0xUBmpAUhpRn2SWfRDFUmj/uabH/70FPjslSLUEH3p6vJlDkLRInaCj37165e/XHz/9cWfGqDKCVHvfM2cy2L/7mWKSRZfvs3PZ34qHvtE0/zPuYjeHuLLfLcuRaF4MU7I851D/0vhaidHP0NiCpWnxx3B8R+poM7nDYSqS7T0kyw3j9xhQvKdNiZyzJwyKdULSf8249KHOdbM9x+/TP18WwPBk3cg9+4euXQSp4og4CQF4/JCyboqfuVdODLSzQverjMs6i++fVH6Ge3PHz9+efHmxV+/vvh88/6nL7f/emO3f/r64g3lffn1xd/oO3e3Hz69v317++Xf7bsvv767/Wh/+Pju1/c3dxTgP/7Krn0Jogfs0nfyxvLb4o5Xqu6muASDNqhv/uM/m6/voixxim8bL3J+ltTdM1/9t8NvT19fMICiWOTkqmLz5sOH/MtvaNkL0zfltz9SuS9OhMRvLOvx8bFqR2mTaqWpVRUnnMdHoE822fG1THv2pefmn/vFEcXIubf35G2Ro7wyyd6O3aAD98c8E8JvyoBGefi2b2KqDyeF3cv/wf61yufq3KsE/jFPmJIoTQKG+7dvVZO/jLHb3K7Runbz287PfnTk/rYn7I8ip4qvsqS4PbH4pf1sEXiHC8Niftpla8R9gBNbpP0zu/ylPLHL/7E6KmQjlzZQxEuLmxGnnxV5oDq9N/YsKU/auigmaPpJhyT+zK+pc8KsOCTsNseIRdQae6ET+MmOUsfzfUSiUdXd5wnz4Iw9GSWjv7UuXbBdx3XGnqti74/9XgUCt3GWIlosvTDllwtOHJ2Rn0tqY091QvcKPpXg40SGdmMjjjzEjTMz/swg3KLAO2S0VjQBWFpPGNPSZs7fRRtbdWafv9zYb6vQd2mZFyOrqK1f2u1Nr3vs/HTq/1SH2bMdRGjqHYeP4Af28wmFbrlOPvXz4O26jhZPpEOAwRPjGHlZblV2FDqTiPznZ/AnHuzWrLEk8XqNjV3+NMAbPEgSFKbs9OPEK6yPa66An8HPO8TBQwZV3i84YCc+8d9J9WUJXE40PPabMSldmviACWI7uc4kub++4F6PmGNyLz7k/rIb/eV69JdX9S+LLxicfFvp6sCiXHHLYXEt6Lf11Z8caesnYXWB6red6z8nUkfpdiRL5h7P0ywP/gWDrT+XY1CiSjC0u67+Wybv0reX2S75zwNMXClnFdE06+UXVSDm/VTFKJ1TKjj57Ce4vlbACOLMRknw8L0CBvmddf8EP80VL+ErPK3OnjBYVBvVgy4oxH2WoAAekwgXMkFMJ8igEfM+BIlXB0FcNmGHhqSP0cYZGjVAFDnNN6VGwg2LKHjs+8CQGLwIFDMfYNBDmjjQWXWMnQS6ULGI1RogbXbRFzDu6QCfpKfDEzSkt4POIw+BtyWeg5zT3LhOFtSnbYkGyKc9gm6XKljmJvdC8O7Ux7kjEBpVQ/n34ct/kEIXVjrbhkZMoLOcIlZXCAMj01EUdIKm4H1o+pw6B+H5jSCojkqU6ahFOgYQj674fHEWEgfl9B4Msdz0m3NVBi2cM1ZKaDJmcQk6PVUXB20TFcRsrunOJ+8ijoexd0kUeMLVt/vu3ltolB2Utx2f8vYOtKMnEpP0PlAeAH7pu1Kuiv7biXBZ7b6Jw0y4t+i+mbItrAtfJYhkwg1//93EC4WreuddDyCr6TylVcjlKkj5brmIzcLWBMsQiqRf9mqRfMvepb0W8v1U9O3eze+5C1Vi/tR+vWSQvy5ovbjRtVUAMMt9UePF28W2kfzt4s/Fr6e7arxT7UWRHP50EFlylISkUoOlX30pUs6r840cly4Yo9QFk2LWunm32JHT2TcgeUlw/ofCq7bUdI8HUO4nUoHId+WJd4Y8iBMSdieNvG4faGN5UgFhe3tU3o/2+QKlAkKMjkp5SRIkPhLkAbDlDcl6ngOwKpWXZPmaVL1almQFgGZnHGtI7WqX93LAplQpgOSlSuH9slQpIOSlSuH9olAIA7Bo1XknFkgOsDuvSi0y9N6UKMGt99hdzcteFJ90998rb3Jd9rrUGL73qvggfPCifHPfApBw8nffk5qJc15VSWmZoWDnRRn/budFGYdr50UJH13/PZUUknC7dd5LUMDCAi17V8J91nlRzqXVf5XdhLD8VaXKI+U267wpuaLfvMumokuaONZ51K24VNdRvsksLnkPL32vaGCWvCo31Wu9mDcPS17Mm4clL7LmYcl7rH4veS+vo0teLCvakleLWiL4ZnODcjXvZ4M+iSEEH0Cuu+JjyPQ6fASJVnkUIHe7KcLINbijGBIt7xSGbBPcwip9O60cli9mLQyZhoOPIFEv+QBy9Qzwuh0N5uauwFlgks0JrBzQqmCfil/ZLzY7cc/cs6JFSQS9OpYCYqC8+5V+VkeoDr/lQeZz/7RwszABesCIZAkIVHAQbh8mUMhzrMqmzEIQEPBUr3BhEr5CU077Ckgl+WM/O3qhVR2bax+hW9jCTSEqcYzRBW0dy2F5Wlf/3fC0W5Y8qCZIz1hxhq76WLSXaukjYgBaAUuXorRoNKADm3OeUWNSccsTXLpNnbqcO5WpVuaULENpJt7gGCmYKh72Qt7NUR1cfLv3hf1/U1gVPwA4D2P8/cvd1etXxY/NZ0Dkii8ceOq5+BH598VP1Scw1IowFPBjQKe2xff5nzB4FUsQyN8f0UNZSvM/YfAqilKQ+fUU9OfOQWH6bdWW1Bs96m/0IdvszGFKpDaCLLDinLBzL7mivcRMPhXVaUC3Asn9xQss0AeSKH7WaOEksWC+AD7fXxEi377HzzoTisLT7Ei8B92VgxnKD71LbOtaYCbfbsPmZhptSE2zFuDLzJAE4b02vuzsdYmNqvzqtBHQTmkfPYGZqPa/NT2S4HBUHrnTI+mzUnYV+gxU7aw+CyeJLSQL4Hvtn15Ddfunz0zT/umzIeMTEoTn1ms1E01cpjSL2cG7at9hO3YKchzs4wSi8xOyFwWhF9Oml76h0xwL3aJVGmuNEWZ3q8HrYNiOE+jDDpCjDfyokXh6Qlc6wXevv9MJ//pqpw++/loXfBMeUKeFPH6uLg2eThGsHa/DBuTBGKCb764FWtG0WKijaunGp62QVgPYcWlu039Vh098M60apwm+VVj1WPAgTVQ+sxKvMdH9XrneCdqxc5ceRDUcM1gZKIdt7GaRVW0pJyTN+/LsUT4qqFsWfTboRytfi9YBXHuMSJKlBLt2SqJE4kyEjC2WJ2vZyw/01ZlT/EBtKnuRZgzl4RRjlLAAldXtm+ods7BJCB8T11zzleQm+IVGgJxNXDN0zliu1dr1PQQerKnuoAOyqevaKL/xSGrLnAUShx+rRFoNtUt0aRRh5K5uFMQPJm8WwHclbxTUo7XMvM5qMmMeYlQtaxPK58a1PGyv9RqR2Vwia0JXgzPWDyiaqrK911Wrdi8jsHYqvJ1oFrkKQVADK6dETH+yo7TeE976Rp31BLi9p1UtwETGTB651epcN1BH0Gh/CY8otUFqCtaDZFqVhg6icIkQRSy2xEsUNWFguSZJChaQtDdMDohs68NWrGWxW/dmVEW3f5WGCmSZwoPbOeTTtoSoUiFXn7awi+SoN/0qwhcf2/jNWY/irAqQoW6aOzLxEoQQZU48CQFKRGwUwmvSVROs7JyZC94tx45MAAIhRJljS0KArWSVhK1DuHRSFtEnikjWIX3KfvASkslnGR+bsh78oI5cpsfgB9ngS3MWPADy5WUhdWqUn6FwJM9OzsIVF1ZKbwicQc3UKXpQSecB0aoKYcVKtsyN4EgelZyFS+hIOjliwnJWviEahe2WEyjUbIHy7v1Z9dpw51vZTBbBLG/qAoH2htiETpXKi8BIEkk3xz0zcRKxi6AG9qrvoeCrdrMHT4tLtpeYnXONVGuQ3ZzVgGm7zyEKPHYalr0m6VWTsBOza3Z1AUs7jyTwy6KvB7por0DA+/VKsZjzQZcmdJzVDUssHC+k/XaVgHG2YNLVOeZVb0hpfylLaR6RjmD3mfSogofrQVLNV3zqc7X9KxaX5K04Pg5eqYPndy7afhTFw0zUCV7mp1YTy9w1MzZ6xYddfPrArpWTLEas8iGvjmDL/l7kDxzDKRsaCDjaEzs4Zdtf5XaHdhHTOipIEf3K23s+8+9WJxqK31SSQMyCXjVNVNzBb7LlsDaV9EoIEE5VQgDgemmqhOgBlOHqGtk66+tvlLE8GLA6aHONJZ1o41hlZCWJgGDCqDSndcDKRK8SBoVJV68HK5vpmYt9VDdCxaeFGKXMEkNSGA8jv/XtuyCPFHQ3Dad0ByXn7f2xF4a9+kJsoDcByM4ksxsrXYvKsgq33kVwfd080QpnVH03F7Vowl5VTLoCxIJ98GBTgpx7y/dbIvJ4JS3WLOAuzT5auhfQrvHLIrkntu8Leu3E8IqL45Hv7+kvsz52CcxGtwZMdtAYkmxMv8VEDbGsrSWiSO8vCWcTlN77jKY8Lr+O0bag3pnL2ojrbnVjP+dBceVLLteej+1TlBKLHWCKaUn26N9tg+Xvduv33KMEbb9KZY7tNUxFoeuFRxdeFv0jz7S+sPzLda0Vd+06vse2im1gmfWki5rcWcvFdKFvuowYCGyPNvQhzsfpdprt2Ym/8MitMbwHtVQd1hyMMIBvJ+gIjmsr9xXgxMPpDtykMyhVhUkHvALxC1JubWlpqjq1vL5L92XNGEP99d50WgFMYbzTgOSNMBiOiONjCkVoO8MUgGDg6jEIT62ElK/TiWCU2shFsVj8nQm4bpevlk0FnEuTiHipcMybaTSltKoELRyzdnGqVh5AVbX6xfpLV3QrwCQifioPDtVDHAjUkh9NPSWYYmQJU1r9nYNiCG0xekyACyvbNhS5NF9hYdPn0FmMU89l2g2o9CSmnrxzmwsluEFSqaANq6kKGr+aqiCOV1MV1H79UsHq1C8VoJH6pQQ5Xr9UYNv1axonD7lLTl7iUnkJeS5PsdlezMaQxYc0cqz3t29vfrm7ubhju/Pxxe3bS/JEQJC98lJUp7zzMi9Rocg5SmkL+TdsB9J8878cW2Q8JouePuWhEsBB9/59eehN7JTnAhPuyUb+XCu/BHf29p4FoNhxxKJBL8S+x89HHOpJkCKQgx5odhhdQ5IIBEdcgvpoz1+FsQA3QEQD2wAHTjB3KdpC3NnIlgtw48QLPOJpqSLzp/UXgArEABBFZT3sHr26usJig1dZXMF7TmVhX2HB4Y8CMCjj6ystfBtYOLbFJ9oZNaEs4ThzwKGZNyMWONoxct358K0yiOX4B45iZ+yjDRc0AcqBFCjX1ngHHLc11gHGrsY5oLACQRgkEfPxAixiMVYAx5yNzCqJ2RojgOLOxwWQBBSINCCHmOCj9LiojDpWj1mqzwtmfKNQiSc9WxrFSsMrSKzHxJvdRCsMuEcp/m7uxglxNO8YZnNHx8TR8hPJy7qGUUy2KEhHB4e5Q73CiA4KsO/DFRcWIBEK6oTo/3YvYfHiyJeeJo0jCl/tII4JWmDyeJJQWPmq7MXuci62ugRivraF3N+ylNg+PiLnWSycipqJQxIFLGKMHiMsFE1uobCmz0iaxThJMdFqKE2lZyFiwE+vX/4zMDJslqYEsZB7XgDWXTkksd1kD9ZWiOyglQADG3+4J7BOII9UC4cFV0Cw81uM7sGKBnaknYKjUEK33IjDCYQmFQY7wg0PTveu9KrOKBYL/g5ZM/3ZC56FoerQ0KDDjMCFQ3oNBlWcmd1nhwOLCenTETQUdMiiG0QiG7XFIdkGgvtHKLjIA8uSePZab3GouXhEEkhOejUXzE4KDazcMbA/gIGVB3Kg8UBHIjWowK1S4qB0anV1/RIuW4oTt/mGnRSs2rKRM6TqxKPVzb36DmyemsANUtjdIIBYu9ffAaJdA2K9hmtZACc8KYsuiJwTWLXNAXMHQZp5BG7AnuNG0b0HypR4rL+FQiSnBKMlC02jgF4AiCa2rVoYDnJ2zLBsJwEr1iUeWM4WeKnyJIPdQQDnIWVoML6oBqnyfaCM/o1DtPex8qBviF5vGRcOfr/cCAvsHSNP7PrL5WbS5zAKn9UnVS0DrKQQLyyCDqcQrSkHXOoi1SUGlu/PmQAvPL2ggBBz1xagzF0Vi3BDgp9Iqqdw9I1oKyR9Q1oKC0VOlAesLTwYZ3YLEGpC1oJMcZm2kJje76D5kpIkcyArMXQLL3Sr3Sig7+0TlDxbyPeOocC1TLNAxVry4q1XA7h8Mbk42goDBcwsiBYPPYZIdoIWO8L4aFTuA0ppHVOGba3Dw6VhaAeZMkq5fgzRR9aQi7a48VHsxwRJbz+aglLVptTbNyjtlT1VdW0wm6GA0gMrrw5Z3FVVEEW0GyhC2Imbu+Lm738VxINpMcoFNDuOfGWdfhAtX3GoQAJXZWm7hQJRC4M4VRx3t5GUVhfbQMw5tHw81kaiw1lHuQzFyBW4zGEe5h6sxlEoiOyP75V28NUw1aBcsQHuLmSogole/CqBJHK1nTScauI3cDDjhSEgIMMiDhAgQ4AheQ8OqEFsoZZTd1Zj2SYvfch2yKaKiHhzcRlhbMDpYDtm4Bgr7L/hoB0Os/drS8PBsVty9mEODo4d1CiuDak+BGuhzV8mKYsGxy3fkgZHTmWHGwcuQaEbBSDTpDYqHRrDSVZYfeegpZC5kULmRepH1YVFAleyqiADci7vEgfkKnQ7uRAi1ACUPQQ26E/ys3PEPmEfYhjB4KCo9fcywAIXg0YApMLtAZR+DDDwUuUWP99d4adX12C9ZYN4j5+VdTZ7NRQrRL41oF8w/CZMJ7vrrr5dks0D8yU0O6Kjz8Rz85biP+krQeRmPv764s3XFz/ESfQbdsibDx/yL795CvwwfVN+++PXr19fnAiJ31jW4+PjZer5iF1KFAU0haxPxUOXmI352ZPflMuw+WskyYovPTf/nDmXhd3LFJMsvqxvt73LP/6cZIcD8iP7nRew+OVHx8nfjt2gA/fHr1+Tr1/Db775IV9DYZtM0m9imgA0TfIHL/8H+9cqn/vB6gn8Y55oJVGaBAz3b9/+9euLBAc0nVz6FaWR4uahm6d8rSalv/zHfzZf30VZ4jTfGpGmb/N5V4nxKUrJn9n+j3+kLUTa/iNVdaSqiw8o81kbwOLspmedqF9fsI1MRxxal6nv5FN8bF06SROMLDGpAc6c6v1NE/0/X3z7woliD7t/8Xycvnjz4j9oNtBUxAlNP7d8jL5Xgn1C5JSnXJXYLBpiFQau7GCjxDt6tIusn82/Lfck0i+u6Kd8G0hI6KeLq6vX373c7f756ru8CEjYznted7/M7B+ud9cvX+2+X2z1tMDq7urV9dXV969fX+Upf3f74dP727e3X/7dvvvy67vbj/anzx8/3Xz+cntzR7OC8uoVjtzCX1k2p4jWkzsSOff/yk7Y72nmsa/fsH/YA+z/vWDjmI9xWH18U/2xPwa73cvY2e0ej6j68tvqj6I83Ln37yMnH8IM3h8ZQlU//634hyXEu6KFOS/ef6NZQzPif9+8/WLfffz189s8N374E20cvilz9sevL64uX9JaikMnYoNL+sWvX/5y8f3XF3/6I61/YdWyfEP/S0fr5PmO0sM/1sWK1eckr82HyHdx8k2IAvZzWcrqnwcPNK1b6xn2FK2/9TP9Zu+bLPHo9+yZN9bbN9avdLyaWkEWupH1McTvmIvUeofTexLF1vubd2Vxsw5eEjyiBFu9cmiJtLVWI8EqNLQ0tdi2qrE2ni0b1jSL0wosTqMs+s2pNip9QyJ8dCZN39AIn89fbuy31dwl1cpoaGo8jerplE1bHop11J1WXIPj/PADe/SEQre8O1cnt4ExUV6ay/vA2Div+oLn4mm9BW3EngQ7zQnHsyfALr/qx8t3EDkrJuHQrCjX4ibz1rtrpeuo9cXMV01snvVR5p5d+tWq4xQlrGbKU2bFuZIEhWm+xWMj1lwC46WkfzXtKu3sqNGJdM6XQdYtD3yTMxybgzqrcx03PcKZXTKHE/bNpe9qJNizMza+plzLuZDHPDb6Btk9QxWf3iSkN60qUnV82rUn7InxKVdxTVgOkiXF2ZnqFXClhRmrwLcmLIvOwFAc2yiltNp31uiizTU2UmjYs3RwuxKrriWBGRH/IhtdFOctC1JemecsOSc/FVF1GFHqeL6PSJSsw1XAuih1OibCW5Du2RUYNbaGbOsQnrE8TjlBnl/sQ4iJtw7XMZOi46xVSI6ZHCEZPgTXdrneswLBEXMj5Do7WHVT4xobz9p6RZ9OdFzHddbJ3Qmr41TLkFWrFsNRmyM03QC5ycMK3AaGJjrH8oLgNTrGnqkJUuWN1quw6tuapZU6J8wWFRN2jjtK2IrKmkwnzQtXkAQfVxu5zZkWGbpxL8JbZRTHtTxVSPq3qK1VOibsCg0xOp1q3vquPeKYYiAkAa1OGQlRLM+mrDE47loap3TAxVmtdWhxrI1TS32MY3bsdqW6zrU30ZJ23JK6286BsXli5QBqVX4Dm2KuJy+gdb3jeWpJYntX89Pcx5eXcXjUoCM3bw3sjCRx89zVSnyuBPnsVuKzE+RzvRKfa0E+r1bi86rLZ7rsj+3IGfXDVmdse57YzjPv8nrYeWLwzJ1HzUbhe7RPew8OHv3zzx92u8FDQ8R8LyLnuX4j9ZwS2hPke5m0LMWMbXCvks4q0sdqJYGVa7QKCVafoTUriaCEZLHRmvoUh6IGPvKRjL4twgfN53Rnu5qWPmh5spQirAHH2czO36juhDVVUcVPUM0+S1BgtJ6aobgi4piuqGAoqMgJMqP1lPxE1eQeSOSYnUcdloLKmLvSaFEVQVE9FLUM4WqupIajqKoA0bdSJ/FoBuvZEggmbkBVVGNcxEwyV1lJUFAPNrwFxFItYLEQaLagmqKgpkOaOGa3FDVDQUXH2EnMbs5rhsKKPLOzqCIooceOI8OrUoeloLLTwfTaVDMUVvRkuqAnGT3ezuy2oeQnqgYZPnKtCIrqqe/7MFdRTVFQk09Hg0YrqghK6HnaI7NH4G2SkrrYJiAvNNxZxCMrqhPni2Zmy2s4iqoyvuf1JXte3/Se15freYPU7K6q5CeoJnbN9r6W/ETVJGY3dyU/cTV26h1D5Buvqs1TUF1CDHfBVgQF9aSG+4hSKR9R+pw6Bz3bN8AE1RQFNZk/XpAdLWTmDxcy2fGC+c5JWd/ko6spLAGUoIrgrB4clFutDJXT4Te/eaK928JMQX2KwnsnuF9zvuR91T+fyYLrTe/p8UKHs5enuz8QkSjwNurxCw3s+imrw6SfnIPt1N5GLVGXcEljjq0Tudh2fJSm3sFz6mvktmY/QmtGjWeonFFec7mDw2yjqVY3Oyoec3yLk8ImMG6YzNeA6gKGrTk3TAQ4x56u4EDyrGsu87yTjYYBfc4Jt7sf7OsnSXnR89aMGyaznH0vNaIK1kTmUxmRbCN3RT+VKybW3CBouDk6ERjPFK3SJntuS6WUptVhIlJn2T8EPwUmMO/zEazDBjBvmMxyfk4d5Pt6YlrJsm5xEWt7TCBdEZmtx/OTmTJa/PRsphPiYe6MAq+pmItWwQ4XbpOypX6rw6eujVySnCnnYKQ+eNE+oY02AE4pnGI6K3PkXTvd6NyFZFa2uEpKNV3eokJ6FuVzYdE8k1I5XiDHfFrzTiehltegfK/mMFySsvXUcF1CkjzTNXEIChVfkWlHeYwZdORRHY3O76HdtEnoqqvahD6/+UJfvpFv1jVXUEVPWE+Mk/weLOQbrKpLUme73SkXm7YCvQQpm7Y+P7lya66g8T3wY/G5ttqJLCRndB/yfC00V1SX5AJtNnmOt9oZKqmwobqstckr6DDSwHSDY+NDcr17Om51pn4kjQot/danS3ZZKhV4EsnUyiA2jjczvUpV/HI1oA09jGPDeNAxXBOTcOvZXYtQb4DQ57jCEKE2aUR7lqdJrw9qEwQrZfl9mEkWE9H5wliidm9B6gV44aa9E6ReaodUnP3gJSTburMcJEWeAYh5krlMpSKQdMvcwJSJysd4LquMQm2UZ37KVD42oaQRyPltF9LmdE7zhWuFyujSMB1dhbZxkpYs6pRssRIoJ91422ZKaZGTUJRggpIjJnZK3K2dL6PKhiQlFNJ3fG9fX6ZnpMABRwl9mbklMhspj5Ajxromb9s1VUlQ9dUtVgIOciNFeHIqBg2RSVp45Ba3IWYKG3CUbUPMlJWJ5pZnsBwON7DhWjcYOsygrYu5be/S5VL1MUOG88W9FzbefaY/0VlkgpmpYtO38UrHWAtUj8HtEvl2ZvMUTzCVzuNq5GigzCmq0rm5bWsnlI1iXVIvUeIo8s0tqTNsF6k9E5kLa+PxPBrZhqjOqYvBVbgchQHU4DIpjRfXIirfl9K2G4fVFSkkiTZ2nnP1ipFeVt7jJGIyh6NPwfHneApXyHR6k+032nA/kqwVtX5/N6S8PDw6vyGZTy6jyl+dUL2C2CYLfgp6OE+KM6DJUZxtvlpLOdRdV01Ha18VbxQKpa24arhjbtiTxSWjc03U0jIyf8Cen7D9qye3H+p2GOWlrDq8M852PjBD/10cvDoXmSXV5a14fh+U7UdRLF8kTEukRssgoZYVBBfvs43XZaRUNoTltZpwjENO7NQRI84wpPtyTFUgstGRckG9E5zVxiQLO9pujTIo5crOd8BvfkbIqz6GC2tYCkwGDc8yDkGwoRMbjSFvONJZNrCmSAYcpC2Z1OPrNisB90f1eDnLMVNLi5yIt6P/2qZlvKuJz04wn+gM1MFpaiNn+9UfXlYN+Wmd49Ul3Yj8rWZ7bVYL6p+RWpSLqnGqhvwWbk3NQ1qwCHkschEi3t7zKSMwzyIX3ZCazyfXivTBJa7du1hZNqdpGEupKk5Ql6/IPK18xcRaJiZ2vv7Bu1Sbe65hBoAN3tYVsuLRBKxpM5tvsls3gLMZdB532lhJHYrS2mjBY3dPmq2uISmtr7ha02x5NUdpdYbXti5HgalK99WtG/CeMB49nQP6VqtlSkLUwQfbzKTy1TApfWpgrpXMxT4ajnsXdawF1rbVvOBQVfGG0XyTVTxroyR4+C6wj7SfujNNSI+czkpdptymtaBMgrIyN4yWFv75KH9vP9zd3k3H+HsbJcN75IWvm+echt02jG+u2GKi6tDxQ1ozlad44YFS3Ww2MyqjxWpGBfk936GEnzaafXIkdCkJ5cJxq7txRnPgOHYZTpd9HtA1uL42h32b0Qx7tjuGtc3fG8O+w0hfg4kDN3mYbjDdAA2fWTLCKIC2GV7kOq2CQd4nN2Rge+Fuouyq67HmHWgFoW2v/eqkUt5t1wKsIb+lwRTKpDdDYUMGbEg+sq1LfhiH2YUTW6ZTK656zQUsmVi8sTpUAUDz0sHbspXpEMkbmwE1bSP/rqUNi043EVgJGlADK0nhQ3ANUN0YDLuOFmX+pknHeOQp1ic0M4hhjxvDW5CvfcQhTra6HYqX3i1CIvw3vO+bx37ibu8h981cnzzmYiGvq0ftg4/Sk1HsG0oiGraLbsqjLxjLNH822v+GHYMayIaPCPsYHQ2qrhUbEeYkQVtdv8ijXtMR4Z4Rb9s5TZd7TUdbXLR2110egLB9L7zfahWtlQpsQDpNT2ScYYoKQb5lx2gK64aOXH9nDP8OJeH+zhj6gjHn2/2LMdwbPsL9nTHcKzbifYYx1Gs6C6NR5wGXhLqNLeNHtZQXNKweJZ2uaN/bT7uiZ2/nYzcmb7cRJ1eQl5g2j8nr1th2vSAzgG7JYo4sNoIsFiS7YRzOLt/RmJt9ytvdbdIhPHaHSZ+uh1wT6lpFY46u7wbIALoVjTm6QWpC4pYs5sjGyWaddYtsyWKO7HY7bTtsx3bT9ukWm7cNINwQmaO84Y7RDuORXaFicfZFRxsbDdWYzHxtrsVjdrRx8mID+FY0RAZHBrAN+KFEhmTLwxdmcG6RmaTOtqeakdZdJnPpXV5/vX1aN0TmKO+3uiK911rwvZ/98lwEbtmeb0NktmNHwSELTWiRW0zmSG+687JDemK35bBwJJutRnSKRsLflsKhu/Vic4/21FIzb969PWss1i5vGdm9y3c0ijufsjm994CPkONge95jl0hyHQfb061oCDkOtqdb0RBxHGzPtmQhQNacetclI+Lz2J5zyULI57E924qGgM/DOWy2CtIi3BARdNMYQbkkIkbZoIHRkJCYp2l75iNnOxethSXI9aLptbAEeb49XDEbPBf72ZETemvw3IFKYGucQqE+qoe3cfDlqWNVCWAVCq2Kk9XjJxLXo35+k2IkoUf22EW3KKALJwrLOd7YkZTummx1TS734WE65hoYUTtGtpMlD1vdNc1P0m4CWLU6a5w6t/SMpXcvQRhQY664c9ikGtNLjjG6sxWI+6K52T5GV0gnKxjFzeRnoZNHV1jn+UiUUTeo62dUdIW4y6fAGRVqIe7Lu8gWdifQK/dK95mEHQCY1PZP8bQEdEgWsiGGQUVMKS2gihvxZMsX8QwtUMSzeEwliwx9ycwywpOnHEhP9BQxP8mMSKnmYoSK0nzQnvzl4LCR02RSQEVLUESxBmzjJInYlReuITOfniY+S0GJeS9roqqamKCQA0YkS8zU0uY2I8e0mi9Y7U2s8xIV/gxq+/KqbmY9l6rkxtbw2eotfIseiZyI56jtPbn3eSHMRtpE+rARiVXJsyghq0dudgRprpJpGcKhuDHG37/cXb1+JZ6xzTtmpUrDy+JTFcvtM5AnpE20CDwG+0wgnFSVpPnjZqVMTskaEBTLbmP1zIkRzd/fH9GDRLOdP25WeuSUrAFBsfw1Vs+cGOFb/jwXPyL/XjyLqzfMSpWKlcWjKZbXhgsTUKXm4Tl5vJseeUuwMmu1TzJrtYyDncbY8Q5bbf/oD5Ypo2Jltl6ffbJG6fIKGq+onYlOcZHjzY1KkUQZiY5YYLcIVZBzTbCPUSrQX1UvFCfJ7f0x2O1exs5u93hEeYhZZECelPKtnjpLhPxsk1eBBJGb+diuNx8wgMrSWaTCnADwG2Xm90u5LFH618tw4k3CxMnf7pB2oTMPpVhFlh89qg0YTH67zeVtwWUc+dEt5mClKcaJF59wgvo+FtkDopRtce/KRjOWRkiVeC06M0cC80e3PMnBJy94pKN8eruCy2cvdDyifHazzeV86iK7zJtHbRxmgWn8G1IiKrbcgM6XILgTvXl6s93oo/xFtqV3nt52a/qUjvE96kKX4s2FMuq2d5uMNlrqy8FGl5FwC2wQe6HINq0mzyDqIrFNujXNIPJjkUMWDdBS7FBZg+teh3fEsqNcUYjD+fjydFqzxy7xUzvN4jhKeLv9REO6DfLEq8GR49CJUoK2vDe0SDurnTzWUH8V/22KvcCOrublKAi9OMEpNXd+ynvkhYTHKTrT/OYxV/B4C165XBLa6v45wWSqLl5vyM4WBid5jklEE9RG+BzkDfjOKqxQHGejTkdKX4+tuLoAbXbF6xJ5JV1hfdhxacWn/24UaHiRyi5pibp4PIuyOuArsouatd/Fi2egcMBXuHM9I4l9wgpbgLge2/He1OxBRzmrbpGdzX3aJ9loqxt6pIS1mM63S05wJqpaTOdV0S7oXGS1qM63QCd0dSa62lRFdO1ef3c+ylpkRbS9vtqdj7YW2Vltx7NpPY4SrUd3ZGC+tgFf2ZHMOUjsExbNxQfkZ1vtx1+Siw1f4G1fJT53ywLvcTHvSZEtJAmPho2HG62doXDFVLiKFBgbnqOWVdgjLCu0jHl6TlIbykJiU1zFG7VdHOPQxaHjGecg40ieIC7aGnoktbe7R0tc7ICshIOlOCYfMJe50SrHGAsV4ublshKcRxM8SltSNElQmMaUbkgqpNNmF5UtS4AJCeqJ4eRLoWeeHI0I9QRBGLlnnhyVBPXEMG89QTYtRJcYZoHu8TPtTOnfxYLjeafKUAxMAp1Lj7pAjHoCpd4xzM9Wn3nadHToWCfo7nVOkch5IS8kOAmRTwlnKcGunZIo2ewqZZG0ZlN5+tGaYi5weohl1/mKn2MvkAB5/AjzldY0VQJ28uezRmsfpaw0BTde8gRxWUfLtqFCFubzdJQgkSm50WrHGCtMyY3WO0lbYWjEbiBiQ9AzKNwCAhQSYsOQRuqJMBX5SGklAlehLMGWIewG06hheM2q8mt2eYq4bZs3Ngx9Ly9PKg5+6zUDPVdTKqV8VO0XKXISxc9nI7TFV1KpcY7ZKZkSLtj2awa7kabULnIY9QFOKHR9z7DVhznVbdKSms10+EwJnnHtTKpFhOCUnFex7nEWnZJWrwfI8/fRk9Fyxwjr3+DbGsGYNK5tEqjcTNPlKVnqXXzwQsNG7hMK23wllZo3Q5nSOTElmR85n4vI8RuXptstIz1KfaGjjCVztHYv097cbMWTrGXzuAIwWvEoY9m54Ak792X0K6MFT5GW1XxmahfrLCbOZ6Ozprtwnn8uQlt8l8zzz0VmRVZtnn8uaoe0Veb556S6TXrxPP9cBHcYK8zzz0Vvj/PSeb7JcscIgx8OqRaB4JZkCjw73eju0bH1r0po5Tfq0NTuPvGMPHNVp0l3QVBy8ZOl4TnIKnlqOF9VxvKGrkpeH9nOQ+eaF9WlR7M5rDNBX6iAVS8YvBV1RPoIc7HdQl1MsyqXaGYLNyK8lDoPxSPMNfTRMeVmR+kgQjDnceEOqcY0K7VbxFo70VpUBTfclW/Ye8ouwOSsZHZJ6w9wPvyiF6c/7t4cIXJ3aO8Z5tyei4pIzZTXyM0FCW+eXDVXqdnqdjWmx2poWF1G8xdDmqdgQGpZiHeG4Ue8OJWDHKSPrdqb88RTDlaLy0zGVU9unWVt1sLFzRTiXTr64urv/QyTKCKn6ZZp5Obj/nUOiBA6J08ePAfbLs7/44Wsic/9EHb0gJPEc3lXkwyuNxCEWj2z6gSrsk2UqSWpCizP5zou7uWVy4qJyO0L+yOKV75GvLn0scq70l9Wc5kJ4OyZxNqTpW0nJEpt5KJ4Cx/mjAweuXlZpLr3x8WHlVe4J/QMWIkIQS6t9MRLN1rfnJTD5SaYOyHOTwmYJ4rLTUSU+0w/e07eirt784SN8hMR5+8cFJunqU9LREqMHhOjq9U4QSF5OPEil+az0RInSYrITJ9DxzxdPVZCDbzj4JiWZC8l5unhkxORhZ/K7Vr7KHS98GhiizjJUURk2ZTS/twgVV1SIjJOUUpMHABymc1dpsJqIUEbbX4bn0oMWQkI8X3jVHQoCUgwZl7UIiNGO/c102K393xqxSgRQ2pCPY0pWeHJ5UVRcfKojEbQH3ISELHBYYEp/qOnATjUy7AN5pBvEZK/xm1/FPNWCl0sy7wUBRztb/fZsbhid9319WFKVZzqVdYxkhpvoO0b3br01GnSuJf69Jalhu/t51eU95nnuyLBnY4Of+mZ43JPCH66CK6vR54XL/ijb0xdFc7NdpoWlZV178WeyG92P3ae/BZNW6tJtuaJ1m3Zbfb8SEsTBUPo56nARhAXxAPdZDni39u4YavbsxFuy3yP5ojiclvuezRH2Cg/ad+jOZr6tBR8j+aIGieo6Hs0SOIkSVnfozm6eqwW+h7N0cMnp+Z7NEfdJMclTjtzpHGYyc3yjZAy5LRkrpkjzE01fYE9qaJHR/bEIYlvRDqW6i3fb5K0Q07knFXrFZug9N7HZOWt+5LCOiz1xxQxyUvcShdBh/FEjjvI9/cUbXOnGU/VkKGEMt8L7330vPYRbgllHYZLlBmx8WZe3uhOnAmNMYVktdtUcS1+y1sfeH/V03G3E/VUzfud+l6npsBu7naqs6VxOjHtbS9Th+2Ym8l4LxK/jAiVDzlf5mCzKc6HmGLlbmwINvK4fNGrx++bFz2uk7NMrLpgtp2dbeYT3s6+4BLy/PS2iEPXOm4pzXewaix5lYli47jje+z0nNm5UlHu5wtXh1yZbEGwPfQG9AXKSdHoWJAU5yx/lSracjDpraSFQ6TlzkpJZnh30WLLa0K5alZpU9PnlOBAb34VNszOoIZnP38a9tozpLVelWb7BBE6nFihKvHMnkGd4tHmVq5JfStkajKeK5CZmGDT84ui8/OnoK49K07caAXQOUGtsJGGh9Od2RlCiXLzoydAf7Y4mkf1hSrH8CEcJcjPDmed8dsaQ4Fc0DmMB/hjgR791XxNHDcMm9RwzxKPvkPfEN7ctiB3j8VGalN7oU6CWSwtuhvV2uzP1ofI848M/e6XT/lzW+YRm6i2ucyuBUufsx9Ed+n9Tk5e4toxSsjzTDCGIlCYF8/5ZmkxKp5NIwEnrdAC9B69unqFN9mslcfHaCWSVaeD1Raar9gOac4uANFXrq/OQFeHpOA9g26AmljjpmrjUxVUSNHKIw9my+vwnF+UfLLXDmQoI6mhJ6Jk799vcYOZpKAuSxFd7slGvrlNRoehiB7sOLaTJQ9mF7wuS1Fd9/j5iEPT82vIVEyfmyLzpbVIiqha/YY8SUHil+I92QEiRmup+AlpwYETxEarqRmK6ln5yskFekQvmXyiE0sv8IhneCveZSmiK1n5MkVJQYnotYlPxV3SBksholrYZOsKb7FFVXZK2GEppOv6HGRdy6pqTY1N1tWlKTeDN1hXh+SSGbyp2vhUZxXGyHXXvjtHRlaLn+Q811RFA5YCuhJ8XHdPtJygip7SgQw/4wan7dfIKIjpxyQ/4hWyVXwzE6YUZI3wlfCsrR3/Slphn6m01/A81Elc8Vq45kyW1VCUa1XtMoKD4dq4hCX8iYbLa1gKaQqQ8YIKipIeUsNFdZku8JKegb4uWzlPqfHyWkSFlCVJlJhfKmuWwh5gwxWJX5lKn320nYPxRa9hKezZNlxRxVHCu226opqlhIf7DDSJXrHc8R8brqvLVNTTbbioRNwrQs5ADhnVM+FDaMl8f/v25pe7m4s7dp8Zvrh9e0meiIGSR3guvXFm4EkJ9tglfiqwPS1BSX+z2yBVnShMCQqJTbwAb7tgUgqzSubWgNrMJVPklGCU+xKNktGhNSOhurTPLAVtVoICbAZqpoqa2pwUOjkwUEWL1dxVcb53DFe/zHRWQYfWjIR9aAfZxksyff4NpznyKMXfvTJkYWmgYkhuTg7NtiwoNs2bJaVLTEyGobkyJCcmJ4hcI5WUvIRF2Al6NFVIxU1KDM3LB5RStiar6pCck+dHTu17N7QWjVGckeacMHuvGNabsNNhMCLmE5yTVSTEY4I29rkM5HSJzckwYGFqOEUZX3san2bZzJxpQnj85EQZ2RaMc5wTRzbeYTJQQkY2k3RoF1dUmJkXQ24zYrAT14/byDdsIsNjJyTIxAFBn9mckJAkUfxsx5FvWCHrM5sR4gfRytEoZxXUlGaoBxQg3Xjlv8+94TRP3rwBSYvUHP04NWKnzEBBh5eAiHy12DwNNS0BCcy9uvV2UJ6GhpeACJIgx7AuoUNrzlmKXDbpMktAi9Qc/XtDh0w9YvMyzGtUW6Rm6T8mHjGsFrRICS4YmFqUePRmJCX5Bilin7Af4623PvUFccgJyDEzc/rMZoSkqV9eRmhkznDpCUgqY9cap6XhJSIi92qlGW00UkNL2yRNAYmBlzrmKapYCQigr15dGzoT5/MTFnWPnw1sDbrcZsQ8vX75z4bWnAE1gTFB5a8vGhHjdhMM6AktJ5ilYyqmzOhaiIEKamLCxcosFV1e4nUD0amyqUpqchJV3cAqwqUnLsllTIvyyQZ0dhix692I5xircpKxuPDUj4gdoBAdcWBy+83hKSGSRAl90VxxDT9xUdgxrI0fchMXczi4G0c3mlBTkROXs33gqQk541GnxuQEyNx2sOQmLiZG9+a2BBU5cTlJioxVU3KTaKjNzZlUMl/yYZVRkzsOOekxn6mCpqKRjEoybqsvh5ycHCMXbcc5Lh6fGyuQwxNiEnImcruM5YaypkosuUkOZU1VU5GTHMqaKmf86PyYHDOd4iMEJWSZtstryE1uumGqmJKb5HTDVDUVOYnpBqKEAwO3eI9zlJtLGStKaN9hd8JiqpZUstD1nX/G6hrylHdSGiuu4Sd02F8iRqJgCIBB6m0epa5KrioORPVZNDYdSjxDWpyBgpLZvIQ0vDJUQslMSIJBW/N4OiY26XGPZZuppOE2LyM/wWmojJrbvIzWWU1DxfQYzktiF9LRacohMlRQh998MFf6H983tRlus5uX4hhaYUpi8wJOiP5v99JQFS12glLiyN84aNq0mIqfgJz8aLZBh8aHgroM5yUZ3ChLNMeOMd6SgYhRXwknJjoiF7vLJ0OFdPgJyGFl0Ebub1lKbB8fkfNcbRszVN8k4WWCD0kUmHOAU0hym7KkaDZPzl8voM5BNIfyAtFpxhZ+MDkz4RzakuLT1BAH6LTYkqakOLYP/BzUVTxF5ZneHkk0Pq3YkaYq6lKcF0US2032po4vW+xmpeSnw8zUUVMTEGGod9UV9K66J0PnwyWxWQHYMWUrQV9BxUxEgqltbk1NQMRv5izjDmX8Nr6MOwzQY6oIsVD0ZfgbQ0U05OaFmBOYZCBjPDhJT8TRVIfjUdDheLp3N76cbExBxWxeQoAcg4dNHXqzYvzA0CFHSWxWQPm80Z7SIcd5WYZsZR9IGdnFPqD/2lT+r8UE4CBKnu09NY8TG/l+ZKjPd4TorMAQEzuNnHtsyj7GvrAewXlBXkrse0OCPQ/ENORmhUSeoXW/JDYrIMaGDlJKYvMCDIk7NuA/EnpsQN9Jr3amSqi4CckwtBepqQmJ+IO5Iv4gJqK6r8VMHS12wlIM9uMOKIqLYjYMF1VRnBcV+c9X1y9NbQFa7OalUH6IYBs5Dk4NHW4NOc7Lqq4OMlNQi92slMSjYwP36jtDN0J16M2LMdX/O3qioh987IQM3eFcMRORsHv9nbEiSm4iMq6NFXEtKuG1qaPhhtu8DFN3P4jud8hjRCLnZOioq0NPTEwr4KXBmnosxaRF0b1nckbV/ITkEI+5kcyV0/CbldNc/mmkmg69eTFeYK6SmtusjAfK1TMlBkhfR4vcrBBzN6EJbzvL46k6iaF9ZZudqBRD2602O0EpqaHL7212nNPD45eJd87Q0vnm/PlZEzelU+KWzN7zMqBVsR8UZSxiS4j2PjZs1aKRNcZVUmq5Y9TFMQ5dHDqeacO+oeIRysuE3+NnathLbPIcn430Iell4tPnMAqfTdssMSq7Tfdsz5cydbJnS4vEYG8RL2SBz+IoNW+C1so3PlVZoXFCh6uE8jdfaJeqrFBWn2mny3zVxg25OWKHdEUFF0fgjBXY0BMXZN4GrY4g8XOsnVB8JgWA5OgasJSWFxL8RNJzaEunKS8VfiZNzjztpQlwBp3LNGVR4fTVxLCls5bGmp2oHBMPiLb0yBwELYPnGbkPpSVJaitKHZqtLL3GquowFJbl/W5we1GzE5ZDkswxdzjW0BMVZPYkXnq2/oD8zGA9DT1hByP3a86Xg696X/Q/dna5Iy/UEv+/ArZ4VlGs5x6VEnfUpo7CUeJybbKlsABfBq4Guy1sru3Ut4+IENp2Jw+eQxtwnP+HOVKSIB8R2hFt0RPP1XQBhJz9WkMxDcuS/JFKzDt8QJlPKE0f7bHf+WYfocR9m89Gvb3n01r6Yx7f5jL16MPpZf77ZRiF+M3LS/r/6SustvbfCJzsEtGOGx+S693l/rhj/wS73cvY2e0ej4i+RqLId060YE9YS9NL9tglk8Xg6ncuj2F26bjkzdXucnd5dUlbkd3V7uVriksblSlE9/4yJcih/3r07zdV83NpX3z36urld9evX1+31h1+wE954+N+QuT0Ry9AR1yWFdsLji8v4/D4g9V5RuzNq8Vv7ha/eb34zVfCb4417nESkciJfGtPG26ai+REq7rHivWeXD7RP5XQB11HFbg7ZnFgiw9p5Fjvb9/e/HJ3c3GHnSzBF7dvL8kTGbPs4tRJvJhVnD/+YLU/VR1Bp3Ll3/7AhP6GHZJ/evG3/x8Pmqjb=END_SIMPLICITY_STUDIO_METADATA