####################################################################
# Automatically-generated file. Do not edit!                       #
####################################################################

set(SDK_PATH "C:/Users/mundo/.silabs/slt/installs/conan/p/simpleb526998f4a4d/p")
set(COPIED_SDK_PATH "simplicity_sdk_2025.6.2")
set(PKG_PATH "C:/Users/mundo/.silabs/slt/installs")

add_library(slc OBJECT
    "../${COPIED_SDK_PATH}/app/common/util/app_log/app_log.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_assert.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_core_cortexm.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_slist.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_string.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_syscalls.c"
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/BGM22/Source/startup_bgm22.c"
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/BGM22/Source/system_bgm22.c"
    "../${COPIED_SDK_PATH}/platform/driver/gpio/src/sl_gpio.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/dmadrv/src/dmadrv.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/gpiointerrupt/src/gpiointerrupt.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_cache.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_hal_flash.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_object.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_page.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_utils.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_burtc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_cmu.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_emu.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_eusart.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_gpio.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_iadc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_ldma.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_msc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_prs.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_rtcc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_system.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_timer.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_eusart.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_gpio.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_prs.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_system.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/fem_util/sl_fem_util.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/pa_conversions_efr32.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_power_manager_init/sl_rail_util_power_manager_init.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_pti/sl_rail_util_pti.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_attestation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_entropy.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_hash.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_handling.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_signature.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_util.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sli_se_manager_mailbox.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/cryptoacc_aes.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/cryptoacc_gcm.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ccm.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_cmac.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ecdsa_ecdh.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_protocol_crypto/src/sli_protocol_crypto_radioaes.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_protocol_crypto/src/sli_radioaes_management.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/cryptoacc_management.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sl_psa_its_nvm3.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_driver_trng.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_aead.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_hash.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_key_management.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_mac.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_signature.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_trng.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sli_crypto/src/sl_crypto_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager_init.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager_init_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_init/src/sl_device_init_dcdc_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/clocks/sl_device_clock_efr32xg22.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/devices/sl_device_peripheral_hal_efr32xg22.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_clock.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_gpio.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_peripheral.c"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/src/sl_interrupt_manager_cortexm.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream_eusart.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream_retarget_stdio.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream_stdlib_config.c"
    "../${COPIED_SDK_PATH}/platform/service/iostream/src/sl_iostream_uart.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/profiler/src/sli_memory_profiler_stubs.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_dynamic_reservation.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_pool.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_pool_common.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_region.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_retarget.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sli_memory_manager_common.c"
    "../${COPIED_SDK_PATH}/platform/service/mpu/src/sl_mpu_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/common/sl_power_manager_common.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/common/sl_power_manager_em4.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/sleep_loop/sl_power_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/sleep_loop/sl_power_manager_debug.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/sleep_loop/sl_power_manager_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/sl_system_compatibility/src/sl_system_compatibility.c"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/src/sl_main_init.c"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/src/sl_main_init_memory.c"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/src/sl_main_process_action.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c"
    "../${COPIED_SDK_PATH}/platform/service/udelay/src/sl_udelay.c"
    "../${COPIED_SDK_PATH}/platform/service/udelay/src/sl_udelay_armv6m_gcc.S"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgcommon/src/sli_bgcommon_debug_efr32.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgstack/ll/src/sl_btctrl_init.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgstack/ll/src/sl_btctrl_init_tasklets.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sl_bt_stack_init.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_accept_list_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_advertiser_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_connection_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_dynamic_gattdb_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_external_bondingdb_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_host_adaptation.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_l2cap_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_pawr_advertiser_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_periodic_advertiser_config.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/src/sli_bt_sync_config.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/ba414ep_config.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/ba431_config.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/cryptodma_internal.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/cryptolib_types.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_aes.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_blk_cipher.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_dh_alg.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_ecc_curves.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_ecc_keygen_alg.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_ecdsa_alg.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_hash.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_math.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_memcmp.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_memcpy.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_primitives.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_rng.c"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src/sx_trng.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/cipher.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/cipher_wrap.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/constant_time.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/platform.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/platform_util.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_aead.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_cipher.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_client.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_driver_wrappers_no_static.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ecp.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ffdh.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_hash.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_mac.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_pake.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_rsa.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_se.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_slot_management.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_storage.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_util.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/threading.c"
    "../app.c"
    "../autogen/gatt_db.c"
    "../autogen/sl_bluetooth.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
    "../autogen/sl_iostream_init_eusart_instances.c"
    "../autogen/sl_power_manager_handler.c"
    "../main.c"
    "../sl_gatt_service_device_information_override.c"
)

target_include_directories(slc PUBLIC
   "../config"
   "../config/btconf"
   "../autogen"
   "../."
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/BGM22/Include"
    "../${COPIED_SDK_PATH}/app/common/util/app_assert"
    "../${COPIED_SDK_PATH}/app/common/util/app_log"
    "../${COPIED_SDK_PATH}/platform/common/inc"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/inc"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgcommon/inc"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/bgstack/ll/inc"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src"
    "../${COPIED_SDK_PATH}/platform/CMSIS/Core/Include"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/device_init/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/dmadrv/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/dmadrv/inc/s2_signals"
    "../${COPIED_SDK_PATH}/platform/emdrv/common/inc"
    "../${COPIED_SDK_PATH}/platform/emlib/inc"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/fem_util"
    "../${COPIED_SDK_PATH}/app/bluetooth/common/gatt_service_device_information_override"
    "../${COPIED_SDK_PATH}/platform/driver/gpio/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/gpiointerrupt/inc"
    "../${COPIED_SDK_PATH}/platform/peripheral/inc"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/src"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/inc/arm"
    "../${COPIED_SDK_PATH}/platform/service/iostream/inc"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/include"
    "../${COPIED_SDK_PATH}/util/third_party/crypto_ip/libcryptosoc/src"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/inc"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/include"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/profiler/inc"
    "../${COPIED_SDK_PATH}/platform/service/mpu/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/config"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/inc"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/inc"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/common"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/ble"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/ieee802154"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/wmbus"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/zwave"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/chip/efr32/efr32xg2x"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/sidewalk"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/efr32xg22"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_power_manager_init"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_pti"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/inc"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/src"
    "../${COPIED_SDK_PATH}/platform/service/sl_main/sl_system_compatibility/inc"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/inc"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sli_crypto/inc"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_protocol_crypto/src"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sli_psec_osal/inc"
    "../${COPIED_SDK_PATH}/platform/service/udelay/inc"
)

target_compile_definitions(slc PUBLIC
    "BGM220PC22WGA=1"
    "SL_CODE_COMPONENT_SYSTEM=system"
    "SL_CODE_COMPONENT_CLOCK_MANAGER=clock_manager"
    "SL_COMPONENT_CATALOG_PRESENT=1"
    "SL_CODE_COMPONENT_DEVICE_PERIPHERAL=device_peripheral"
    "SL_CODE_COMPONENT_DMADRV=dmadrv"
    "SL_CODE_COMPONENT_GPIO=gpio"
    "SL_CODE_COMPONENT_HAL_COMMON=hal_common"
    "SL_CODE_COMPONENT_HAL_GPIO=hal_gpio"
    "SL_CODE_COMPONENT_INTERRUPT_MANAGER=interrupt_manager"
    "CMSIS_NVIC_VIRTUAL=1"
    "CMSIS_NVIC_VIRTUAL_HEADER_FILE=\"cmsis_nvic_virtual.h\""
    "MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>"
    "SL_CODE_COMPONENT_POWER_MANAGER=power_manager"
    "MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>"
    "SL_RAIL_LIB_MULTIPROTOCOL_SUPPORT=0"
    "SL_RAIL_UTIL_PA_CONFIG_HEADER=<sl_rail_util_pa_config.h>"
    "SL_CODE_COMPONENT_SE_MANAGER=se_manager"
    "SL_CODE_COMPONENT_CORE=core"
    "SL_RAIL_3_API=1"
    "SL_CODE_COMPONENT_SLEEPTIMER=sleeptimer"
    "SL_CODE_COMPONENT_SLI_CRYPTO=sli_crypto"
    "SLI_RADIOAES_REQUIRES_MASKING=1"
    "SL_CODE_COMPONENT_SLI_PROTOCOL_CRYPTO=sli_protocol_crypto"
    "SL_CODE_COMPONENT_PSEC_OSAL=psec_osal"
)

target_link_libraries(slc PUBLIC
    "-Wl,--start-group"
    "gcc"
    "c"
    "m"
    "nosys"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/bgcommon/lib/build/gcc/cortex-m33/bgcommon/release/libbgcommon.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/bgstack/ll/build/gcc/xg22/release/liblinklayer.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/bgstack/release/libbondingdb.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/ble_bgapi/release/libble_bgapi_gatt_client.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/ble_bgapi/release/libble_bgapi_gatt_server.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/bgapi_protocol/api3/release/libbgapi_core.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/accept_list/release/libble_host_accept_list_stub.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/bgstack/release/libble_host.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/ble_bgapi/release/libble_bgapi.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/ble_system/release/libble_system.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/connection_subrating/release/libble_host_connection_subrating_stub.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/core/release/libble_host_core.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/hal/release/libble_host_hal_series2.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/hci/release/libble_host_hci.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/build/gcc/cortex-m33/ble_host/system/release/libble_host_system.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/platform/radio/rail_lib/autogen/librail_release/librail_config_bgm220pc22wga_gcc.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/platform/radio/rail_lib/autogen/librail_release/librail_module_efr32xg22_gcc_release.a"
    "-Wl,--end-group"
)
target_compile_options(slc PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:C>:-mcmse>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:C>:-fno-lto>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-mcmse>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-lto>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=hard>
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-x assembler-with-cpp>"
)

set(post_build_command )
set_property(TARGET slc PROPERTY C_STANDARD 17)
set_property(TARGET slc PROPERTY CXX_STANDARD 17)
set_property(TARGET slc PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc INTERFACE
    -mcpu=cortex-m33
    -mthumb
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    "SHELL:-Xlinker -Map=$<TARGET_FILE_DIR:Gruffalo_Dimmer>/Gruffalo_Dimmer.map"
    "SHELL:-Wl,--wrap=_free_r -Wl,--wrap=_malloc_r -Wl,--wrap=_calloc_r -Wl,--wrap=_realloc_r"
    -Wl,--wrap=sl_system_init,--wrap=sl_system_process_action
    -fno-lto
    -Wl,--gc-sections
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztvQuT3DaW5/tVHIqJG/twFVVZkuzW2t3hLlV7aleydFVyz06MJhhIEplJF1+Xj3q4o7/7BUCCT5AEiAOS1dO7PXJlJvk/v4M3QPDgby9ubz58en9zdfPl3+3bL7++u/lof3r34fbF2xc//Okx8L9+/eYeJ6kXhT9+fXFx/vLrC/INDp3I9cIj+erXL385+/7riz/98evXrwn5v/CHOIl+w05GLgtRgMkluXMeRG7u4/MUZ3l8jmLk3Nn77CoKD97x/OckPxyQH9nvvCDAyfnRcZgRohPjJHu6dch/iQzXfVGZIheR//1wiHwXJ7U9lGfREYe9C/nlno/ri48oy2x3f17Y3Oeen3nU1SzJMfuKKOEEZditvrRUdE/zdX+wCs+6X3uh4+cu/oSyE/mYJx5RSLPc9aK3VplIVpUGtegP/Mfqm29M5XDumMpbh+kOZm3n6n1Grx+4ejjbCiM5yR2SKOdcRJhn5EvfC+/YN8TRdLh4iDNTCIHi2EZpShKoRClLkY75vgU/OpqST3177+c4i6LsRG2EJG9JUi5lzpANx49IuxWgEB1xYkep4/k+yqJkMZNZgrFBY16UEgsosHGeIlL2vDA1VgCJuQR5vp1n5J848wzaiaMHknY8DQ3ZCe+DS9vFB5T7xtIsTpHtJE9xFhlMLRffew4mee+R7stxHYOmAhxEyZPpnHED5Cb3JpueI4pNll/S/2SJb95A6pww7cMTO068KPGyp+XyPsHHpfoH5JLRTual5kocS1L7RFpTYgzFGTLc9zUa0lZTx+rwImaRyS4wSkx2egccFE6YM5H6GJMuLjBa4oI9djM/XcBC2UPoG9KZ3/B5QE9T/maLD+xXmiJ9wUFMxo945Qlws3EEnwW3xDWmwkLxz1+u7asoiKMQh1kKLs/anlLddlBGcuhowgi+pwZOKHRJ32vegIEsriYOhQ0jWdGzYdIP1nPS6Q8KHcPuMFONCVdh0bhzPYvwPnqdPskum6UlTGUJCtNDlAQGjXZGW+bql2ezmZ/5RKRmSkXT5tjYIKHfnfvuf8Ul0vKCDzgjc4QMrb0KTrK4tOTh9L9iflRd/S37CJ4dXkBaCbnMIK20G2DbC44vz+PwKBxLV6lIb31rXb21fiUz2tQK8tCNrI8hfpd499h6h9O7LIqt99fvSk+sNHEsBmP17EjV3Pqui4XoLmbR7Rai282iu1yI7nIW3auF6F6J6YZakW6dSj0yg/IculKVunf27uXu9fmb853s0yE6+6JjhInnQ5273rHp7+g9A3feegQ2Ct+jfSpx+4DIn3/+sBvyUJ4kyhMpH0Ra7WHDU5rhwN4fg92uHPoMFhne4JO8snjaW0VyWo20sZiLVsFodQ2IS7Iac0aGvnlsErprQY169FmhdCbfFH0uRC4zP17Gzm73cETlWBAoxUpKq2cCIKOZpo2q2Y0JZC4PhrvPExSYBK4MQCJnjmHkwgAYshPkJoFLeThc9tgPOUZTuWUEDJ0+RDRJzfXhgInd8BAZZa5NwGEHiOimTuKRTEyM0vcswTkR+75R9FIfDBibbUcwcDtSLPsZJa4sgEEfyNTBaHWsDIAhH2MnMdrqVQYAkT2jicz1QYHtODJbnFtGwNBPB8MlujIAiPxomPgRFtjbGa2ApTwcLjI7TOL6cMAOck7YKHJlAQzaJ2MXk8hcHxT4cY+MjueaNsDB6aZILzQ7BRfZgnMEs607RvlrE3DYprsYH7yL8Q13MT50FxOkRpvsUh4MN3aNriuV8nC4idFGo5SHxLVT7xgSRMPYTTNg+ElmdnGJ64MBp2Zn3inwzDt9Sp3D0ShxZQEM2njPB9/v5cY7vhy+5zO+KgO/KPPgRkZLM9cHAMZBuWfZDG9LHuLxZPOJpxHirgWjTyelL5e4UOaS/hujQRANbYMavdMLHYXn9N3dgSiLAm9el1ogW8S+1RKSzSfBJmxvXvPSJilV5mM4kYttx0dp6h3I7J69XquPNaA6G9MzwzkoOz89cZjPG9K3E5DLzAcp3laGKOyVkE4po4ogBYsLacHEnj9zFNXDqaR0gJJ5HWEXJlHq8ASvRWWJF84bQ7RRaiENGN9LIcpvpaOTLijL580hu+nChaZh5Hvp3ia8RKuXLOr7nE1YpbN0X2FLSK9q0H8y/BgAIHXltKuKPlItpAFD5pnI91MInIaUbt0FoOE6INVlzliVFOG5m0tbkSLmby9Vqc2D1agVtIK+bjQrc8rEsFpyVd0S2lCcyAgGfj1Z+4Tm7UgZwx8zpOnDgLKdztvpqpgJDVOgfhhmN1B2lig2RkrMMoVFvZyoLjvozOYVWja4POYDa6EN2NpkFhqA1zMMLNAHL4fzh9RlhIVNdOY82gNNLq1Goe0UbxW68rrlvNRjm82M0XJ1INgYJ158wglpzY0ht208pza3VUJ02oFO+pQtV1cesgAao523l3I42NfMrXJSrLM2ysnUFWPEbRvg4Hb2FM/cD6WIX1taqsKzaiT/dqNMnbfxIbncPR5nvqo3kGQFaLcBaNtaKtEKArBUa+Q/HWUbSb4SWVzqela3N7Siw+pNjKvqOIuac66GXqfr75p4hp1/5QJEq8mSqNNHNfU3VFq9MMNJkseZ/lxgTm50I4pMvCovma1OkHqpHZKEt++9JMs1u/JeGrG8RXR1V2hokVexe8GXupAGXB4ys1R9B2gVPeMJxRfStFJKOpe1HiZNOTFubkutWBl5bN0Ol1Po5UUpUmVBQ1S79LTDbxvhbGiD4SY4Q8kRZ3aauZqrLoPYfRtg+ETR9/Y8nKkR+p4JMPjcWEHJFYvJFkaLVW3U6jN4ivA+tSGqvaptgtCDROy1FCaScvZL4tLV2Ah1zwRsNTbCnMOks2eOVSC9obFLO079uiOYNotWs9+W4o1/34BuCe+E+XefyE9kOpZgClJsgDXtxpBR7RrRO76CbRYFd2fEEHDu8EGW+SxpWgLOB62mSSoDIFr+TnrEUeQbK0ATxgy4sowPRmrAcZEmqbbznIbX5ipaOWoxXs/KdDdN3rAD3cuQlhOH/DyZLIn01k6FzsjZXKrgxklEE0V+6DWgoz4Am8oSTkbmBfl+3m7ogXzgyt0OqG9xjbii6k2JbEpCluUqDTuFumnr2bz3OJATQZyvPCOJc93nlkSi6iQrtWfVK8bz4hA0E4D3IrFSzIEFSljriItly9rc13hl8qx7JKT2wLslyMozf7Vk2BjEq+JddRy8WsiP0tIaHRA7T832oyg2URyA06+G7aWhqULg4n2u9yRDyY3anglnAF5HUPNm7hssA+54Hfk48e7poW86XcaEQyMmtzHiGajXEL1xu4LBJXLZQ/fkdSeooppklro2oj03NZvYAv0NjYzocA158gMSM+NvQqD/gmUpVA3Dm6LaCzBcrJx/GQFtaOuvt3RFdYp1G1gsDpLCZFbr4DS1kaP9TEWUyH35ZzVDqwo0RF7yuVpTFLyWmAA1XOagkfvyi21kZIEJaIQsGnEFZd7e873saTMrkEI6mDov1m6EaxDafdarkNwrsAZiKBF5VJa2OZg5UylqoErKeTO/ss6rskuM7/ih7esO8WoOzRrOZepoJ01h3R6hccY9nUCzaK+meFsWgMFJQaZHTRlFr20AwxfHZBllr0wAo5st4W0T2nOEtrBmM9uhFqk/p8F2o1kBSpcqslpTGDAPYTm7yhtasshd7CP5YayR7qxg0KrohQSv5LWgbotUKNkoCe7fBPaRdC+3wJQd7edUrctk1qkqZYqU1bkWXKOGzAnOdvXh9uZ2Tmi2qyiRCek2cPe8Y1yF71xqxSJl7lvUlyqOdF9Vqw4WcuXB7rCMDVEtxOx3tgcKP86bKgr42ooA6XeceY7DYNod5xzc0EVjoTCDy0swtKagFhrddULb5e+h0FqCz6Vxw4Gb3M9p3NwAyd05cL/2oKIAmDWiYE5bhQDrqWutLffN3RTc8QNhIBbEiiTQOsmmlaysu68Irb788u/jl7kM4lqttaGBvuJeKfgBI6aR7jUSuBHHupLaUPrS8FvVy/crNn0tDo0WsKXDGsKe8pbbw5E0mV8E22lCS2JPeUMlMrwPLles79Q8PXwR5b5OmlMZltRdPa0BHhWDggKBsY84xMnMs2FEKdXQ04ebf6yrCG3mEa4isLlLrSIsiMjJXMg++Cg9QaLVivqAs8NmithAgmQypWj/G3bg2opaTh8tRke48s/F9LGyBM08wUzEVanpg+WZpzVRaINVas8mbFWzsyq399ssHeY9z2okCh2Jjavrd4xAiCAwZW8BlWqVGmQzDwXXUgRq5qHYQIJxN9tlKLBaDqiZhwLjYlCtKRRXpbZYAGAWHAegQdUI5NNIiELF6ig+n0VZ39vPWZTVOJOLngs6exsJA2alrykz82QnuuUsyPU5SpH5FBiCAmtTzI8K2AZRjgDYZ5l9vEKLRPUYhT6Hh1yAgspV5nP4boD0ObjKfI4gBUiOUmQ+RZzM7cAaFKXIfIrZWxBbGKrbDPscxQ5ZfZJaZz7L/F12LRSFnXQ6sa/1+7B5owfqKXv00JDR6MNOXqwPwlX0+lJ9jEAtQoGIotxIDgLT0JrJRHfsgaROW2h+CmkcpdxKHe2TlFnxn7uw06pDaus5/TIz/zzndnnRPc6Z9gcoOOQhQMvSEJpPo7NXqkUzY3+UKJ9mnizdySWtg6VLBc1nLB2eOU9YxPMIbRys275oxPVtgyjH8B1iAesQenKaMxxtINVzugZmONocXEVzhqPNwVX0ZjjaGKWIFgVYoW1r6c26tGFKEc1Zl37nmKntORXOupzD3OXDBkmtoz0DhGApdXRZ4HrHvp7u7FQbSeHVG0PrtgkiiHPWbRPk+bbcmu+AQuznR4WoJAMqB5KM9NEB0BvWXG7WygNLTIunjFU4aHFJqyMP8zp1pTinMCoAL7X9tVtI0JkTheWYf+6u4e6zCn7g3yy5oYxgqUiTyo6R7eTJ/cyDM8V50k4Hq3LBGrY8q3zNyTRhilCUGrg4ZBGwUnXSY8gaQB0TShvL2CFrQI7QwlEctbqEIyJrgI4s5gMsfq/GLle6pEybcHG5cidleo2erEHVinGndL6rdJr3TAC2vWNmLAkM8ALWtwJXvLScXb+oZR582co8M4Up8yyRIfDiQmSNlA8R/2bCCw0UlVmxqsWpC5GodQhnrqgbKoFJB4d5axqjdFwVhLB4BGbjJIlo4G0XZvLQARYbAeFnHawB5EoXhPKAUZYnRkCb0lqswFUJpB4ZqERgNch89TFVd4xUHMBaY6rKzK4vAAf0ZJETqa4V9nT2vmqMk9FWiciBDEhK7yyiZ3W0AcZQxlDncwKF58QYf/9yd/H6FWSm1qqgCVbLWmJLUDltnl8bHib7H4J9DhKOgucHEwRNNKZo9fShstoUsA4tTN7+/oDuQZtqJgiaVEzR6ulD5a0pYB1aoKN1PBc/IP8OMnu5JmiCcVFLZAUqn82Sa2IvvaZx8lSPWxI/I4R93PgI/7iRemqnMXa8w8wdEt0ROhEsHi5WjxgfrUFrcwrvcBFexhk4T+Y1Y8tWBZRn0RFrb7IgqcnSLcE+RilIj8oli1cd7f0x2O1exs5u93BELI4f0i8ApfdWB9+SsQ3QMHMzQeTmPrarZ/bUBGdZws0p+9tozA1tcHIT714qML4wdNa6EYhnv7tYOM3CQPGwvspvMK4dHYszz+kImv6XQXyV9zevXG5jnHjxCSdIZrUK8o00klZF9Px5U8Kam6d8Q232i09MRON1ADGV9nsBpc7scirG0tyKX6rM3WQtZtLbbV2L2DjMA2CwWlMPT2MjtphNe0d2rTN3V/YgmN727JaO1hbtMUC1vdoaB+jMj0HRbknm9NWNBCi76rYgQNMEh6UZB6HRmMAx6b1+364RcFQq78AbGkKk2CHYUqfBiQ6Wo2/6RCEOdcLGksnHHruZn9ppHsdRorrTDSZoz0DGexUcchwyHUqQxlFkRVJbzXSz+u7zKD9jxkH2O9XyURB6cYJTArS4ax3bQJ7FKVonx0SGV1n6BjuesXR25iE3kinIj2etbQEUBCd5irOI5IaN8AL8PXMALnA7jjOv41FyoGMMEj9Ac09ym8NfWgN0ADsuqdjk33khE2e50bYJWh+OSxSnnjmYXbq0hS2kF2mS2uYAu6flfOjaW2UHDdgBt7yPMNqj86Oba1sAOU+6BRvNDCmvRN4wBNFsOMEy2A1DENikF1iIu2EJooE4oYtlwJuWYMB3r98sht6wBQP/+mK3GHzDFgD8cakqegStou3udYkGvW0OvjdfwIeuPbh8uEd+PnMX95x8qM1t4+kyT5r+AhWllX5IPC4GNS0vSkGWhEfYEWTtamvwyA0B1pjCyvwXT1Vd6NiD96QMyLegL7VFIG9SzGPn2S6Oceji0PGg104EPo3YhWvevCy1Zx8SIe9NzxbozL14dzigq6Um3RgyCFTOavmyJC/SkA1aBfcqS1CYxighLNzWae5xG/M8HCFYwluHPe5a19+aYQmPEUbuuv5ygiW8BV/PVXUWbol30tQdfiK9Evm7eKCzqtt9lqVSYKGOZwbLEinATvilL6Ou63wL43kt43b3LqYI7l0Hdo5piHySZHmaYddOsyiZe+6dTGbRWSz5aI0ZBnvzgZaK1TycMg7mJXtr3rg7lZV1I9+J53EmnR+0aHjmaNqnEbvwM3ytQAczc2p+0BChR8KJnUl3hgwanUmazp9Bq0bHIvSEBTrsM1/+JOwb9XR+xBN9L+cGRll4VRrzMHKbWZK2aybIUXIlytfX2mZg1gdrzfmhndX5geM8N4Th11/G3ABeaWlKE9tJFD8t5UnDHLgr0CuAY36ArvU1hc0thoy5Y2jZo2vihEKX+AK6Ej3lVtMmuFNGli3GPNJYoJBwB2UZTrNFS17HJNxsiRsIkOfvo0eT/gzZe14LSCOjDcCBYp125U6FthnwIu3igxfCjnVHXGiaA3cFfNA+5sjMUbqEG7NPypjhxbxjM2SaFRNLFV1PBg2C50m1Akl6zMWKWM8ofC5xE4vlUtMg/KTjhJ07naPuZ2RS1ya8U8u6Y9CRYpK2lCOVNWNTwoU8aZgzMyVcyA9uy/SUcCF3+lbNTgkXdKtp0+CUcCGPWgaNTgkXcqhj0tyUcKlBQcPette8qzX77ax5Fzx2Ou/gsqGnFdxPviDRsvKsp+2eiTclquRqP9kBf0xFM2AB7tLMxuuizWPAbq1Oel0ymwVDBI8B0LFSb9AfsQ5UHLmkuV15A74NGIbaatG2CvwAWC67ABsNUWIt4tKA4Y03KHTbC3bsKJWKZzgqBthdVUzALX+l29j007AEtnmp1LT3KCEFIVvSj7bNbZQ+3Tha4z/2YivH41HG55+11rtT6YBrEWh5fJFeRNZaR6WYkbv4wT/sUOlaxWoL6p7wBY7X01wqdi616keqUc4EuUVEVIYOorQgElZDSiuTuI5m9jSRgMoNEFVb7bmEGt77Oc6iKDvNaZoUD5DsR9lGWWaTCnbvOdh2MfuPF9J+iS3C2NE9ThLPVY05LwgmLWlItRxUqcdLhKwhSxFqc8VJrbuUOnwNtmzqRcHeH1GsdlJsfaoZLxLlAmMlNTtIqQeI48Hx2EkWpTZyUTxjmXaCT6Stw5vx8x5cfFB7zjwC2hPVI0QuqfCZl857NjnKKZTWTs8Qs13j4LRCaT1a94l89hzW5rp7cOJBeT1qf+egGBy2q6rHGKOHxGTRHdbX5MaJF7kkz0yyj9rQ40+fQgccuCOq2Z45Do5JcfPSDL5BE2rr8eLHclvQPgpdLzwaaCdGTejRl00P6YrgcNuaenynKM0MDBaEwvPDwdM6kKF5m52GR4B9US1C34fGaylqscENmystXR62rknKxt7zvUxtd9EEXV9Zs8WEG+TDpF5RbFlkLdiawCW16NT3JY+BKW88FjKV7yyDUTX0TJ6Csj/qruUAnHlG534FBuly9vmxOLVO6flnPym5ZPUMbcjGMzocreuEZmmrkqiegnfVl0oc39vrPiLc557vwsQyOTrznjYOyDlRkuHHs+DyUkN1yGvVCqyor3P657CR7pGZ3AulkzFHCjQ9IZOVB4tkpVWnf31F47zMpvH50U9aDs6PKwIqoxPfZEsH3a50ytfAEppev1R1RwPS0KtzYLRCaROrc2DEg/KAq3NgsF1VI6tzYLTD+sZW5+DYR23Arc6BAXdEwVfn4Bo0obap1Tkw7FETsKtfYMwCYagZPwRjX9LsLJbZmj+J9bU3KMK9gLDPnCzxIbKiTBbL9+tcaWnDvLzTELUzlN75OFPbmK1I3jLyrN+dgFzUbSSZ5vquVG47yPf3xJ7uOpwIu28AFJ2i+uhJ8dVZBfSWATPoEPsZpvmVNzhIORETo7T2GqJvyK/ROGx3GerxuNvBL0DBLhD1l4bqyqS7NlSVl3pliCZJcymoZUx3LeifyzfKF+pVJoAKBL12K9jbiNnYHbJiqw5/pYVN1+1qvqVbt4VLvWVKVzW/ueTbNAy05tv3rgRY3LmG3efchg2VduIe2yv6DMs7Ry/2gDu+R1/kM1o8uMVuARFimKwJDYN077t+f67td41h3O8Vff0HbQUaS43Psx0oFvAaC6akDJjtBxvGRN2FEOYfsORQf9OnNMPB8yw4BbvxFqUw0y0otfF/wJLReMKZ5vsEZWSI+DzLCKvPInfMtzIiq8LmZhTvH7J0JfqZvmZpSrDhgpPggYJSWP4HLBMn5cgYWyoShJ4Ooj2c7oyWDGJHWDA69v8Ry4fzTGe5Rf44Zic+RF9cLpx/1FnPcx63sqxZYPAqHrh2rD/nsqF1al1v6Zguh0i9pq+oTHQNbHc2XlCPxes9hsY6rdS2aBK1NyI3jf+XK6Lbe/ykssgsetx9/sgUNIoRXdVrSoHsogIM8DEZpKp3R3byEteOUZI9zQo9U4Rg9MbDcI1KkJpWqKSR9uNBoG1fe/Tq4hWes6mYhSJqpKlVJZDV9JNto+pbAdjXQUQvL8yDt2yAHZvpBqg+QcEQvNgSmAvEXvkKo1H+lhmI7UCPtmL8VhXmWh0Gde/fzTiBT5G4bQQG3D3ZyDdWL1sGYICx49hOntwbLRttI3Dgd/jpiEPDKd43BOWAmyLj7A0bMNiqhzAqEkOeu/hoBygzCcvlgWBx4ASxSdzKAByw2smiM4DhzhJ9JDNBL/Ayz2xj1zYCA56oHampSJzAHZ75WBzkbY41g4Olw/MLPONtANU5QMsIEPjlAtyX8NiN6ZBB8LYV6EmXOfCWDTOTLkPwYksALsTIdRVPj1LhbsiDz1wMIfeMgIAn+Kj0hogaMVdf6e0xP1eObSyuT1EQky8S9gZrSLdSGEmzktgaMAe6lKEYx07Zha4hA+swi+CDHpdbrJYY5K4tQLdqdhm7xSy80B7oCo1Z/toIEHSATBMXFsAXlcxStw0ZWVgy70DbGPTikmn+hh0g9CSJEuMFpzICuCpmFhny+Fmi9mA7B9OlozYCuJxnFpmbAF3SM4xcGQFd1jMPDXcmdGvVzSx42xDc8p5Z6gRyjpuZ581mAc+cMLb8e39zdf3L7fXZLT2wDZ/dXJ1njxm8rwNm1jh/hidDZ94c7LGb+anWvo8EJTK7TkaywyGT3gyFmZ15AdZaVy79sUosq6esdcZVdkowYktJkIwtVS0+fhAhKF5TFITOpiaNIFbKepxksAuP2BDVO/rN946h6iGpk3gtVS2+fWgHud4SdBeultQjQyl+8wpmlbyH2NfWYyXZkQfFtlVQzrYuBKOZ9OxrQ7AGkWsCs5QFIrQT9GCIkksDkpI8ukcpGSobRG7Z0GP3I6dadTRTcocsaHE7J0xVi2EmwCPK3jhJrK/HXKTBQ4L0Jsc91rauHqP+Qnd/yDlvLXtsTGx7QQxbTMXykMQmKtewCT3yTO9Bbg8zm/HMtsNUHKhhJBX70lqk2IkrMRv5sANTkTgArYEuqyusRxlmSRQ/2XHkw+Z9V1iL0g8itZCTk3iVohZXQORTvYdpXbBaUpcMvD9saOqxxSnEg98eXktWm5A91AEHrFS1+ehajua+IBFgLatNmCXIgW36Wqp6ay/IpeNnULqGph7bnZnuuKOrywjevjQ0NdkeEi+DLXkNTZA1P0M5LFLX4k3YA/nMPmE/xpoP0ru0Am1tViPJ2hXWokxTvzzEzkSaCtW1ecsgk9Cgtaw+IZurpzmpo6mZQjBqRZs/8FIHHJeLatMR4YtLM7MZsTwQ8R1+gq9ebWkt0sfXL/9gprT2lLV7Lb5mV9RZ6EdWPXWAFUHYB7wz3+0dWauEx6t0gXLbUDYDEtqIzFdMlUauDVZ34IulUB2K101Ic1wUKjqUsMOIHguVeY4pF0YNQnmV+lFmByhERxwYbMoEZsA8yKKEyBojr+WhiLED29z1paFIDwdX7yXvEVSuDcWq/fb8COu8V+eHWQNkrNUopaFIY3RnrGpxbShWMjM1hVpKg7VZ5por0BRlfT70mkxHG3g8YYh27juhI7zQu4wE2pCsJp5SDJswNGozRS8wY37cuYwvbYOQYyBD/KU06BjIECrXBh0DGWKd95LUMKuRBbQBfTBm4AfvfWnIEaYh0lIadIRpCJVrg40wUehGAfy+sGETkGNjU8QAOzTaI1hDoCloWeguaZiC7puBXjkxRV7Lg797xV0DCUii/X7WSHLrRqPg6ctf4OOf4WJQoMSDaRp6iKUwBGMaXphhLIWBGOG2WohAZ266ENIWr84YQa2lITjZKwlmOCtpCM7GCwhmaDsGIJhpYH8yTj5EZohb8hDRich/fN9Qa9UUh2B1zBTaUheC8ITI/3YvzWA2xMFY48jXi50wTsvlQXjZiz1wbwz1idsGIJjNtV2grZYDNbXtUc6a2IoZoyBG2dnu/NEMaUsehJcWJBu5v+VpZvv4iJwnvj3BjAOj9kx5dEjIzBrqHQUpn5oWwb2icy1moDC2gFcCi0a8SnO68oyzZT0TWAX3Lk1hVo7GvSmtgNPTjXQL4HMzcPyGKz1oDW+ETjGE3LYAQZ0ltpvsDY11GuIArGxDuBHQShmE0sy6kQu2buSezMxwSl0AQuwAPbnrInJhGEZDTVOlDEL5G9hjmj7nb/Me0wyQwjxX7lNChQEs3wU2Q1lrQ5CCvfTZ45z34qeQ8mhopeUIttJyunP1IoEPIXJhCEYy+TXXhbfUAWj9wEzvWOoCEJaKJteA+iYguGH2+/VYZ2z1G+B7bQjwNRQhDqLkyd7nhwNObOT7kZnlqgE7AB6EZAqcRs4dBtrt0iXv6EMQe2TWeAcTv6tHW2sDkEaemQpW6gIQxthMf1rqQhDCRCroAc4IVjDA56QXO0OMXBqI00xrWikDUX5njPI7KEoer9UIaEMckNXcGlPPAiQ1pTBLzS1AUEf+08XlS0PVrCEOwZp49yjDNnIcnJrp+vsmILh5lF8jxA1xANbEI/2ge/HGzGP3ljoEraG1qVlbRoWE6QmZ2RnGhWEYd6/fmKIspWE4L01RXsIxvjY0tqqlITgNPeeDe7LHQrgg52RmBNBSh6JtBJwxB90xAsUeRXeewaSu5IF4M4/Oz43x1vIAvPVRDiZwW+oQtF5gDLWSBuC8J7XAA3rfswva0AYgNbYrAXAfAgtB5CRmOoWmOByrmdrfFAdjTc08pmqKK750A3K+Lpl7gJytC7+Rj5BZsPv1yqAAxQYglNP3eEO09zHscmnNPWQK3Jdyi5CLYxy6OHQ84MFL36UBi6Y8u8NPBM1LAM4Mlvatb9OUd+lTGIVPwM8bB/1qWtvuGx4UH/7tjiI9qG7mhTQURByl4EP9RsqLLcF7AnR+ooQn4AcodvRprSMdFF3Cgx4ZCrzpW4PzqNhBb8qDWh2SGHwjQYsY8k2SVhwRwLAxAvCeEQP8YYYfs3SBFmncojnPlqnX01bNeWi+DR63COcZEU9gF+UbTlTicLwG3uBoAMO+qVEGDTHxKLfBDPw0twpuURZBU9gtA4Dc3u/mKmUlDsibJbljbORQq8MRG52WGZh/3SM/Nwdcqxtd0YE8RXr0koEfh77u7FVEXjgViZLe8da6emv9muIktYI8dCPrY4jf0cbAeofTuyyKrffX7+x3XhDgxEoTx+LC3TTuxsyIJyPhzjJf6kpYnyhls60Lylf32TpGboDPA9cAQUN7giL17SPKMtK6J/eeQ5p4zP5D5/VJwAZmdkTa/MRzecjSIw5xgjIGS1orLMTvWcWPrCa6n1B2+qMXoCMuIW0vOL48j8PjD1brGpX7LzTv32nef6l5/yvF+1MaHcxzvOzJJs2fvXu5e33+5nxnxUmURU7kW3vSxmVRlJ1IWfQsksf77PyR/Algo9fW8vh1MY0BVXxII8d6f3N1/cvt9dktdvIEn91cnWeP2bj9srWmP+kVf0H5E2nzLoQk22/YyazBZC0HbMQcrRzWrUeuisL3aJ9af/75w25n3fC4U6B2STtSnmtapDr5bKOUpEO2gCE/OppKxtIU0YK20C//ixjZH5d0aX9MM+TcWb5vwh7PpLJDsBwWd6gIQJcsb5BUZ1MGrz7c3txaV1GCDdXfnmtl57pgYlbduZeZNIcDN7m33ADR/yxox0p3ZI53DBEN1mfSpLn6Xdsh3adJAwki15N/Pd+mlmI/P3qhdcDFdmcDPUrdYpWpJzvQNJUCxfKFdYxJOhgvpNQKO3IqyWOjdS/GCduyhhbpDiqXlmzF+kYNdgujnlooCYwbjtKMzA0CAykrO3j3jPSHstaNZi6ZjZCfLbZnMoijEIcZ/cBfpk3zOI6SrAzsshEMIoxTDD3qV6dZoEB2Vu6WMleGLzZdtct3dhdsOjsWF2g3OxbJ/XQOv4yzcW6+Yw/vg8uFrJhuhIpUi6MHnCxTJgfaGfqOVTk4W24AXAxKlxpt19N4Y8PbIZMexvj7l7uL16+WtvwQ7HNjE7Mho78/oPul0tg5kbELPiSXu+Lfx+PucWl/UzJjekD+3bLzxhidkdap3Me/WB6LbFcpv1uWgn2mAwq71YCytZbVSDJv4cZ70dUsOiRFntFlmK6pBQZMlSnfTp/SDAfl/kFv7/k0wRfxFuOYvqu/Sv/vlaF/1xl7lO0oZ1hh8umRARB27ChdZgmHCPloqFgFyEmid/hAWzHSun6tHhSzB10vP13tdv/2808qN96+t68+vrsm/3z49PGX61++2Lf/fvvl+gN7bsx2Y1BnWMHXk716//Hq/9gffvrlp5+vP7fUW48UlI1U+j99+en9x5/tT5+vb8lnPdh313+9ubq2P11/vvn0r9eff3rfAi4XR+ulPU1jH3569/mvbQtsDV1P9udPNx9bonTNU0/yX39iKf7h4y8t4RPy7cHxuqJ8j5qK65Pf/PLl+vPnXz99EZbA3mKiijH2oMr+hRQY+683n7/8SguLzt32v17/9O76s/2Xm/fXLcr/5//Lo+x/OUHqpXZISqB97yVZjvzzU/GLitkPf75+9+X9LUmhX/5y87PAlp/9r8YSE9+A/ke9XPj08d+IY6IcaA3S5jjy6fYn++rzv3/68nHUp9aRpvN8+vzTzXv7/c2f7Q+/vv9y8+nzxy8frz6+t29//fTp4+cvLYsv50j/+oX88+kn7kZRGkSZ0xhYIqgcur0WZk89kNTsBD5+bucJPVd2TiJd2j99umkpXWg6/v76+tOXmw9dx6uhl678TVk8O/J8dKUmf0NS4d3Nx5+ub+3P1//vrzekzyP5dvt/bn75WZ+zKtIDwJ0xmWaTcHt9ZX+87fSw1YhLIF4uBv+l2CinsQ9pzhYSOq9j79ZZR8exSOnN8ONZcHlZX5FgH6MU0yv5d+doM25Ue1NqJ+jcvElNNwuSEShOtoMtTHAf26cozSqnmgkfhTQkhLt/Li6QP/ZHuhmw6QT/stgC6vgePWDyH8chOuHZfCFjuNXV5MNlu4LTn9lx7tt2g+cLDexGRrm+R/7u5Az93W78bpMZ7LOpP4ImoPztuXgwWmGekRPFUkHXi+LbZ+IGGUqH2GF7ntKcwGWkKxHWFtGFz6na0IZrwLFn06KdkC90gS4bEB4Pp7vn4onTq/yFJ85zqf/ius+cWLUBGHg+Q2PLHHFY7C4h3zW42ecy6Mf+GOx2L2Nnt3s4Ipv4/ry8CCI3J7lQPYajHvCLJDypjvEQLUcLL5W+ULSgLLwwjEjxEVxMyqT/MS5nmPTDDXvrqfr2PHfO6SfnhLyQzS8j9v3YZedOnHdXKMqCvhTBoUNwiO9fn6XxYub9CJGR4N7rLMMmotfVZAjowxS6x2gcgF91zp7DYFL7XNwiKN5mm0XA3n+bsF9cU/7n1km8OGuZ/xf+JKeucPRKWsfP/YWS5pCH5XCjGHakUAmkyOGiDIEzKGRSiMLIdmjzt1YKRIGX2YeEtE92XGwkXwkkpGEh6KRtxeJAGJIs81YoCPxt1w8oZl3GOv47Nj2y0WUtZLPnuPh+IfuPjwME//N/Xny3DMMDSkIy/UnPke+vlA0VAouTsjZEjF0UZp7T7soH3r82miGkM2UnuqVrodArAu939hpR+2mC9/tSPRY9/NP28T1ul04XH1Dui3aEiSECdIdZl4+S4JzOBTKUHHHWpRi4rDe4PAvINz/OGGJqcmSnPNh3SMrvlgHojnHPAvLNj+VI98y9eLMYiHC0S3Do92fk+x+VRr49M3UjPUlUXzrUo5ylmfujSrcyYiOOFYBowI6hTqaAUuppgLFE44+zQxidFd+uBjUwMGNozd+WLVt8zGQPTbRIoxQodA2A6bYgmkqK8a7U7o5tzv6NfbN8QpknmpU+/YHX2b+V362YRkapVNJpcBx09hGkFVBNIdM8KmkzvKRwdqC/ndW/LZ9Qi8KppNr4gtDZgf++auqtAqlUL8cXc84O9IIzdsFZdcEK1XUdTKVaPDDNOhO9Jmm+2hqgES9ODVw2vJqst4isScWWT3uLp2dk5oWd9Ef66zn7cymeathXfLYDFLfJ/m+p9/Wbsw8o/vFf/tvHX798+vWL/e7m83+3/uW/ffr88X9fX3355acP1//9nN0syV28pHFOo+eVq/td5HKrfxS3O8jWM0HwZPJSZ+BgESb83kuzSrwe0vjfnp09JCR5SBuBsc1Sq/FlwM6g7n3tiL9OMP++55wCSf3OFN0J2v+WJDo9aNJGTjEEUTZFZ1K+aAuqHOTRGetzrDoXFfOXbTz6ZwZPZ7B6GpMG/jz1fLRPWbVNvctd0fC72XmxRd1lmxTYA83zY5ifV83MHpWhOxtZ0ZCrrz0vLiAt8sFHx/SfWbVEXSR30xnbWfLwSCrlMcBhBlIpZxQYMnRQKDLl1bzQ/LPIPPsiMziqhGnI53stM0JbpEWthtlSbWrrQRCpIjTZzqPshBO60XhjCTipIdjfNE0ckHpCUvLMx+ExO/0oejFsoZZNKeua1/8z8yAzrz9WhG1kjDQVvYaRxjsO9mDQj+RDJXn24GWnMzbp3/KwUVXO8RIn91FSnf/3NH+nwna8CkkpdntLCmp7DHRGagCu1KM+xSz6gQd5qL755oc/PQY+vaWIgkNuujh/yUSIWkTfTSNf/frlL2fff33xp1qIL0JUO19z57zYv3ue4iyPz6/Y+4Sfiss+kTT/M3Pi5yQ/kLSOyn3E52y3LlEhejFOsqdbh/yXyFWLHN0MiYkUS4/bDMd/JA61Pq/gaLkv4xZnGdvEouyhZZ5RPxsWgMydElO/kHTPvy3XMIea+e7l56nPtjVkePTU3M4JGOdO4vCX252kIC6PIKyq4lfRsRcD3bzkeSz9ov7i2xflOqP9+ePHLy/evvjb1xefr9//9OXmr9d286evL94S7vOvL/5O7rm9+fDp/c3VzZd/t2+//Pru5qP94eO7X99f3xKB//hbcQYo8eW6OHiBNJ9v/+M/v6XHjwTRPXbJR9aGfltdeBvliVNcR1s5Fn+0PnmgcVLgt62f/ego/G2f0T+K2M/FV3lSHPhW/NK8tghKIpSh8RDtss4KLxDEXWj+TM/AKN+lFP/I30CxkUtqSOalxWFu49fKXMBf4Bq6NitfjHRRnKHxK50s8Sd+TZ0TppUzoQfQRTTa0NANraA4dpQ6nu+jLBr0un19RpcQhq6MksHfGgHpbddxnaHreFzyod95kGQb5ykixdILU3G5EMQYGfi5RBu6qhXWVPKqBB9HMrQdN27gImEMjuFreqHoJO7JBmtFHZyicQVtPYoegLVDvId4++ED+/Ib0s2E6dvy2x9Jy/bilGXxW8t6eHjgQyYyerLS1OI9B2ZROsiVdcv7tWxm6Zeeyz73e56rAkrU8dD7YjdoCf2RtbThN2VALRY+8JuYtEw4KSye/w/6r1VeVzXR3LU/suQpEYnzVPfv3+q2sfxJ3ecv1/YVDwuWlnkx8Biv8UuzvaHPUod+OnV/qkKQ2Q7KSOod+5fge/rzCYVu+aB27Ofe3VUdLa5I+wK9K4Y1WFluVHYUOqOK4usn9EcubNesoSTxOo2NXf7U0+tdmCUoTOnrdyO30D6uPrV6Qp91iL2LNlR5v+CAvnKI/0GqL03gcqTr0d82k9KliQ84Q3Qr0SaT++sL4ZlwTEF42pvwl93gL5eDv7yqfpl9qtro3VrnpRWlSLIcFmcefludayhwdvlE5QdBfts68HAkvbROjrFUjjM8TXKID19r/Dlfg4BqyZDumv+3TN65d8+zXfJPC4wct2UVkQar9X9dIbr8pqtRro7o6LDZT3B5qaERxLmNkuD+ew2N7Hd+GLmsyNTxhlZrUxKsqo2qQReU4j5PUACvmUkXMklNJ8ihFVmvguSrg6QunbBDS5LLSOMMrRogopyyXZGRdMMiKx77PrAkBi8CxcwHWPSQJg50Vh1jJ4EuVDSarwFJmx6CBKx7OsAn6enwCC3p7aDzyEPgbYnnIOc0Na5TFfVJW2JA8nGPoNslLkuXyb0QvDv1MVsIhFY1UP59+PIfpNCFlcy2oRUT6Cwnivx4VWBlMoqCTtAUvA9Nn1LnID2/kRQ1UYlyE7XIxADiwZWfL05K4qCc3oMplrtOGau2aLE4Y6UZScY8LkXHp+ryok1QSc36CGM2eZdZeBi6N4sCT7r6tu/dezON0je1bccn3N6BdPSZwiS9K8QiZs+9V2mpont3Il1W23fiMJfuLdp3pnQP5cxbM5Tl0g1/997EC6WreuteDyCrWZjDqpCrVZDy3vIhNo2bEsxTKJJ+3q1F8s27l/RayPdT2bs7p2KzJVSF+VPz9pKA3S5pvXu8uoVp7ssa750HX/w5+/b6OHm+F0Vx+NNSpMlRAimlRu/o8PY3aixtMYrUFlMia5xKWuzIae0bUDxAlf2hcautNN0TCZT7iXQk2LYw+c5QJHFC0stJA7fbB9JYnnRE6N4enfujPXtAqaEQo6NWXmYJkh8JigTo4w3Fes4EaJViJVm9JvFby5KsIVDvjKMNqc23Gc8XrEuVhggrVRr3l6VKQ4GVKo37i0IhLUDDJbNOLFAcYLduVXrI0LlToQQ37qPn2M67UX7S3b2vPOVy3u1KY/jOrfKD8N6N6s19Q0Bhkb99n9JMXHCrTkqrDAVbN6qs77ZuVFlwbd2osEbXvU8nhRSW3Vr3JSigcWnm3auwfNa6UW1Jq3srDbA//1atyqO0bNa6U/GJfn0vnYrOaeJo51G14kpdR3kntTjnPjz3vqKBmXOr2lSvcSNrHubcyJqHOTfS5mHOfbR+z7mP1dE5N5YVbc6tRS2RvLM+XZbP++mgT2EIIRZQ667EGiq9jlhBoVUeFGDLbpoyag3uoIZCyzumodoEN7TKtZ1GDqsXs4aGSsMhVlCol2IBtXoGeLSLAXNTZ7DMMEnnBBYTtLjsY/Er/cWmr3zT5VnZoiSjzl9LATFQHpZJPusr8JffWJRztj4t3SyMiB4wyvIERCo4SLcPIyrZU6xLU2YhiAh4qnNdmITnatppz4V0kj/286MXWvy1ueYrdDNbuDFFLcYYnZHWsRyWp1X13/XfdsuTe90E6Rgr3qHjH4v2Ui99ZAxAe0DTpSgtBg2Y0Ba8z2gwqYTlCS7dxt66nHorU6/MaVmG8jnzeq+Rgnkl0p7JXb+8g4tv9770+t+YFucDkPMwxt+/3F28flX8WH8GVOa8cOKp5+IH5N8VP/FPYKocGEr4ISBT2+J79ieMHqcEkfz9Ad2XpZT9CaPHEZUk2fkI5OfWi8LkW96WVBs9qm/MKdv0ncM0U9oIMsOKc8LOneIT7Tlm2FTUpAHTHijuL55hgVyQRPGTQQsnhQfmM+TZ/ooQ+fYdfjKZUESeZEfi3ZuuHNQQe+ldYVvXDDNsuw2dmxm0oTTNmqGvMkOSlPea+qqz1zk2ePk1aSMgndI+egQzwfe/1T2S5HBUXbnVI5mzUnYV5gzwdtachZPCFpIZ8p32z6yhqv0zZ6Zu/8zZUFkTkpQX1ms9E3VcpjSP6Yt3fN9hM3YKchzs4wSi85OyFwWhF5Oml9xh0hwN3WLUNdoaI0wP94L3g2o7TmBOO0COMfGjQfD0hC5Miu9evzEp//piZ06++tqUfB0e0KQFFsDVlA+eSSdoO16FDWDBGKCb77YFUtGMWKiiapnWJ62QUQPYcUluk391h09iM40aZ0i+UVjNWPAgTfA1s1KvNtH+XrveSdqx2ZIeRDUcMsgNlMM2erTFora0E5LkffnuERsVVC2LORvko8WeRZsQrlaMsiRPM+zaaRYlCu9EqNiiebKUPfZCX5U5xQ/EpvYq0oQhFk4xRgkNUMmPf9TvmKVNQqwxCc3VXylugp9pBGixSWiGzBnLZ7V2FQjfgzXVHnRANnVtG+U3XpbaKu8CycsPVSKjhpolujSKMHIXNwqyDqZuFmDtSt0o6IrWPPMmq8mEeYhRtapNqDU3oeV+e23WiMrmElUTphqcoX5A0xTP9k5Xrdu9DMjaqfR2okllHoKgEtZOiZj8ZEdptSe88Y0+9Yi4vSdVLcCZihkWudVqHTdQRdBofgmvqLRBakzWgyTlpaGlKF0iZBWLLfEKRU1aWK1JUpIFhPb6yQGRbV1ZTq2q3Tg3gxfd7lEaOpJlCvdO51BP21KCpwLzPm1oF8lRbfrVlC8+NvXrdz2Kd1WADLXT3FGJlyClqPLGk5SgQsRGKb06XQ3Jqs6ZheLtcuyoBCCQUlR5bUlKsJGsirJVCJdWyiJyRRHJOiRX2fdekuXqWSbWJtS9H/SVy/To/aAafGnKggcAXx4WUqVG+RlKR/HdyUm54sRE5Q2BE6q5PqIHlXQeEBYvhJxKtcwN6Ci+Kjkpl5CRdHLEGc1Z9YZoULZdTqBU8xmet8/Pqp4Nt75VzWQZzfKkLhBpr6+dkalSeRBYlkTKzXHHTJxE9CConj3+PZQ8bzc78qS45HuF2bnQCH8G2c5ZA5q2+xSiwKNvw9LbFFfVFOzE9JxXU8LKi0cK+mXRNyNdtFcg4t16pVnMxaJzEzrOq4Yllo4X0rybJ2Ccz5h0tV7zqjakNL9URZpWJCPYfa48qhDpepCo7IlP9V5t94jFOXkrr4+DV/ri7MxF24+iuJ+JJsXL/DRqYt5yzYSNTvGhB5/e02PlFIsRrXzIqyLY0r9nrQcO6ZQNDYQc6YkdnNLtr2q7Q9uKaRUVpIh+5e09n67v8jcait90kkDOgllv6qi4vd9Uy2FlKumUECAdXkIA5DppqqXoAZRhfoxslfXVN9paHoxYFbS50lJOtGGtMrKSQkAwaVWS0yZkVaJXSYvCpKvXkVXN9NzFPqoaoeLTTI3SzVJD0TGRBjv17U3AIgXdjstpnUopuHt/7IRh51/IDfRGBOk7yfTEStciblnFst5ZcHlZX9EIZ8S/m4paNGKPF5O2A3LBPkSyaYacO8v3G06weCUNahpwl2QfKd0zsCv9skjuM9v3JVft5PSKg+OR7+/JL5Nr7Aqatd8GNOmLxpCwMfkWZ3qKZW0tFWV6f0U5O0PpnU8x1XXFdYy0BdXOXNpGXLarG/2ZBcVVL7lCez62T1GaWfQFppiUZI/83TRY/m43fmcrStD2eSoLbC9hKgpdLzy68G6RP1imdR1jXy5rrThr1/E9ulVsBcu0J53V5E5aLqYLXdNlxEBge6ShDzEbp9tpvqdv/IVHYY0RXWik6tDmYIAAvp0gIzihLbZWgBMPpztwk06vVBUmHfAKJC5IzNrc0sQ7NVbflfuyeoyhf3tnOq0hpjHeqUVYIwymI7PwMaYitZ1hTEAycPWQhKdXQsrbyUQwSm3kolgu/s6IXLvL18umQs4lSZR5qXTMm3E1rbTiDs0cs7Z1eCsP4BV/+kX7S1d2K8CoIn4sXxyqhjgQqiUfST0tmWJkCVNa/Z2DYgjfYvSQABdWum0ockm+wsqmT6EzW6eayzQbUOVJTDV5FzYXWnK9pNJR61dTHTVxNdVRHK6mOqrd+qWj1apfOkID9UtLcrh+6cg269e4Dgu5m528xCXuJdlT+Rab7cV0DFl8SCPHen9zdf3L7fXZLd2dj89urs6zxwxE2SsPRXXKMy9ZiQpl3qNUtsC+oTuQppv/+doy4zFV9fSRhUoAF937d+VLb3Jvec4w4Z5s5E+18nN0J0/vmSGKHUcuGvRM7Tv8dMShmQQpAjmYkaYvoxtIEongiHNUH+zpozBm6AYoM0Ab4MAJpg5Fm6k7Gdlyhm6ceIGXeUaqyPTb+jNEJWIAyKrSHnaPXl1cYLnBq6qu5DmnqrKvsOTwR0MYlPjywghvLQtHW3winVEdyhKOWSAOTV6PWOCwY+S60+FbVRTL8Q8cYmvsY0wXNAHKgRQoa2O8A67bGOsAa/NxDqisRBAGRUU2XoBVLMYK4JqTkVkVNRtjBFDd6bgAioISkQbUFBN8VB4XlVHHqjEL/zxjxjcolXjKs6VBrTS8gNR6SLzJTbTSgnuU4jdTJ07Iq3nHMJ96dUxejb2RPK9rGNSkDwXJ6OAw9VKvtKKDAuz7cMWFBkiEkjoh8r/dS1i9OPKVp0nDitJHO8hrghYYFk8SSos9lT3bnU/FVldQZM+2kPtbnma2j4/IeZILp6Jn4pBEAY0YY8YIDUXDLBTWzBlJ8xgnKc6MGkpT5VmInPDj65d/AFaGzdI0QzTknheAdVdOlthusgdrK2R20CqIgY0/3BNYJ8Ai1cJpwRUQ7PwWozuwooEd5UXBQSmpU27k5SRCk0qLHeGGB6c7V/mpzqAWDf4OWTP9yQOepaWq0NCgw4zAhVN6DSZVvDO7zw8HGhPSJyNoKOmQRjeIZDZqy0vSDQR3D1BykQeWJfHksd7yUlPxiBSUnPRiKpidkhpYuaNi34GJlS/kQOuBjkQqUYlTpeRFydTq4vIlXLYUb9yyDTspWLWlI2dIrxOPVDf34g3YPDWBG6TQs0EAtXav3wCqXQJqvYZrWQAnPCmNLoicE1i1ZYJsgSDNvQxuwM50o+jOAyXNPNrfQilmpwSjOQ+aBgW9AFBNblu1tBzk7Jhq2U4CVqxLPbCcLfRS7UkGPYMAboWUqsGsRdVKfO0D5eRvHKK9j7UHfX31asu4dPD7+UZoYO8YeXLHX843kz6FUfikP6lqGKAlJfPCIuhwCtGaCsSVDlKdY2D+/pwR8WKlF1QQYu7aEFQ5q2KWbpjhxyw1Uzi6RowVkq4hI4WFKCfaA9aGHsxidkMQakLWkExxmbaQmt7voPmSZknuQFZi6BZe6lS7QUHf2ycoebKQ7x1DiWOZJoWKZ8mzt1715NjD5OLVVhgpYLIgmj306CvZCZq9ECZWI+7eo5TUMW3ZxnN4uDQM7SDXVimfH0P0kZXkrC1uYhX7IUHK24/GpHR90+rta5Xmkz1d75piNlUBxQMrr042u6viEkW0Gygg7MT1WXHT579K6sG0GOUDNDuOfG0//SCa/8SBiwSuzqPthgpELQziVHPc3VTSerrYFKKLQ/PHY00lMpx1tMtQjFyJwxymZe7AahyRgsj++E5rB18lwwflmg1w+0GGrpjswa8KSjJH2ynL6SZ+LQczXugLAhIWcYAACQGG5B05oAaxoVpO3WmNpZu8zCnbIZ0qosybissIYwPOD7pjBo5YY/+NQO1wmDxfW1kOjm7Ouw9TcnB0UKO4pqT+EKyhNn2YpKoaHBvbkgYHp7PDTSCXoNCNApBpUlOVDI3hXNZ4+i5QSyFzI4XMi9SP+IFFEkey6igDMpdniQOySp1OLqUINQClF4EN+hP27lxmn7APMYygclBo3b0MsMLFoBFAqVj2AEo/Khh4qXaLz3ZX+OnFJVhvWSve4SdtP+u9GpoVgm0N6BYMvw7TSc+6q06XpPNA9gjNjsjoM/Fc1lL8J7kliNzcx19fvP364oc4iX7DTvb2wwf25TePgR+mb8tvf/z69euLU5bFby3r4eHhPPV8RA8ligKSQtan4qJzTMf89Mpvysew7LYsyYsvPZd9zp3zwu55irM8Pq9Ot71lH39O8sMB+ZH9zgto/PKj47C7Yzdoyf3x69fk69fwm29+YM9Q6CaT9JuYJABJE3bh+f+g/1rldT9YHQf/yBKtBCVJQHX//u3fqq+uH9mTmZT89B80rRIckORzyUdCl+L63tsoT5z6uk2k6RWbd5Uan6I0+zPd//HPtIVIWxcfUO7T0kojwqb/TFSIRP2HKqpfX9CNTEccWuep77ApPrbOnaQORpZsqQHOHX7/P0ais17Q3Zd9bPfb04ZSHtEY+fY+uyqKxarJ/58vvn3hRLGH3b94Pk5fvH3xHyRDSMrhhBRft7yM3FeKfULZiSUfT2AajJJH4SvTPkq8o0dGKNW17NtySyj54oJ8Yrtwwox8Oru4eP3m5W73h4s3rDA0bfN87xofGkGhOG7EBCxPqpAdHlkqQ6nTDE+/+/71qzd/ePXqQt5PtcGdMtHF7s2bNxevXn/3hx7SRLa3a5tijn93ubt8+Wr3fT/DJa3OSf3dxavLi4vvX7++YIX+9ubDp/c3Vzdf/t2+/fLru5uP9qfPHz9df/5yc31LagHh6tRLZuFvtIaliLRKt1nk3P2VxpbYk3pDv35L//nb3+m/f2ck74ohg+SNX4v/94IO/T/GIf/4lv+xPwa73cvY2e0ejoh/+S3/o6jDt+7d+8hhBaN3/0Cd4T9z7r+TtCEp8b+vr77Ytx9//XzFkuOHP5HW8ZsyaX/8+uLi/CVpoXDoRHReQ7749ctfzr7/+uJPfyRtT8ib1rJJfUy9H1uN6cPleZQcrd3LlxfW//3w/tY54QCdeexRv0Na52/IHW9T9i13hwiEue9/M9gk32Y5Pa23aJFJ45lEZIqaPd2ShME/ViWKtqIJa0MPke/i5JsQBfTnooeufu39vs/oFY3f6RWkweS/F2c0MJE8KTYu8lu+yRPqPr36rXX11vqVVObUCvLQjayPIX5HHw5Y73B6l0Wx9f76XVncyjMQqaJVSFkjRqwa3CrIG540OEkDaaOUEDRjgwMQCnWtYQY/OsIDtEUHrDf7K3EYcACaaSOSdOaQJjkctlOMn/cYpY7n+yiLEnAsCUOylFmCsWG+jolhss7x5DZt3sDZJowM0yXI84vF1TjzwLGG1Id5umfIwvIMqQ/whPfBpV1O+GFZBpQHOFrP1QEphLrDeVONOj0y+HJcBzx7RgwMU/WOlIZlGpQfIHID5Cb3sBg9zZFeozxiDLjH6KiO2C+Pv4MG6MpOEtBhI53tsiOKyQyBDHcNQY1aki63xcHwpotvz4rM+EN47AX0UERoZCyXu8cjGMjeERNSPWqrt2GtmsEOdsyYFC0ySYekaMpdY8DjtrbosPUDLjZMghMIhIcpGuftQnMIpUdaqOKxI3yb1NOdZiiHBqZQevKcqDON7iwHlOtRw+sF9ROA4TWD3qMBHddkHj3ILhJ0l3QhuLqaEv2Pbm4LTQ8Xus9fru0r/lA6hTLeVx1rBcvrbAdlyI+0y3sjBYTawyj4nl56QqHrF9uXgTB6urIIcMWwpysxhS+uBisUA9IKIHDJIZKWAGEDDb5iayRh+hZksRprIcW9BlJr0NBsSFNJKDI0COl1Omm7lIWjG7Mgj5UlKEzZmy7mAYW2ZFey4NuvQf2R1GMLPsYyVKw+gVMHHDGJNWxlAM/3wjuc0G/OfReGpSM5YJhilQ+tPLq1AcJyV3PIdP0sF8RqLTdhECizG3Jyw3cvIHWnNXhvwNG9muzt5ePL8zg86iEyS1ZPciBd6usu4E1fSJrewZveSZq+hDd9KWn6FbzpV23T40Vy6On84AyTv+rZmV+2rnnHZretK3rX3HrEbBS+R/u0c2Hv0j///GG3613UV2S7swTXdXsCdjS7zfY16LY9QxuCeCpZRVJYDW8t5o5V0FpdGGuSPiOjqjzeCn6Xps/fm/MPZN9NEZtmOv9aG1J02/L5KVDyWj2cySxkd/CzRTcAz1Ekwfd5goKtoFcw8vCZsyH4AkYS3gnyraCXKLLg7KEvcjaT8i0gSSfoE+Kt8HMWWXSiWgbj3AR9jSPrQIDIXamTeCTbtBcGwfzoUcm6ExcxbTbhRMkiiY630wZhpTaoWI/aDHtFI4l/INY3U4ErGEn4Y+wkm2k7KxhpeG8zCc9ZFNDtONpOsW8BSTpxOmyo5Fcw0vCPG2J/VEH3dpupsiWKLDjazkCNs8iiVwcVbAK+opHE98mIaCvwnEUB/XGPNjO2bPIoukA3+nrhdpYXRFyyLmG2fWgzntQ4sg5sqfPyFTsvf0Odl6/WeQXpZrqAEkUSPHY3s7ZWosiCJ5tpcEoUeXA79Y4h8rfkQBNJ0pEk284CG2eRRE+3s6qQKq0qpE+pc9DeMAfGXtFI4m+qd1XtW/NNda65au+6qfUo1eWoB1d/mygUO2eZRMdBufF6ffIWyvRD3+ZT4tXZuzTSz3yFXwu+FH3VfW+ehtgY32HghY5gZ0F70xzKosAz32mWEUEIkdUy2k253p50z3wD0WYrLU6BOZGLbcdHaeodPKc6MWlB0AGCCXBvffJBhKk0x2FufmrQTmRucgqtCMGwdDWqjE6XVh4XfNECyo1K4MUewPsO6oCV2WnExHyn2cVLhJ1j7/21LCkPEF0QrjY6ied76dI1o7I5nXYoy83Pertpx41aUwOB/nbFRKJPL9oF01vjSqfYtU2jMlWJ/pPhx2BhyK5pyaq1LGRtdBKPzHaR72u/Z6MK2DArV/sX5uM2J6vX9Di7DAA3PtBuBaqZ2swrqsGCStKKfUPfJzKeiKWrVst0VXOEPIKJT2+42bvRPiHze3/GnBmDmvRo4F47Nb8XWTGDGliKXm3Ik1mlbGsFbGbZ2l6xGi5RQwse0ysSUm3fOrnJB+JCHtU6tR0XpOi9DeELWKTKn8yAugxEAdp58+AW7Oi9papv2xFef7so06W2vINttNsEOyeRRo9xwg70QP42HGjzmGw5W7m9VI3t+F62OF0UtYK3CfbhvaZDgfoW2DAoRT64XXC6xmyCv80zw436lPgtOVNTzWsEWGXqvy063g7Y+JBc7h6PC7wsOZAcBXa3UWhzzUuQQk8hRRp5QceyqydN6YC4tPQIoQc9dCgLOuKpA4kuOG9p2O50vF2cBbreyuTSbQ9zv9MLNFnAyg47BivJ40x2zDyUfu3Abp0X6oXJ7ASpl9ohcc6+95IsX7C76nnN0hrRtUchlNJr4O2S1DO1spNDSPNqk1R74m0qEfiijlQqSOTnYg8/plwaR4NrMcqwWDBdDVdbLvVKg1WiNQAkcr8dKH516gaHAnyCM5QccWanmbvgusCgE30eBWfIPb63ryJ0ru1LD0fBlXwTRSofKFCQ46uq1i3WD3BveR/YAJBYPV2b11MD7rUPayfz6AviklV7dR96OKpVe3UPctk88LZBLsAAG8e0Q/vDjGbamos15W2zvEHvw0yX1855B+4T+YlMhRJMTRVbO7fk1BCgRPnuHUzCtjeu6twIlHLO8SHVtrKrSaWcR4s1QlKZI9f+d/yPo8jfRFGbAJvl2PY8mllzjptr5momk4PybVS3cswCUNvKVNuSHw0m9T6KtJ445AfpZEm03Hqp0DU5vnkFNk4i6lF/WCY5MBtOTK5MRvP53vxe24EU5BTdzqVPNz8CqbjST6fMWqWqSpNO8Wpygb+b158WxDnQXCDOl3xuRsxVnUdl2WhvEZt/x73pHG9PY+H77LPzu3UOwNycn36ZU5yG3QM1Fx0YtoyzW/nG+2Gw6Vd7u/fi4NUGPSqp5jeu7Cww24+iWD2jV0yPGruXJvOy18X7fLlVdyWHajZ1txberK3m19ibAILuvX1zTIBRZv7tR0nXRvD0+vqZvVq7SqyTSGVP10OZngCJyv92fKiBJOY+28kIAQvY6IMOaJDXHyzMG3ESpWVfLiuNVgPPJoDEdJ1fXo70V8ducMjMzru3LVVI2/hiEMnUJ3MrB6epjZxF1/ZFGdBHMTp7qYrq0rnG5zFNgBl1ZW1s7bK2pgN9lJnb39jr0zR6EI0+gTJv7/mECGzVSqi+fC0VczReIBcyGl+54pZXqcZDicKjQrTRZGYg5S0rVxM5v6YrEPzKXH38NsxwqdZbsEZxk3V0gybEdEvaOIOcTgNZXMot0LdolN0gxYkeHbQZR2oeZVeKQ5A240mFo+zIdmpGG0diZN6+dcEmtOODiMTkoLbRmKzgcxWtqQmhlFvrUXcpwCb4uYt91B8QzuqwCq3FqmRhjlfH2vh0S1Jca6MkuH8T2EfSKdyuyNzhMFkBy0RaqhiX3pYVrzY+t/ROB1C6+nB7czsePukqSvqnXkofjil4Q2yxeILMOYvyV7Fh+wQTpb+44Z5QLTF4HyRuAEwAZ7+z3Rr40fwUSkDbti6VtscFosIPputxKAx8G5QFpgsuL1cBbRqfAKU7BWjr+P0aoC3j5posHLjJ/XiT5Qaof82cTroQMt5DM5eswhi7o7YL27u1/d/xQxymF2cKoMXOoWglCOsOK1arjzL3bd4ylRd3prYLNiwd2KOiPujBNPrzQknSiLtamQVLERoepnqBFqApaOkt1CK0bLIbexTGRr9tS8sUiLa/tFz0KMDKR3gfXALUFypDDw5Dub9UKlGTLHG6ticGB/TyNRAl0ewjDnGywGkHolRs2JZBXeYYRBHoyJGHfcwlFstEkHIRNfml9sFH6Wkt0Nq6DO4iodtEpJKB2ti10f437KzTGtWmZUBjdFynFnHDMpBZghY4kUdEWVmWwcwzb7GBeRuzsmws5Eyzoys3L9u+F94t8Dyj4TC9fpxEpgNeAVgSrexb1kjRyrJal7EGasu6dJexBqlkUNlmu70GZm1austYA5Mblm+L16CsLM8MYclCYUg1xwsF8Wg4WVi0OtZNLjT63n58oVHUd7WXU4KFNhAwWHZp0+To+R90S1CQL0tWGpziwktzYUmuZaKEtdEGI4J16RYJCt5iGwr+3SXzkLtwFeAWp8jo4e/LknGLU2T0XO5FwUqDU1z09OpFuUqDU1yLbJ1rgQ1tj+uSFXssl2WrbU7RLbMvrAU3sPdLLr6tbI9rfmRCPWIPLxomJ3vckxcvi8YtyowFlgUTn2Qu4Cq3Li+O17A7Skn3my2egm2jU6m40BGorRSUPAGVVZ8llq5a9VW8YtUte8uczNoud3IHs9L+BwWHPFy4pWsYneJbatdUi29kp1Q/dxc4NbaTtxKHxpbXLfg8rEM49jRMNFNbFBDLtXcLxUltow3GRBXTrdKt9UxLzSoXRRw62Uc4q1yUjFuUmlUuSsYtyswqFwUrDUpwrVId2nZl5r6L4pUGpea+yw4DMvHOWcHc1zkssUzcYKttSs7Ml6YrbcrRrTMO6NuWW0dYFHLg9Z5Zq/0Jcr1ofLU/QZ5v958J9K6L/fwoiAHSu+5AXKAPbKTejeYXG1+pYQlhcV+twhmLm7c6KDIvQlfXmy4cCuiq24bbGYzOnCgsZxpDu6fbz5L4QWHCi/tJxnygoHaMbCdP7hc4Lk+cem1frcoRa5hSWCaGkrbjOxWqzRUHrK1U5DueD5FN1gDhjZvIzCEyKZdodhdHJm7NJRGZtEub9EbFkV693GbZk8JUd3abpVIKc35/1NBuxWcTniA5kYY9gZVa3zEkSwJZsej0NdYpOFpuQxWizFMtNZm3fjHJPEsEpVgQyE2r57zIE+2QPLLvjIlTZ+lEqQP9cuvTYQrYzcHB/Hx+lJUTSPIWD8lsnCQRDczsLj/Q7+CLgSS9WeZg73EHBo/xHmA+YJTlyerYTYwJ8hUrpGRtXLkqKtTDbVXC+TVw9eqnVPe2UPEma5300SZZ5ESiVbzOlXtfFCFloFUiFy8+ECk9sYhtq8MxOYraBPQ4sXS4Sozx9y93F69fyWdXfc9qCVAjWGIquTzclidSbshm7EOwzyWCXfDUY5evlgjMutVjkcvELaBPccvm2u8P6F6h4WSXr+Y6s271WORybQvoU9zSB6p4Ln5A/p18xvE7VksADmCJiORycDs+SDigt3pw8kRH5Yiee6k8IHtUeUBGGew0xo53WOD5eHcUSYwXj8Oqh2KP1iCZqPiICtD2XJL3Z7hp0CloKM+iI5Z4nE48YKwJ9jFKJXoMfkPxMqG9Pwa73cvY2e0ejohFhkPLJn/pqdVxxJLhnGyeuEgQubmP7eo5LhXglrbm8BQreIzy6W0iLvW/G7BcEHoKJkLsIm/0FS6xUEvFDf7we32AsVUX2Vfa9K0Mqzq4uxSsjMQ48eITTlB3TUD1XSZCW8T8Nj+Ur5l5OjUsT7z8wi5daMO1mFNy53V59SIlTwwqtbW5vHaJzaZiSpldp/WlNg7zYEXU2r4M8EIbUsW0kjtT66uX2J06iCqzTbV19WJbVceQh/esSh1KMhXRod3imO6bG46WXXPbuHRztw6oVHyARqOzDqXMC+btWrEO59A73bMGKSl2iAe9s636B2LRtyOiEIfTQVTJgH2P3cxP7TSP4ygR7T2SDTjTS36vEkeOQ6YACVroOKUimaxmSlh9V3l0mjFQiZ0o9c1REHpxglNibtNOdjilfIxTtP1cFEFqLIdKHhBXAi1wKIhkipTtT4NrMoud5CnOIpJ2NsIb86SHNukMV3Ec882+kisdMHlHArTEeVZzPCnJpF3BjksqKfnXfCjAWQ61+RTqzXFrha2HJrOrkragxY3bcqaHJt1pbdObLpvGzgfJgzp5b7CZfpsfBltzTeYp6QBstEDQdiUfGlDTzYUTbM+BBtS0A6S936AHDarphuGELrbnQpNKxoXd6zebdKLBJePG64vdJt1ocE26cdxipT4qVOp257opN3poqv3+xrzpssnmzT3y8wV23c7JmxoNeLtKqS98fCu6XG66XuRAloTH9caEtVut4SCHki7jhcYyr/ypOtNhU/WpDKm2Ua9qOim/UsxjnNkujnHo4tDx1lxnEXg3wijbSHlZai9yYIK8Xz0uhRl98Z5mQFdJt+LQEJxUKaxvLkvx5hrBQUJF/7IEhWmMEmKJK52WOHxinq8jtPp+O+yh1PPxvObV9x1h5D4fzzmtvt+rrharui27gDwpdIefSM9F/i4e/TybBOhzw6TFBruvGdz6acFOnaUvDD6fZGghm1gabu99TJHMDn52pmeIfAKcpxl27TSLkiVOg5NJVjofJR+tMUiJ/fw0Z56Fn1OgEr6yd5U35VRFpBONTDxT24qbg3Ra88gteTfCqLoGsNjL5jNzbzz8g8y8ciuODcFpzCu34tooocbogkbUpwO2bZVOCVYNn5eJVaHv71hIC60VacyDd4EtR9u15lrj0wqAr5m1kWRW/+o7lgl4q+6JUvTbxm3rrp+MOaS0UtK8kSgnUfy0RZ8aaIpOrbm+N+aRwkpe87ZtLGaMOTZr2aIrcEKh63vrrUJPOdjkU3Rv9WWHMd8mFhhGHUNZhtNss+Wygyc7r+K3B8jz99HjVjwbYjO/X7AxCFhpwFenRbnboI2kWGxdfPDC9UavI8400RSdWnVAPubSyAh8evS4QX+GDyAYb07WXsLo+jQIp5hP1doj6SU349wooGrOcYGtODcIpzqhOWHnbqmj4GdkXJdP1b3tOjbbpWKit0WXKrKZU9AN+tRAmzMF3aBHnEtvCrpBx/qEOlPQjTrY5Js9Bd2gby04jSnoBl3r4M2dgm7EsyE28N3efDUfbm290LNT88dRDT2z4D7xhYoWkfFJvLf2WxCV++3nNYqPoWhybcyDEsnAGw9lVFDouuB1lW0W2G/Vt/07RPVG+xFSqWLDb9jGHrgBLwcg5TZJtDVXfCQrl4XSFV6UKJtzbgDSQIcYEzY7SntRCQWXS3cJleaKbWrF0NhW06CS3ChU3mHvUUIyIduqR20+8wFQ+190ovPG7SjQMmdMda4RHoHbN1MeizIVWbS+0lQGEgv8CBF2rGxt0Wobnz5/aFXYnv150V6phh+JYnj18oVcZqrrFPlJzFkNsxPZwa9cMCOagNLlZQXGtmVzgXP3fo6zKMpO4w3GwMF13SjMZOZMZpvJvedg28XsP15IW142mbaje5wkniuKE94LVSwpZTJfqrThOSQLZSk6AJa9U12H8OCkeSVCJpLy/ohic2c71qcQ8Wwql3IqsxPhJb2VAD1VQjvJotRGLooNL5pNEIs4pj3IeBR9Fx/MPWscQe8ByDAjl1TQzEvNP5MaJRdiSKZ5iNmu4VX5hRgy/O4T+ew5rB1196v6MIgi44e/c1C8Kn6XQIY6Rg/JVqrAMIuUJzjxIpfk3la8GeWR8Sh9Cp1VXegASLWmjoNjUhS9NFu3ORVyyHiAH8sNKfsodL3wuHKbNIoj40/ZmJEucR0H2vZliE9Rmq08CBJCTAUxpzUmQ+Y37QyPh/sAEsy+vyZwy7oE7ToTjcquHCFbcyTlZu/5xMpavH0KqRZ8nYmSSgoXhZxFrFqvjnHzErxmd/+OoQ5u7xVQlm8Dr8LZsK1+rsj+KLdqJX4CK5iJF3Kky9rnx+KENGNPJfuJws1XT7GGeAweINY1umCZqNyvFyS6JPMc9729xDHiuee7MrE4jo74KZ5gQTXJ8ONZcHk5cL18cR68Y+xURmEOk7TgVoydSziStfR8QpbSFklGq06h+orGaYVNUHG0jJEyIPXzWMQKiGM3gc5GGlgmWq5lqhqkAYx5q1Wr8Asx5q9WreLDIIryatUq+F0CjdWqVfiHWTRXq9bxZpRHdbVqFRc6ADNXq9ZpToUceqtVqzgyijNn7WcVLwQQarPSpan75ufMopjC1CTKl9jiJrvte585WeIvnWSlo5bv16nX4pB5yaFxi52h9M7HmbkNuoo+tIDMv4C+0hJiIwkkVxNH8tFBvr8nakuu0ogc6MMoOOF74Z2Pngy+gqjgRAtmjhNL7yKY9mRwW8GIOzGRpDVxA340UOY3CvALJI/H3U52aWR6oaO7zFEXwyXXOaocqFc5qJvNZY0W2NC6xuaXLcTFQaooqK2T9fauYTZKkytiQ0ObgcvVS1k12l2ylAkX0Mp0qcpgcyGtCTmyktb1rZTctGsNRui6JCx7bJecwfLETRS7Sx3fo6+ubCYDOF03C4TIaiWtIUH31C7bbmt7XSPP8PqZeLpIHWssiJitZcVUv7H8kmb5dlrxBpiouROCL9L+pU9phgOzWVPY2Exe1EjdrKhBjad947lFmu/p4emh6O0gwFxg5Uxkdls1RUQorDKjriyQf8lwBkDmV4I3lDUJHsiKgtJ4qp+E7+VCJzqxQgcAHk53m0l7wiRM+g6r+RxwDI+WC6+c7QyiCIs45Z1lRlBL9NDMoY110+IuukO62HqLYCmCThaEr+cN3kPukN48NCMjj8VW0Q30GK20sajb7Y1ATdBnu2QmWjjoLx6fP7LrFsoOOtdrmp18eqj8QmovEEHn9+zkJa4doyR7mnhBuQg148VTq46kxBTXppHE8qPUI8s9enXxCpveNsNeD2+kh1W5bDV9Yhp9oslnE+SWy4ttudDikTygxw1QHV11A26IqSSdIWrlVu3NeNJCmn7g9WgbjFClQl+TyEDv/TvDJ4cosreBZFxwTzbyN1GTWzAy6NhxbCdP7jdTctpAsi7c4acjDjeUC30oOVfcFG3KiwaPjAMmj5ZRZJc/TebRDlC2FWyOIoWNAyeItwJewciimztXaQa67ElKj2R25AVe5m2nyWwDybhg8DB7RXbpQ+sfqwPuN0CdyWLTycEFNrwzT3W20gKScuFyYx5cqjrQmKBtxIU2kdqUcRsutHjmTBk34IaYatKZGLmuwTj4Kh40UBRnWxuA7wFJuJDgo7G9nGrsnERrf7efC2P0dWtPFMTkY8Le7giNnqUrmwYluzWAprDsYjAuirIzXSjl1aPNOaJwvFixbrMRD2oatXbN8DH2M9wQsimsK23HkxpICj9AW2IvaBQXxbbD34aasTC2LVfaYGqLY1vypMEk5USSRMmmilUFJL2+tx14+eO6yLUPtnPYUtmpgaSXKLcDz3EUlik3BF8BKSxVbgtf9tS91urgdlxoQ8kuWW6HP5GfcWfbIs8G0UcmrQ2P3t9cXf9ye312S4/3wGc3V+fZY7audwNIcyO992bpwR67mZ9K7HZJUNLdO9NLQIdMkDMUZnbmBcYOvO8lXemDVUJaPYqJ0xmyU4IRW2hai7hFMEHLD6FZDbYJIMlanJu9NnBFMUVNhr3rAjcApo4+8b1jaPJ4rEnYFsEE7T60g3y5xfEuam1+ihOl+M2r5Vfze8B9jilykhl5UGxjXY26zSBHvH5a9znkyIPIXRu6RJDmtRP0sAFmjqHETXLoHqUEbCMOtHimPPEjp1ovXb/ED9FMeOGcML2vGLAu/Ni2N9YTs0x5UPj8kKDlpu498jbDFPGyC//9IfXw2v7wDMCm5lZkFqGo8a9dRYdxpvzIlnsI3oPOBp53twiLcNOrp3AfY4IbO3F1uY389QbeIhAp9pW7zy7EFHOYJVH8ZMeRv14p6UJMMPtBZC4o1yRsZX2CMiAC6XKPMbuYtflpzlV76ob9KdI4XfoRfQ+2hSDByx6SrYpbEUjQ0nWyBfd3iXBrBAneLEHOek1ti2Bq1Qu5dD6wGmvD/hTp3frDhg7DNPGqLVjD/iTpQ+Jl65XYhn3JVdoNlAURyQR9wrZWZPYJ+zFecNNEl13AIUG+epJ3ISaY09Qvj7dZO72FJBL0ZcC7NbFrBBletrqR5qQup+sXl1EiCW8CL3VWhecAEqzk1ovL9Wd5YhRp/jv8tG4lbWNMcD++fvmH9Ut5j0KiB+Urp0XdXvOBZ49Eag13vU0GI2/RD641rwtbMUiXiw0UCCVeG5G52QagKw6FGrhucRaSyNO7FKooYHRQY4cRPTAk85wtODQKJ+9j6keZHaAQHXGwkcZSgKTgTxYl5MZN+FGjyPNjZ70GtY8hz304uMsFZBgB5xzy5ItGwBghHw5/MUQeoE20RCWGPHeM7jZRQTmHPDmZoW8BvMRQaBU3kd6pYmqz8caa618dDuVxzwbYx97UHqRfc5+dgEONfO1nVcM4s0eeW/BFgAQxkt6eZ204tZHbBrwpMRRHbhsA5xyKI7cNkA+/1DhEvvpC5gCLggcrbgXpY6iNmTfAXWIojpk3AM45FMbMiLAF6+6aHMZRG/tvgV9qd1F71L0B7FSx1HQXgbbgQh9JfV1qC37UKFJvXCoEQZJ8D7OXUEtGseEpw1+x5Z9lY9egxFu+IejBlhDTtGl4sT5tCSFFu85WHRHyyKYd4at1q0PXGNPE7HWf9YkrjGnixos963N3YKbp6eEdZKx9iNZnb6FMx0sj//H9DbR5TZBpamf9wl0yTLOeEPnf7uX6wA0QSeo48peLtDLOzVEkyNnrdeu849dnb8NM02+jBVRo+5w1Jt093sEptyByJ8rOdueP6zO3UCTIaSGykftbnma2j4/IeeIbTtZ3ZZRtnm+HhMzk13jbR8q7Jp2if3S2xm4vpDbmn4Buhn9pTlfbcbZdHwWEin6m6fJrXuN+lUSKftBNmBtzhCPJerKhZkKhTWiEfNoAfJtmmj9LbDfZb2CM1QCZpGYvMqyOXFFI8K6/duZKrp25p/VnZSXDJCt2Vngu2oXlEDK0G2jgKgoJ3t9WeaTVJ/5t+JFWP9DABnjlwqCW7/avz1tzTDOv8tJ2j3j4xe0O73EDa0xHyTWm05273JkNQ7AcYpqWTNa3MXRokUxy+8H6fXHJMMlaXr+VdbA+zrQHy+8O7VEPbAztkb7eAOprOVYcRMmTvc8PB5zYyPej9RfvBpgmfQnJ5D2NnDu8wm6lrg8dlml2j8xy75aPaNjjrjkmmSNv/SpZMkyyxnj93rtkmGZdPoJJD3UgiEmP1Ekvdhug5RhSxOu3zhWFFO93m+D9To6XR9ZeHbkBIk29jbW3Ho08P7WxHX5OM80f+U8Xly83UDEbINPUBAVl2EaOg9P1hxx9nGkPeJT21dkbIJPUiUd6UvfizfpbKFok09wbWLMb3FDcDWNyQuvvJOQQMrS712+2wFtiyBBfboH3Upb29QbGeTXGNPEGnsXKPn1loZ2Qc1p/5NEikeNuhKTaBn4HSM6LKLrzNpL8FYoUeebRNYZNkNcok+T1YUFrg7dIprm9YBPQFcYk8T3B8lZ4P7qL3OCYZN7E/hPpHScsZJmTrN/dNEFkqddvOZogktTp+o8NmyCC18Ikz5cnsx6Js+XX3dJJGC2VnZtlEI1i2xbK6TvqIdr7eL2l4tqDISxFr8qNXS6Oceji0PFWHPr0nRugm+fjHX4ihr2kPqZ+W172+eb5mT6FUfi04vPcQQ+bZM/hvSPqiOo7R4Xf9K7MC2kIlThKV51QNHJDTKXq0wqn/Er4pHjMb+duWvdIZ0YXHdccYQr86pPJ+la8g7EFX2oSefZVt3a02OXfb2pF5VkpmJPAhR6Qsidhhh+zdGOt2TjdXB+31xJME871dVst+TidrI/k1mS9RxMNdyoQWfKV3yZqoKu8NVQG11n7UXmDXulpeRXkpSx+W3CgBSPtgff7NqpxBSJNniW5s4lxSk0iy76ZqaTynPEe+fk20GsS6dUn4deCL3tfdb7ofmztJkVeqBt7lmtYIgMo1g6YXUoMymvmbikhlKePGgJ8Hrh6JhoyQjOpbx9RlpE2Mbn3HNIwYvYfOh9PAjYAsiPSUiaeqx8oWM1UhVvMEPKEXcK53+EDyv2MEPloj/3WN/sIJe4VmxN5e88nledH9vL+eeqRi9Nz9vt5GIX47ctz8v/JLbQSde8InPwckW4OH5LL3fn+uKP/BLvdy9jZ7R6OiNyWRZHvnEghHLGWpuf0snPqFpWr7jk/hvm542ZvL3bnu/OLc1K5dxe7l6+JLqnrY4ru3XmaIYf865G/3/JW4dw+e/Pq4uWby9evL892l99dvn65e/Xdd41l4x/wI2se3E8oO/3RC9ARlyXE9oLjy/M4PP5gta6Ru/Ni9p272Xdezr7zlfSdQ81vnERZ5ES+tSdNK8nQ7ETqskdL+D47fyR/aqn3Gnce0jKmQduKD2nkWO9vrq5/ub0+u8VOnuCzm6vz7DEbsuzi1Em8mNahP/5gNT/xprpVz9i3P1BHf8NOxj69+Pv/D99+P9c==END_SIMPLICITY_STUDIO_METADATA